// Code generated by alef — DO NOT EDIT.
// alef:hash:5d8cd4ae253ef133b0d079bf0ecee60e1d6ae3e4c5ef1fad5f53348c3e51230f
package xberg

// RequireNativeSetup_1_1_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_1_0 = "1.1.0"
