//! Hand-written tests for the Zig binding.
//!
//! These live outside `src/` on purpose: `src/xberg.zig` is generated by alef and carries a
// alef:hash:e0fd890555599e294a49d448e870447ae3725b78064282bd254211e4a0b7afa3
//! "Do not edit by hand" header, so any test written there is lost on the next regeneration.
//! `build.zig` points its test module at this file.
//!
//! Everything asserted here is a pure or self-contained FFI call — no models, no network, no
//! fixture files — so the suite stays deterministic and runnable anywhere the FFI library is
//! built. Values are derived from the Rust implementations, never from observed output.

const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

// `timestamp_token_to_ms` is `token_id.saturating_sub(timestamp_begin_id) * 20`
// (crates/xberg/src/transcription/engine.rs:205, WHISPER_TIMESTAMP_TICK_MS = 20).

test "timestamp_token_to_ms converts one tick past the base to twenty milliseconds" {
    try testing.expectEqual(@as(u32, 20), xberg.timestamp_token_to_ms(50365, 50364));
}

test "timestamp_token_to_ms returns zero at the timestamp base itself" {
    try testing.expectEqual(@as(u32, 0), xberg.timestamp_token_to_ms(50364, 50364));
}

test "timestamp_token_to_ms saturates instead of wrapping below the timestamp base" {
    // A plain-vocabulary token id sits far below the timestamp base. The Rust side uses
    // `saturating_sub`, so this must clamp to 0 rather than wrap to a huge duration.
    try testing.expectEqual(@as(u32, 0), xberg.timestamp_token_to_ms(100, 50364));
}

test "timestamp_token_to_ms scales linearly across many ticks" {
    try testing.expectEqual(@as(u32, 2000), xberg.timestamp_token_to_ms(50464, 50364));
}

// `verify_excerpt` (crates/xberg/src/text/markdown_footnotes/parser.rs:311): an empty excerpt is
// vacuously present; otherwise a direct substring match wins, else both sides are
// whitespace-normalized (runs collapsed to single spaces) and retried.

test "verify_excerpt treats an empty excerpt as present" {
    try testing.expect(try xberg.verify_excerpt("", "any source text at all"));
}

test "verify_excerpt finds an exact substring" {
    try testing.expect(try xberg.verify_excerpt("hello", "say hello world"));
}

test "verify_excerpt matches across collapsed whitespace runs" {
    // Not a direct substring — only the whitespace-normalized comparison can match this.
    try testing.expect(try xberg.verify_excerpt("hello   world", "say hello world"));
}

test "verify_excerpt matches across a newline in the source" {
    try testing.expect(try xberg.verify_excerpt("hello world", "say hello\nworld"));
}

test "verify_excerpt rejects text absent from the source" {
    try testing.expect(!(try xberg.verify_excerpt("absent phrase", "say hello world")));
}

// Self-contained FFI round trips. These exercise the C boundary: allocate through the FFI,
// copy across, and free — so a regression in string ownership shows up as a crash or garbage
// rather than passing silently.

test "list_supported_formats returns a non-empty JSON array naming a known format" {
    const formats = try xberg.list_supported_formats();
    defer std.heap.c_allocator.free(formats);

    try testing.expect(formats.len > 0);
    try testing.expectEqual(@as(u8, '['), formats[0]);
    // PDF support is not feature-gated out of any build that produces this binding.
    try testing.expect(std.mem.indexOf(u8, formats, "pdf") != null);

    // Must be well-formed JSON, not merely non-empty.
    const parsed = try std.json.parseFromSlice(std.json.Value, testing.allocator, formats, .{});
    defer parsed.deinit();
    try testing.expect(parsed.value == .array);
    try testing.expect(parsed.value.array.items.len > 0);
}

/// Assert a call failed, without pinning *which* error it produced.
///
/// The specific variant is deliberately not asserted. `_error_with_message` in the generated
/// binding dispatches only on the large hashed FFI taxonomy codes, but argument-validation and
/// JSON-parse failures set the small legacy codes 1 and 2 (1078 and 727 sites respectively in
/// `crates/xberg-ffi/src/lib.rs`). Those match no arm, so they fall to `_first_error`, which
/// returns whichever variant happens to be declared first — `error.Io` for `XbergError`.
/// Pinning that here would enshrine a mislabeling as the contract. What genuinely matters, and
/// what these tests guard, is that a rejected input FAILS rather than yielding empty content.
fn expectFailure(result: anytype) !void {
    if (result) |value| {
        std.heap.c_allocator.free(value);
        return error.TestExpectedFailure;
    } else |_| {}
}

test "extract fails on a malformed input document instead of returning empty content" {
    try expectFailure(xberg.extract("{ not valid json", "{}"));
    }

    test "extract fails on a malformed config instead of returning empty content" {
        const valid_input = "{\"kind\":\"bytes\",\"bytes\":[],\"mime_type\":\"text/plain\"}";
        try expectFailure(xberg.extract(valid_input, "{ not valid json"));
        }
