// Generated by alef. Do not edit by hand.
// alef:hash:8722893af87908de1383590984a614186cdf8cd03442debc69462f36f6797d73
// swift-format-ignore-file
// This file contains convenience overloads matching the alef e2e generator's call shapes.

import Foundation
import RustBridge

// MARK: - Bridge protocol re-exports
// Re-exported so a conforming type can be declared with `import <Module>` alone; see
// `gen_bridge_registration_overloads_file` in the alef swift backend.

public typealias SwiftOcrBackendBridge = RustBridge.SwiftOcrBackendBridge
public typealias SwiftPostProcessorBridge = RustBridge.SwiftPostProcessorBridge
public typealias SwiftValidatorBridge = RustBridge.SwiftValidatorBridge
public typealias SwiftDocumentExtractorBridge = RustBridge.SwiftDocumentExtractorBridge
public typealias SwiftEmbeddingBackendBridge = RustBridge.SwiftEmbeddingBackendBridge
public typealias SwiftRendererBridge = RustBridge.SwiftRendererBridge
public typealias SwiftRerankerBackendBridge = RustBridge.SwiftRerankerBackendBridge
public typealias SwiftTokenizerBackendBridge = RustBridge.SwiftTokenizerBackendBridge

// MARK: - Unregister name: label overloads

public func unregisterOcrBackend(name: String) throws {
    try RustBridge.unregisterOcrBackend(name)
}
public func unregisterPostProcessor(name: String) throws {
    try RustBridge.unregisterPostProcessor(name)
}
public func unregisterValidator(name: String) throws {
    try RustBridge.unregisterValidator(name)
}
public func unregisterDocumentExtractor(name: String) throws {
    try RustBridge.unregisterDocumentExtractor(name)
}
public func unregisterEmbeddingBackend(name: String) throws {
    try RustBridge.unregisterEmbeddingBackend(name)
}
public func unregisterRenderer(name: String) throws {
    try RustBridge.unregisterRenderer(name)
}
public func unregisterRerankerBackend(name: String) throws {
    try RustBridge.unregisterRerankerBackend(name)
}
public func unregisterTokenizerBackend(name: String) throws {
    try RustBridge.unregisterTokenizerBackend(name)
}
// MARK: - Bridge → Box register overloads

public func registerOcrBackend(_ bridge: any SwiftOcrBackendBridge) throws {
    try registerOcrBackend(SwiftOcrBackendBox(bridge))
}
public func registerPostProcessor(_ bridge: any SwiftPostProcessorBridge) throws {
    try registerPostProcessor(SwiftPostProcessorBox(bridge))
}
public func registerValidator(_ bridge: any SwiftValidatorBridge) throws {
    try registerValidator(SwiftValidatorBox(bridge))
}
public func registerDocumentExtractor(_ bridge: any SwiftDocumentExtractorBridge) throws {
    try registerDocumentExtractor(SwiftDocumentExtractorBox(bridge))
}
public func registerEmbeddingBackend(_ bridge: any SwiftEmbeddingBackendBridge) throws {
    try registerEmbeddingBackend(SwiftEmbeddingBackendBox(bridge))
}
public func registerRenderer(_ bridge: any SwiftRendererBridge) throws {
    try registerRenderer(SwiftRendererBox(bridge))
}
public func registerRerankerBackend(_ bridge: any SwiftRerankerBackendBridge) throws {
    try registerRerankerBackend(SwiftRerankerBackendBox(bridge))
}
public func registerTokenizerBackend(_ bridge: any SwiftTokenizerBackendBridge) throws {
    try registerTokenizerBackend(SwiftTokenizerBackendBox(bridge))
}
