// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:520ad85760a9fc515728d2d1c937d34f007b2aaa7d4378c5796f1b7ec09c95ae
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
