# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4acd260963c8cae0db1d02bf4a2a718bb5409faed37822cb58419a4f38532b0e
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_embedding_backends" do
    test "list_embedding_backends" do
      result = Xberg.list_embedding_backends()
      refute is_nil(result)
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Xberg.list_ocr_backends()
      refute is_nil(result)
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Xberg.list_post_processors()
      refute is_nil(result)
    end
  end

  describe "list_renderers" do
    test "list_renderers" do
      result = Xberg.list_renderers()
      refute is_nil(result)
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Xberg.list_validators()
      refute is_nil(result)
    end
  end
end
