# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:02e6a931edb0e44d6bd0033d6da503fad736ec7a1559876fd557988f51ca1745
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: reranker_backend_management
defmodule E2e.RerankerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "clear_reranker_backends" do
    test "clear_reranker_backends" do
      _result = Xberg.clear_reranker_backends()
    end
  end

  describe "list_reranker_backends" do
    test "list_reranker_backends" do
      result = Xberg.list_reranker_backends()
      refute is_nil(result)
    end
  end
end
