# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b278b97acacbbcc31361238b547d02febe24bb4672283b35199acb96645f6df
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: tokenizer_backend_management
defmodule E2e.TokenizerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "tokenizer_backends_clear" do
    test "tokenizer_backends_clear" do
      _result = Xberg.clear_tokenizer_backends()
    end
  end

  describe "tokenizer_backends_list" do
    test "tokenizer_backends_list" do
      result = Xberg.list_tokenizer_backends()
      refute is_nil(result)
    end
  end
end
