# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e02209c891886cab975eed85f07bc8f3296e20e2e8ffafec7bd2c9925183d4ec
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      _result = Xberg.clear_validators()
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Xberg.list_validators()
      refute is_nil(result)
    end
  end
end
