// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a9164c9f4550fa5e1331154c6a7545d4f158320ba09185d7e1bac296f04c9b0
// To regenerate: alef generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: embedding_backend_management.</summary>
    public class EmbeddingBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_EmbeddingBackendsClear()
        {
            // Clear all embedding backends and verify list is empty
            var exception = Record.Exception(() => XbergConverter.ClearEmbeddingBackends());
            Assert.Null(exception);
        }

        [Fact]
        public void Test_EmbeddingBackendsList()
        {
            // List all registered embedding backends
            var result = XbergConverter.ListEmbeddingBackends();
            Assert.NotNull(result);

        }


    }
}
