// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e2fb63408ca686312cdef661d0a7d09ab1cb0c2dd78a1341e16868717d6009d4
// To regenerate: alef generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: ocr_backend_management.</summary>
    public class OcrBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_OcrBackendsClear()
        {
            // Clear all OCR backends and verify list is empty
            var exception = Record.Exception(() => XbergConverter.ClearOcrBackends());
            Assert.Null(exception);
        }

        [Fact]
        public void Test_OcrBackendsList()
        {
            // List all registered OCR backends
            var result = XbergConverter.ListOcrBackends();
            Assert.NotNull(result);

        }

        [Fact]
        public void Test_OcrBackendsUnregister()
        {
            // Unregister nonexistent OCR backend gracefully
            var exception = Record.Exception(() => XbergConverter.UnregisterOcrBackend("nonexistent-backend-xyz"));
            Assert.Null(exception);
        }


    }
}
