// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5449864fb92b8e94cac563550c7a2284cfc0d95535e1a8e8865bd833ef0f3e6c
// To regenerate: alef generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: post_processor_management.</summary>
    public class PostProcessorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_PostProcessorsClear()
        {
            // Clear all post-processors and verify list is empty
            var exception = Record.Exception(() => XbergConverter.ClearPostProcessors());
            Assert.Null(exception);
        }

        [Fact]
        public void Test_PostProcessorsList()
        {
            // List all registered post-processors
            var result = XbergConverter.ListPostProcessors();
            Assert.NotNull(result);

        }


    }
}
