// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f0fe97e376cfcce99e867b2c2055eb5a9fe1d6f4fd9429aaaf4a4de7553f409f
// To regenerate: alef generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: renderer_management.</summary>
    public class RendererManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_RenderersClear()
        {
            // Clear all renderers and verify list is empty
            var exception = Record.Exception(() => XbergConverter.ClearRenderers());
            Assert.Null(exception);
        }

        [Fact]
        public void Test_RenderersList()
        {
            // List all registered renderers
            var result = XbergConverter.ListRenderers();
            Assert.NotNull(result);

        }


    }
}
