// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b350a062585ea5bc2aa9cf4016a3b6dd6acaed53b8978c896a54aa01d06798a8
// To regenerate: alef generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: reranker_backend_management.</summary>
    public class RerankerBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ClearRerankerBackends()
        {
            // Clear all reranker backends and verify list is empty
            var exception = Record.Exception(() => XbergConverter.ClearRerankerBackends());
            Assert.Null(exception);
        }

        [Fact]
        public void Test_ListRerankerBackends()
        {
            // List all registered reranker backends
            var result = XbergConverter.ListRerankerBackends();
            Assert.NotNull(result);

        }


    }
}
