// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:03b09928b4f831f2d01800f13aeafa438c1ebc42eb1e8209d7ebd6e9f77751f2
// To regenerate: alef generate
// To verify freshness: alef verify

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: validator_management.</summary>
    public class ValidatorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ValidatorsClear()
        {
            // Clear all validators and verify list is empty
            var exception = Record.Exception(() => XbergConverter.ClearValidators());
            Assert.Null(exception);
        }

        [Fact]
        public void Test_ValidatorsList()
        {
            // List all registered validators
            var result = XbergConverter.ListValidators();
            Assert.NotNull(result);

        }


    }
}
