// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4cfd287c9452fa4cd1c76e1de372996c2bd70b550cbf9686047be5b7718d5df3
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: ocr_backend_management. */
public class OcrBackendManagementTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
    }


    @Test
    void testOcrBackendsClear() throws Exception {
        // Clear all OCR backends and verify list is empty
        assertDoesNotThrow(() -> Xberg.clearOcrBackends());


    }


    @Test
    void testOcrBackendsList() throws Exception {
        // List all registered OCR backends
        var result = Xberg.listOcrBackends();
        assertNotNull(result, "expected non-null response");


    }


    @Test
    void testOcrBackendsUnregister() throws Exception {
        // Unregister nonexistent OCR backend gracefully
        assertDoesNotThrow(() -> Xberg.unregisterOcrBackend("nonexistent-backend-xyz"));


    }

}
