// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0088537ed7535c750c156425408948a82c569e443446ee7816bc4ab3ab6b8a25
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: tokenizer_backend_management. */
public class TokenizerBackendManagementTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
    }


    @Test
    void testTokenizerBackendsClear() throws Exception {
        // Clear all tokenizer backends and verify list is empty
        assertDoesNotThrow(() -> Xberg.clearTokenizerBackends());


    }


    @Test
    void testTokenizerBackendsList() throws Exception {
        // List all registered tokenizer backends
        var result = Xberg.listTokenizerBackends();
        assertNotNull(result, "expected non-null response");


    }

}
