// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:081859a5844a3377e0d3606f0455ee703e280a33222635c38f12aeaa469e2325
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;

/** E2e tests for category: validator_management. */
public class ValidatorManagementTest {

    @BeforeAll
    static void initEnv() {
        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }
    }


    @Test
    void testValidatorsClear() throws Exception {
        // Clear all validators and verify list is empty
        assertDoesNotThrow(() -> Xberg.clearValidators());


    }


    @Test
    void testValidatorsList() throws Exception {
        // List all registered validators
        var result = Xberg.listValidators();
        assertNotNull(result, "expected non-null response");


    }

}
