// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fa5ffe2ff6e68b16ad8be69d0be11c7a813f874ab53a6d1d8973eb6b04d884d8
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: embedding_backend_management

use xberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    let _ = clear_embedding_backends();
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends();
}
