// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bfc44193a71daf4684347599bec464f571ca19a2fa4fc221b07da3a4e026b30c
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    let _ = clear_tokenizer_backends();
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends();
}
