// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b9f65c147d6c2bb574d50ff22ddc0806651e9960a7668cc7b2372323479b38d7
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: validator_management

use xberg::{clear_validators, list_validators};

#[test]
fn test_validators_clear() {
    // Clear all validators and verify list is empty
    let _ = clear_validators();
}

#[test]
fn test_validators_list() {
    // List all registered validators
    let _ = list_validators();
}
