# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9aa85e35fb79792ed8e156cb254d2d3da7d22fda777e4bec1897aaf560b5194c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.AccelerationConfig do
  @moduledoc """
  Hardware acceleration configuration for ONNX Runtime models.

  Controls which execution provider (CPU, CoreML, CUDA, TensorRT) is used
  for inference in layout detection and embedding generation.

  # Example

  ```rust
  use xberg::AccelerationConfig;

  // Auto-select: CoreML on macOS, CUDA on Linux, CPU elsewhere
  let config = AccelerationConfig::default();

  // Force CPU only
  let config = AccelerationConfig {
      provider: xberg::ExecutionProviderType::Cpu,
      ..Default::default()
  };
  ```
  """

  @typedoc "Hardware acceleration configuration for ONNX Runtime models."
  @type t :: %__MODULE__{
          provider: Xberg.ExecutionProviderType.t(),
          device_id: non_neg_integer()
        }

  defstruct provider: :auto,
            device_id: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
