# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:171154bd9eca54c3abe090d9eaec7bd87d3b803905f52b87972f041b94f22c40
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.AnnotationKind do
  @moduledoc "Types of inline text annotations."

  @typedoc "Types of inline text annotations."
  @type t :: term()

  @typedoc "Bold (strong) text formatting."
  @type bold :: :bold
  @typedoc "Italic (emphasis) text formatting."
  @type italic :: :italic
  @typedoc "Underlined text."
  @type underline :: :underline
  @typedoc "Strikethrough text."
  @type strikethrough :: :strikethrough
  @typedoc "Inline code span."
  @type code :: :code
  @typedoc "Subscript text."
  @type subscript :: :subscript
  @typedoc "Superscript text."
  @type superscript :: :superscript
  @typedoc "Hyperlink annotation."
  @type link :: %{annotation_type: :link, url: String.t(), title: String.t()}
  @typedoc "Highlighted text (PDF highlights, HTML `<mark>`)."
  @type highlight :: :highlight
  @typedoc "Text color (CSS-compatible value, e.g. \"#ff0000\", \"red\")."
  @type color :: %{annotation_type: :color, value: String.t()}
  @typedoc "Font size with units (e.g. \"12pt\", \"1.2em\", \"16px\")."
  @type font_size :: %{annotation_type: :font_size, value: String.t()}
  @typedoc "Extensible annotation for format-specific styling."
  @type custom :: %{annotation_type: :custom, name: String.t(), value: String.t()}

  def link(url, title), do: {:link, %{url: url, title: title}}
  def color(value), do: {:color, %{value: value}}
  def font_size(value), do: {:font_size, %{value: value}}
  def custom(name, value), do: {:custom, %{name: name, value: value}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:bold), do: "bold"
  def wire_value(:italic), do: "italic"
  def wire_value(:underline), do: "underline"
  def wire_value(:strikethrough), do: "strikethrough"
  def wire_value(:code), do: "code"
  def wire_value(:subscript), do: "subscript"
  def wire_value(:superscript), do: "superscript"
  def wire_value(:link), do: "link"
  def wire_value(:highlight), do: "highlight"
  def wire_value(:color), do: "color"
  def wire_value(:font_size), do: "font_size"
  def wire_value(:custom), do: "custom"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
