# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0196627ee1a782a20e4e7038c0cf2837d3fc07b08d5fdc4ba699616952b1b4e2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  @typedoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."
  @type t :: %__MODULE__{
          x1: float(),
          y1: float(),
          x2: float(),
          y2: float()
        }

  defstruct x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 0.0
end
