# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:15e529f98314293d9822fc9aa70637a8f04bc246cfbbb5d8ed1a8f4e7107e69b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BlockType do
  @moduledoc "Types of block-level elements in Djot."

  @typedoc "Types of block-level elements in Djot."
  @type t ::
          :paragraph
          | :heading
          | :blockquote
          | :code_block
          | :list_item
          | :ordered_list
          | :bullet_list
          | :task_list
          | :definition_list
          | :definition_term
          | :definition_description
          | :div
          | :section
          | :thematic_break
          | :raw_block
          | :math_display

  @paragraph :paragraph
  @heading :heading
  @blockquote :blockquote
  @code_block :code_block
  @list_item :list_item
  @ordered_list :ordered_list
  @bullet_list :bullet_list
  @task_list :task_list
  @definition_list :definition_list
  @definition_term :definition_term
  @definition_description :definition_description
  @div :div
  @section :section
  @thematic_break :thematic_break
  @raw_block :raw_block
  @math_display :math_display

  @doc "Standard prose paragraph."
  @spec paragraph() :: t()
  def paragraph, do: @paragraph
  @doc "Section heading (level stored in `FormattedBlock::level`)."
  @spec heading() :: t()
  def heading, do: @heading
  @doc "Block quotation container."
  @spec blockquote() :: t()
  def blockquote, do: @blockquote
  @doc "Fenced or indented code block."
  @spec code_block() :: t()
  def code_block, do: @code_block
  @doc "Individual item within a list."
  @spec list_item() :: t()
  def list_item, do: @list_item
  @doc "Numbered (ordered) list container."
  @spec ordered_list() :: t()
  def ordered_list, do: @ordered_list
  @doc "Unnumbered (bullet) list container."
  @spec bullet_list() :: t()
  def bullet_list, do: @bullet_list
  @doc "Task / checkbox list container."
  @spec task_list() :: t()
  def task_list, do: @task_list
  @doc "Definition list container."
  @spec definition_list() :: t()
  def definition_list, do: @definition_list
  @doc "Term part of a definition list entry."
  @spec definition_term() :: t()
  def definition_term, do: @definition_term
  @doc "Description / definition part of a definition list entry."
  @spec definition_description() :: t()
  def definition_description, do: @definition_description
  @doc "Generic `div` container with optional attributes."
  @spec div() :: t()
  def div, do: @div
  @doc "Logical section container, often associated with a heading."
  @spec section() :: t()
  def section, do: @section
  @doc "Horizontal rule / thematic break."
  @spec thematic_break() :: t()
  def thematic_break, do: @thematic_break
  @doc "Raw content block in a specified format (e.g. HTML, LaTeX)."
  @spec raw_block() :: t()
  def raw_block, do: @raw_block
  @doc "Display-mode mathematical expression."
  @spec math_display() :: t()
  def math_display, do: @math_display

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:paragraph), do: "paragraph"
  def wire_value(:heading), do: "heading"
  def wire_value(:blockquote), do: "blockquote"
  def wire_value(:code_block), do: "code_block"
  def wire_value(:list_item), do: "list_item"
  def wire_value(:ordered_list), do: "ordered_list"
  def wire_value(:bullet_list), do: "bullet_list"
  def wire_value(:task_list), do: "task_list"
  def wire_value(:definition_list), do: "definition_list"
  def wire_value(:definition_term), do: "definition_term"
  def wire_value(:definition_description), do: "definition_description"
  def wire_value(:div), do: "div"
  def wire_value(:section), do: "section"
  def wire_value(:thematic_break), do: "thematic_break"
  def wire_value(:raw_block), do: "raw_block"
  def wire_value(:math_display), do: "math_display"
end
