# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b3d7a421ea8a302d73fd4370923da1cf26b1ddd7e780f53caacea71fdd617e47
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BoundingBox do
  @moduledoc "Bounding box coordinates for element positioning."

  @typedoc "Bounding box coordinates for element positioning."
  @type t :: %__MODULE__{
          x0: float(),
          y0: float(),
          x1: float(),
          y1: float()
        }

  defstruct x0: 0.0,
            y0: 0.0,
            x1: 0.0,
            y1: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
