# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b7a8b5b5310e0060391f8ea9e8ecafd67416e82c82f70784ec8cc4270adc8271
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BoundaryReason do
  @moduledoc "Reason for boundary detection."

  @typedoc "Reason for boundary detection."
  @type t :: :start | :page_one_marker | :letterhead_reset | :density_shift | :end_val

  @start :start
  @page_one_marker :page_one_marker
  @letterhead_reset :letterhead_reset
  @density_shift :density_shift
  @end_val :end

  @doc "Start of PDF."
  @spec start() :: t()
  def start, do: @start
  @doc "Page-one marker (\"Page 1\", \"1 of N\") detected."
  @spec page_one_marker() :: t()
  def page_one_marker, do: @page_one_marker
  @doc "Letterhead reset after signature block."
  @spec letterhead_reset() :: t()
  def letterhead_reset, do: @letterhead_reset
  @doc "Text density shift with low bigram overlap."
  @spec density_shift() :: t()
  def density_shift, do: @density_shift
  @doc "End of PDF."
  @spec end_val() :: t()
  def end_val, do: @end_val

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:start), do: "start"
  def wire_value(:page_one_marker), do: "page_one_marker"
  def wire_value(:letterhead_reset), do: "letterhead_reset"
  def wire_value(:density_shift), do: "density_shift"
  def wire_value(:end), do: "end"
end
