# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2c8f6c882b9b4da9f1cee853c4c794670a7ac8da9fc36e2918948e0197dc18e2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CandleDevicePreference do
  @moduledoc "Device selection shared by the typed candle backend option objects."

  @typedoc "Device selection shared by the typed candle backend option objects."
  @type t :: :auto | :cpu | :cuda | :metal

  @auto :auto
  @cpu :cpu
  @cuda :cuda
  @metal :metal

  @spec auto() :: t()
  def auto, do: @auto
  @spec cpu() :: t()
  def cpu, do: @cpu
  @spec cuda() :: t()
  def cuda, do: @cuda
  @spec metal() :: t()
  def metal, do: @metal

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:auto), do: "auto"
  def wire_value(:cpu), do: "cpu"
  def wire_value(:cuda), do: "cuda"
  def wire_value(:metal), do: "metal"
end
