# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aaac2136bb3f8a2253f9afc2199b6093eedcbf4d7fb7930d90d6d9064c46afda
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CandleTrocrVariant do
  @moduledoc "TrOCR model variant accepted by `candle-trocr` backend options."

  @typedoc "TrOCR model variant accepted by `candle-trocr` backend options."
  @type t :: :base_printed | :large_printed | :base_handwritten | :large_handwritten

  @base_printed :base_printed
  @large_printed :large_printed
  @base_handwritten :base_handwritten
  @large_handwritten :large_handwritten

  @spec base_printed() :: t()
  def base_printed, do: @base_printed
  @spec large_printed() :: t()
  def large_printed, do: @large_printed
  @spec base_handwritten() :: t()
  def base_handwritten, do: @base_handwritten
  @spec large_handwritten() :: t()
  def large_handwritten, do: @large_handwritten

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:base_printed), do: "base-printed"
  def wire_value(:large_printed), do: "large-printed"
  def wire_value(:base_handwritten), do: "base-handwritten"
  def wire_value(:large_handwritten), do: "large-handwritten"
end
