# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e5de8b9631257290bce15ec78a48f522b6266be0bb2e7c2d18f1dc8da48584cb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
          llm: Xberg.LlmConfig.t(),
          prompt: String.t() | nil,
          min_image_area: non_neg_integer()
        }

  defstruct llm: nil,
            prompt: nil,
            min_image_area: nil
end
