# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b007eea4d9746b56da0425bccd6acf4488796500024221466f324caeef3e766
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Chunk do
  @moduledoc """
  A text chunk with optional embedding and metadata.

  Chunks are created when chunking is enabled in `ExtractionConfig`. Each chunk
  contains the text content, optional embedding vector (if embedding generation
  is configured), and metadata about its position in the document.
  """

  @typedoc "A text chunk with optional embedding and metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          chunk_type: Xberg.ChunkType.t(),
          embedding: [float()] | nil,
          sparse_embedding: Xberg.SparseEmbedding.t() | nil,
          late_interaction: Xberg.MultiVectorEmbedding.t() | nil,
          metadata: Xberg.ChunkMetadata.t()
        }

  defstruct content: nil,
            chunk_type: :unknown,
            embedding: nil,
            sparse_embedding: nil,
            late_interaction: nil,
            metadata: nil
end
