# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fd9d4f292204ab70b160c127267228d588fed8b58497a536fe0a627ab16cc871
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ChunkType do
  @moduledoc """
  Semantic structural classification of a text chunk.

  Assigned by the heuristic classifier in `chunking::classifier`.
  Defaults to `Unknown` when no rule matches.
  Designed to be extended in future versions without breaking changes.
  """

  @typedoc "Semantic structural classification of a text chunk."
  @type t ::
          :heading
          | :party_list
          | :definitions
          | :operative_clause
          | :signature_block
          | :schedule
          | :table_like
          | :formula
          | :code_block
          | :function
          | :class
          | :module
          | :image
          | :org_chart
          | :diagram
          | :unknown

  @heading :heading
  @party_list :party_list
  @definitions :definitions
  @operative_clause :operative_clause
  @signature_block :signature_block
  @schedule :schedule
  @table_like :table_like
  @formula :formula
  @code_block :code_block
  @function :function
  @class :class
  @module :module
  @image :image
  @org_chart :org_chart
  @diagram :diagram
  @unknown :unknown

  @doc "Section heading or document title."
  @spec heading() :: t()
  def heading, do: @heading
  @doc "Party list: names, addresses, and signatories."
  @spec party_list() :: t()
  def party_list, do: @party_list
  @doc "Definition clause (\"X means…\", \"X shall mean…\")."
  @spec definitions() :: t()
  def definitions, do: @definitions
  @doc "Operative clause containing legal/contractual action verbs."
  @spec operative_clause() :: t()
  def operative_clause, do: @operative_clause
  @doc "Signature block with signatures, names, and dates."
  @spec signature_block() :: t()
  def signature_block, do: @signature_block
  @doc "Schedule, annex, appendix, or exhibit section."
  @spec schedule() :: t()
  def schedule, do: @schedule
  @doc "Table-like content with aligned columns or repeated patterns."
  @spec table_like() :: t()
  def table_like, do: @table_like
  @doc "Mathematical formula or equation."
  @spec formula() :: t()
  def formula, do: @formula
  @doc "Code block or preformatted content."
  @spec code_block() :: t()
  def code_block, do: @code_block
  @doc "Function or method definition (tree-sitter structured code chunking)."
  @spec function() :: t()
  def function, do: @function
  @doc "Class, struct, interface, or trait definition (tree-sitter structured code chunking)."
  @spec class() :: t()
  def class, do: @class
  @doc "Module, namespace, or top-level file scope (tree-sitter structured code chunking)."
  @spec module() :: t()
  def module, do: @module
  @doc "Embedded or referenced image content."
  @spec image() :: t()
  def image, do: @image
  @doc "Organizational chart or hierarchy diagram."
  @spec org_chart() :: t()
  def org_chart, do: @org_chart
  @doc "Diagram, figure, or visual illustration."
  @spec diagram() :: t()
  def diagram, do: @diagram
  @doc "Unclassified or mixed content."
  @spec unknown() :: t()
  def unknown, do: @unknown

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:heading), do: "heading"
  def wire_value(:party_list), do: "party_list"
  def wire_value(:definitions), do: "definitions"
  def wire_value(:operative_clause), do: "operative_clause"
  def wire_value(:signature_block), do: "signature_block"
  def wire_value(:schedule), do: "schedule"
  def wire_value(:table_like), do: "table_like"
  def wire_value(:formula), do: "formula"
  def wire_value(:code_block), do: "code_block"
  def wire_value(:function), do: "function"
  def wire_value(:class), do: "class"
  def wire_value(:module), do: "module"
  def wire_value(:image), do: "image"
  def wire_value(:org_chart), do: "org_chart"
  def wire_value(:diagram), do: "diagram"
  def wire_value(:unknown), do: "unknown"
end
