# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          pages: Xberg.PageRange.t(),
          estimated_time_ms: non_neg_integer()
        }

  defstruct index: 0,
            pages: nil,
            estimated_time_ms: 0
end
