# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:00bb9ee6d01118bca31f1538a9838035690b0b8b0aa26bbc83a97af3deca98f9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          pages: Xberg.PageRange.t(),
          estimated_time_ms: non_neg_integer()
        }

  defstruct index: 0,
            pages: nil,
            estimated_time_ms: 0
end
