# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f220636c3545f81d277d4732a73575e8eaec5d39b722ef7f24e7fe28e1c66c6f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ChunkerType do
  @moduledoc """
  Type of text chunker to use.

  # Variants

  * `Text` - Generic text splitter, splits on whitespace and punctuation
  * `Markdown` - Markdown-aware splitter, preserves formatting and structure
  * `Yaml` - YAML-aware splitter, creates one chunk per top-level key
  * `Semantic` - Topic-aware chunker. With an `EmbeddingConfig`, splits at
    embedding-based topic shifts tuned by `topic_threshold` (default 0.75,
    lower = more splits). Without an embedding, falls back to a
    structural-boundary heuristic (ALL-CAPS headers, numbered sections,
    blank-line paragraphs) and merges groups into chunks capped at
    `max_characters` (default 1000). `topic_threshold` has no effect in the
    fallback path. For best results, pair with an embedding model.
  """

  @typedoc "Type of text chunker to use."
  @type t :: :text | :markdown | :yaml | :semantic

  @text :text
  @markdown :markdown
  @yaml :yaml
  @semantic :semantic

  @doc "Generic whitespace- and punctuation-aware text splitter (default)."
  @spec text() :: t()
  def text, do: @text
  @doc "Markdown-aware splitter that preserves heading and code-block boundaries."
  @spec markdown() :: t()
  def markdown, do: @markdown
  @doc "YAML-aware splitter that creates one chunk per top-level key."
  @spec yaml() :: t()
  def yaml, do: @yaml
  @doc "Topic-aware chunker that splits at embedding-based topic shifts."
  @spec semantic() :: t()
  def semantic, do: @semantic

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:text), do: "text"
  def wire_value(:markdown), do: "markdown"
  def wire_value(:yaml), do: "yaml"
  def wire_value(:semantic), do: "semantic"
end
