# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:640753da0a53b1a47fa13dd5b2e3c9bd80170b680ee58e6cc80ad439927a7587
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ChunkSizing do
  @moduledoc """
  How chunk size is measured.

  Defaults to `Characters` (Unicode character count). When using token-based sizing,
  chunks are sized by token count according to the specified tokenizer.

  Token-based sizing uses HuggingFace tokenizers loaded at runtime, or a tokenizer
  backend you register yourself. Any tokenizer available on HuggingFace Hub can be
  used, including OpenAI-compatible tokenizers (e.g., `Xenova/gpt-4o`,
  `Xenova/cl100k_base`). To size chunks with your own tokenizer instead (llama.cpp/GGUF
  vocabularies, SentencePiece models, custom vocabs), register a `TokenizerBackend`
  with `register_tokenizer_backend` and set `model` to the registered name.
  """

  @typedoc "How chunk size is measured."
  @type t :: term()

  @typedoc "Size measured in Unicode characters (default)."
  @type characters :: :characters
  @typedoc "Size measured in tokens from a HuggingFace tokenizer or a registered tokenizer backend."
  @type tokenizer :: %{type: :tokenizer, model: String.t(), cache_dir: String.t()}

  def tokenizer(model, cache_dir), do: {:tokenizer, %{model: model, cache_dir: cache_dir}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:characters), do: "characters"
  def wire_value(:tokenizer), do: "tokenizer"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
