# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b811601b7a067d0893dfe55b42fb53b0ade439b364f7cd87238a5427bd16cc91
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ChunkClassificationEnrichmentConfig do
  @moduledoc """
  Chunk-classification enrichment knob: how to multi-label individual chunks.

  Operates on `ExtractedDocument::chunks` in place — the caller must have
  already produced chunks (e.g. via `ExtractionConfig::chunking`) for this
  stage to have any effect; a document with no chunks is a no-op.
  """

  @typedoc "Chunk-classification enrichment knob: how to multi-label individual chunks."
  @type t :: %__MODULE__{
          config: Xberg.ChunkClassificationConfig.t()
        }

  defstruct config: nil
end
