# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d9ca9398446e6241c73340dd6b6ef9a1580fb59d657cbb286e96d5bf2e153c38
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          confidence: float() | nil
        }

  defstruct label: nil,
            confidence: nil
end
