# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76706a24058bc73aebc16e89ccaa62fd1efeb787445d5e5aa82c05ede27a6bd0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CodeMetadata do
  @moduledoc """
  Code-format metadata: the structural chunks produced by tree-sitter parsing.

  Wrapped by [`FormatMetadata::Code`]. Kept as a named struct (rather than an inline
  enum-variant body) so serde can tag it under internal tagging and utoipa can emit a
  referenceable `CodeMetadata` component in the OpenAPI schema.
  """

  @typedoc "Code-format metadata: the structural chunks produced by tree-sitter parsing."
  @type t :: %__MODULE__{
          chunks: [Xberg.CodeChunkInfo.t()],
          data: Xberg.CodeDataNode.t() | nil
        }

  defstruct chunks: [],
            data: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
