# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d895cbf742713a9985be67bf30a918c1c2ef9dff358d08a9802fb4f5508fb3e4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CodeContentMode do
  @moduledoc """
  Content rendering mode for code extraction.

  Controls how extracted code content is represented in the `content` field
  of `ExtractedDocument`.
  """

  @typedoc "Content rendering mode for code extraction."
  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @doc "Use TSLP semantic chunks as content (default)."
  @spec chunks() :: t()
  def chunks, do: @chunks
  @doc "Use raw source code as content."
  @spec raw() :: t()
  def raw, do: @raw
  @doc "Emit function/class headings + docstrings (no code bodies)."
  @spec structure() :: t()
  def structure, do: @structure

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:chunks), do: "chunks"
  def wire_value(:raw), do: "raw"
  def wire_value(:structure), do: "structure"
end
