# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b013cb1dcf73ebd35c21b35561e9082f8d28060556fc4167607cc9895f18ea02
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ConfidenceSemantics do
  @moduledoc """
  How a backend's reported page-level confidence must be interpreted.

  Backend confidence scores are not interchangeable. Tesseract's mean word confidence is a
  classifier score validated to track legibility on a 0-100 scale. Sceptre (EasyOCR-based)
  reports a length-penalised `custom_mean` that is rescaled into the same 0-100 range but is
  *not* comparable — its ordering can be inverted relative to legibility (a dense prose page
  can score lower than a nearly-blank one). A page-rejection gate calibrated on Tesseract's
  scale was once applied unconditionally to sceptre's output and rejected every page of a
  16-page document, emptying it. This descriptor exists so gating code can ask a backend what
  its number means instead of assuming.
  """

  @typedoc "How a backend's reported page-level confidence must be interpreted."
  @type t :: term()

  @typedoc "Validated to track legibility on a known scale — usable as an absolute quality gate."
  @type legibility :: %{type: :legibility, scale_max: float()}
  @typedoc "A number is reported, but it is not validated to correlate with legibility. Never gate on it."
  @type uncalibrated :: :uncalibrated
  @typedoc "No page-level confidence is reported at all."
  @type none_variant :: :none

  def legibility(scale_max), do: {:legibility, %{scale_max: scale_max}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:legibility), do: "Legibility"
  def wire_value(:uncalibrated), do: "Uncalibrated"
  def wire_value(:none), do: "None"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
