# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc4e1e60e80ebbded6bcf9ce21fe009e1d966f4571a53b3e535fd06b248943cf
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ContentLayer do
  @moduledoc """
  Content layer classification for document nodes.

  Replaces separate body/furniture arrays with per-node granularity.
  """

  @typedoc "Content layer classification for document nodes."
  @type t :: :body | :header | :footer | :footnote

  @body :body
  @header :header
  @footer :footer
  @footnote :footnote

  @doc "Main document body content."
  @spec body() :: t()
  def body, do: @body
  @doc "Page/section header (running header)."
  @spec header() :: t()
  def header, do: @header
  @doc "Page/section footer (running footer)."
  @spec footer() :: t()
  def footer, do: @footer
  @doc "Footnote content."
  @spec footnote() :: t()
  def footnote, do: @footnote

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:body), do: "body"
  def wire_value(:header), do: "header"
  def wire_value(:footer), do: "footer"
  def wire_value(:footnote), do: "footnote"
end
