# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c36bb281120937f2f16863d9dbc52f097918eb3004b10d6722934de8f7476a88
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ContentFilterKind do
  @moduledoc "Content filter applied to each crawled page before it reaches the result."

  @typedoc "Content filter applied to each crawled page before it reaches the result."
  @type t :: :bm25

  @bm25 :bm25

  @doc "Keep only pages scoring at or above `bm25_threshold` for `bm25_query`."
  @spec bm25() :: t()
  def bm25, do: @bm25

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:bm25), do: "bm25"
end
