# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65cd7ec8a936b9cd9d6c6855f1374b5ced6346c19f2d4dd6729aebd4ea986139
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  @typedoc "dBASE (DBF) file metadata."
  @type t :: %__MODULE__{
          record_count: non_neg_integer(),
          field_count: non_neg_integer(),
          fields: [Xberg.DbfFieldInfo.t()]
        }

  defstruct record_count: 0,
            field_count: 0,
            fields: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
