# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DoctorReport do
  @moduledoc "Aggregate doctor report over all configured backends and settings."

  @typedoc "Aggregate doctor report over all configured backends and settings."
  @type t :: %__MODULE__{
          checks: [Xberg.DoctorCheck.t()]
        }

  defstruct checks: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
