# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b73b6729b8e26392460f4f92bc3de64bce2ef5a95bfa8cf11babf7ef17581fc7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          strategy: Xberg.SummaryStrategy.t(),
          token_count: non_neg_integer() | nil
        }

  defstruct text: nil,
            strategy: :extractive,
            token_count: nil
end
