# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:64f0023d448a5cce6648b7e5acd1ca189556e4927812ce80084811ab9c551c5e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DocumentBoundary do
  @moduledoc "Detected document boundary within a PDF."

  @typedoc "Detected document boundary within a PDF."
  @type t :: %__MODULE__{
          start_page: non_neg_integer(),
          end_page: non_neg_integer(),
          confidence: float(),
          reason: Xberg.BoundaryReason.t()
        }

  defstruct start_page: 0,
            end_page: 0,
            confidence: 0.0,
            reason: :start
end
