# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e6f4700e302e4627ace6f44496d69d2b4fce88f993a39252573c1fe127790e57
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
          element_id: String.t() | nil,
          element_type: Xberg.ElementType.t(),
          text: String.t() | nil,
          metadata: Xberg.ElementMetadata.t()
        }

  defstruct element_id: nil,
            element_type: :title,
            text: nil,
            metadata: nil
end
