# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:baa557f293fdb0fdaaad57b91d1186c770ba21ca63ef92d766dd1e9f61c5b4fe
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          compressed_size: non_neg_integer(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            compressed_size: 0,
            mime_type: nil
end
