# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:037c89c934a889f4a35192f5b112dca6a42ffa4e06ef3c240773931d17a0c868
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddingModelType do
  @moduledoc "Embedding model types supported by Xberg."

  @typedoc "Embedding model types supported by Xberg."
  @type t :: term()

  @typedoc "Use a preset model configuration (recommended)"
  @type preset :: %{type: :preset, name: String.t()}
  @typedoc "Use a custom ONNX model from HuggingFace"
  @type custom :: %{type: :custom, model_id: String.t(), dimensions: non_neg_integer()}
  @typedoc "Provider-hosted embedding model via liter-llm."
  @type llm :: %{type: :llm, llm: Xberg.LlmConfig.t()}
  @typedoc "In-process embedding backend registered via the plugin system."
  @type plugin :: %{type: :plugin, name: String.t()}

  def preset(name), do: {:preset, %{name: name}}
  def custom(model_id, dimensions), do: {:custom, %{model_id: model_id, dimensions: dimensions}}
  def llm(llm), do: {:llm, %{llm: llm}}
  def plugin(name), do: {:plugin, %{name: name}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:preset), do: "preset"
  def wire_value(:custom), do: "custom"
  def wire_value(:llm), do: "llm"
  def wire_value(:plugin), do: "plugin"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
