# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:048283727d8f57a9bcd21c3ee0f28fa98514dc6b49910ef9aad718e1d36fdc70
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddedChanges do
  @moduledoc "Changes to embedded archive children between two results."

  @typedoc "Changes to embedded archive children between two results."
  @type t :: %__MODULE__{
          added: [Xberg.ArchiveEntry.t()],
          removed: [Xberg.ArchiveEntry.t()],
          changed: [Xberg.EmbeddedDiff.t()]
        }

  defstruct added: [],
            removed: [],
            changed: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
