# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1e286b56b4f0db54bd67c68d859e28802c9125b515e668b9b62749db2b63517a
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddingsEmbeddingBackend do
  @moduledoc """
  Inference backend that an [`EmbeddingPreset`] runs on.

  `Onnx` presets require the `embeddings` feature (ONNX Runtime, not available on
  WASM/Android x86_64 emulator). `Static` presets require `static-embeddings`
  (pure-Rust model2vec inference, no ORT — the only dense-embedding backend
  available on `no-ort-target`).

  Defaults to `Onnx` via `#[serde(default)]` so every existing preset payload
  (which predates this field) keeps deserializing without change.
  """

  @typedoc "Inference backend that an [`EmbeddingPreset`] runs on."
  @type t :: :onnx | :static

  @onnx :onnx
  @static :static

  @doc "ONNX Runtime transformer inference (the historical, default backend)."
  @spec onnx() :: t()
  def onnx, do: @onnx
  @doc "Pure-Rust static (model2vec) inference — no ONNX Runtime."
  @spec static() :: t()
  def static, do: @static

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:onnx), do: "onnx"
  def wire_value(:static), do: "static"
end
