# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92c5f174e05d6c2982548c1c7b13e4eeb0c276be8dfd76dc477fb5117bc9a6e5
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddedDiff do
  @moduledoc "Diff for a single embedded archive entry that appears in both results."

  @typedoc "Diff for a single embedded archive entry that appears in both results."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          diff: Xberg.ExtractionDiff.t()
        }

  defstruct path: nil,
            diff: nil
end
