# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2841e3883f0d9b0a43d557a152e8edeb557bf38fa5d5e5b3dc9f91ba53d2b5ea
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.EmbeddingConfig do
  @moduledoc """
  Embedding configuration for text chunks.

  Configures embedding generation using ONNX models via the vendored embedding engine.
  Requires the `embeddings` feature to be enabled.
  """

  @typedoc "Embedding configuration for text chunks."
  @type t :: %__MODULE__{
          model: Xberg.EmbeddingModelType.t(),
          normalize: boolean(),
          batch_size: non_neg_integer(),
          show_download_progress: boolean(),
          cache_dir: String.t() | nil,
          acceleration: Xberg.AccelerationConfig.t() | nil,
          max_embed_duration_secs: non_neg_integer() | nil,
          max_sequence_length: non_neg_integer() | nil
        }

  defstruct model: nil,
            normalize: true,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: nil,
            max_sequence_length: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
