# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:42fc6c661035ee9626a91da4708313e74bd0127e77dd6b853089177fc1ee7158
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExcelMetadata do
  @moduledoc """
  Excel/spreadsheet format metadata.

  Identifies the document as a spreadsheet source via the `FormatMetadata::Excel`
  discriminant. Sheet count and sheet names are stored inside this struct.
  """

  @typedoc "Excel/spreadsheet format metadata."
  @type t :: %__MODULE__{
          sheet_count: non_neg_integer() | nil,
          sheet_names: [String.t()] | nil
        }

  defstruct sheet_count: nil,
            sheet_names: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
