# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0304bbc7164f686b36916514d24d59a37ff501e6bf807f427ca852fc4d9781e6
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExecutionProviderType do
  @moduledoc """
  ONNX Runtime execution provider type.

  Determines which hardware backend is used for model inference.
  `Auto` (default) selects the best available provider per platform.
  """

  @typedoc "ONNX Runtime execution provider type."
  @type t :: :auto | :cpu | :core_ml | :cuda | :tensor_rt

  @auto :auto
  @cpu :cpu
  @core_ml :core_ml
  @cuda :cuda
  @tensor_rt :tensor_rt

  @doc "Auto-select: CoreML on macOS, CUDA on Linux, CPU elsewhere."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "CPU execution provider (always available)."
  @spec cpu() :: t()
  def cpu, do: @cpu
  @doc "Apple CoreML (macOS/iOS Neural Engine + GPU)."
  @spec core_ml() :: t()
  def core_ml, do: @core_ml
  @doc "NVIDIA CUDA GPU acceleration."
  @spec cuda() :: t()
  def cuda, do: @cuda
  @doc "NVIDIA TensorRT (optimized CUDA inference)."
  @spec tensor_rt() :: t()
  def tensor_rt, do: @tensor_rt

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:auto), do: "auto"
  def wire_value(:cpu), do: "cpu"
  def wire_value(:core_ml), do: "coreml"
  def wire_value(:cuda), do: "cuda"
  def wire_value(:tensor_rt), do: "tensorrt"
end
