# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionErrorItem do
  @moduledoc "Non-fatal per-input extraction error captured by [`ExtractionResult`]."

  @typedoc "Non-fatal per-input extraction error captured by [`ExtractionResult`]."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          code: non_neg_integer(),
          error_type: String.t() | nil,
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct index: 0,
            code: 0,
            error_type: nil,
            source: nil,
            message: nil
end
