# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f7c8d8e64c0b5f08d3776d73fcff382a03bd6f4512fa73f7de6a19483dccc59
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: Xberg.UriKind.t()
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
