# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9baabec46516eb173df8c8b46268ceeb58178abbcd1359a39a18eda42781792
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FootnoteDefinition do
  @moduledoc """
  A footnote definition from markdown text.

  Represents `[^label]: content` declarations (including multi-line continuations).
  """

  @typedoc "A footnote definition from markdown text."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: String.t() | nil,
          offset: non_neg_integer()
        }

  defstruct label: nil,
            content: nil,
            offset: 0
end
