# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33b929cfb5138957227cd30fc759203a4bd5b4268ed37fbe0f6d6ec5d9e4c947
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [Xberg.FormattedBlock.t()]
        }

  defstruct label: nil,
            content: []
end
