# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:224b2975a83fc3ea3853afa8f67a85ec83f5fbc7fcd2213b158288770f478686
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FootnoteConfig do
  @moduledoc "Configuration for markdown footnote and citation parsing."

  @typedoc "Configuration for markdown footnote and citation parsing."
  @type t :: %__MODULE__{
          parse_citations: boolean()
        }

  defstruct parse_citations: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
