# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteDefinition do
  @moduledoc """
  A footnote definition from markdown text.

  Represents `[^label]: content` declarations (including multi-line continuations).
  """

  @typedoc "A footnote definition from markdown text."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: String.t() | nil,
          offset: non_neg_integer()
        }

  defstruct label: nil,
            content: nil,
            offset: 0
end
