# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:163ae8ebba95572ba5a9a3d64db553425836451d70d14f7c39e76a10e0f425c0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FormulaModel do
  @moduledoc "Formula recognition model selection."

  @typedoc "Formula recognition model selection."
  @type t :: :latex_ocr

  @latex_ocr :latex_ocr

  @doc "RapidLaTeXOCR (MIT, pix2tex-derived): resizer + encoder + decoder ONNX, ~180 MB total, downloaded on demand."
  @spec latex_ocr() :: t()
  def latex_ocr, do: @latex_ocr

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:latex_ocr), do: "latex_ocr"
end
