# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9e69cd98b93dcedd771335c30f61cfa45dedce8d3686e0c36c4dff34f52e400
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FormFieldType do
  @moduledoc """
  Kind of a PDF form field.

  Mirrors `xberg_native_pdf`'s widget field taxonomy without leaking the upstream
  type across the binding surface.
  """

  @typedoc "Kind of a PDF form field."
  @type t :: :text | :checkbox | :radio | :choice | :signature | :button | :unknown

  @text :text
  @checkbox :checkbox
  @radio :radio
  @choice :choice
  @signature :signature
  @button :button
  @unknown :unknown

  @doc "Single- or multi-line text input."
  @spec text() :: t()
  def text, do: @text
  @doc "Checkbox (on/off toggle)."
  @spec checkbox() :: t()
  def checkbox, do: @checkbox
  @doc "Radio-button group member."
  @spec radio() :: t()
  def radio, do: @radio
  @doc "Choice field (dropdown or list box)."
  @spec choice() :: t()
  def choice, do: @choice
  @doc "Digital-signature field."
  @spec signature() :: t()
  def signature, do: @signature
  @doc "Push button."
  @spec button() :: t()
  def button, do: @button
  @doc "Field type that could not be classified."
  @spec unknown() :: t()
  def unknown, do: @unknown

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:text), do: "text"
  def wire_value(:checkbox), do: "checkbox"
  def wire_value(:radio), do: "radio"
  def wire_value(:choice), do: "choice"
  def wire_value(:signature), do: "signature"
  def wire_value(:button), do: "button"
  def wire_value(:unknown), do: "unknown"
end
