# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aa83455a9909feac1e2d5413378a4c8a694e94cde4d1b4c19aa39fa7fe3e4723
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.GlmOcrBackendOptions do
  @moduledoc "Runtime options accepted by the `candle-glm-ocr` backend."

  @typedoc "Runtime options accepted by the `candle-glm-ocr` backend."
  @type t :: %__MODULE__{
          task: Xberg.GlmOcrTaskKind.t() | nil,
          device: Xberg.CandleDevicePreference.t() | nil,
          layout_mode: Xberg.GlmOcrLayoutMode.t() | nil,
          enable_chart_understanding: boolean() | nil,
          cache_dir: String.t() | nil
        }

  defstruct task: nil,
            device: nil,
            layout_mode: nil,
            enable_chart_understanding: nil,
            cache_dir: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
