# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6f418c37bcd2f70087cd5ad692f57163751b7a4b1ce54ddd1637c554cac81739
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  @typedoc "A single heading in the hierarchy."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil
        }

  defstruct level: 0,
            text: nil
end
