# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:46dd3a354d1280d18040b69a7d593c9e4baa84bd68c8f9911072baad22ca2120
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
          headings: [Xberg.HeadingLevel.t()]
        }

  defstruct headings: []
end
