# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a03246c754ac66b5a8e476015819cbef0249bee8190df0f08f3dad0444bd3fe4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HierarchicalBoundingBox do
  @moduledoc """
  A text block with hierarchy level assignment.

  Represents a block of text with semantic heading information extracted from
  font size clustering and hierarchical analysis.
  """

  @typedoc "A text block with hierarchy level assignment."
  @type t :: %__MODULE__{
          left: float(),
          top: float(),
          right: float(),
          bottom: float()
        }

  defstruct left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
