# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:79813b8f999dc478340201ddbd5575dd4700b1cb8634ba3d1961e631e88d7f5e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.HierarchicalBlock do
  @moduledoc false

  @type t :: %__MODULE__{
          text: String.t() | nil,
          font_size: float(),
          level: String.t() | nil,
          bbox: Xberg.HierarchicalBoundingBox.t() | nil
        }

  defstruct text: nil,
            font_size: 0.0,
            level: nil,
            bbox: nil
end
