# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3da481baa88bf39df088013922566fc6c8d68c197c409e7907e0b774965b8a4d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          dimensions: Xberg.ImageDimensions.t() | nil,
          image_type: Xberg.ImageType.t(),
          attributes: [Xberg.KeyValueAttribute.t()]
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
