# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f830ae9d9d226c07bc4d457235534a2daf825f69fd0c89c5687cd79b9c113fe8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageKind do
  @moduledoc "Heuristic classification of what an image likely depicts."

  @typedoc "Heuristic classification of what an image likely depicts."
  @type t ::
          :photograph
          | :diagram
          | :chart
          | :drawing
          | :text_block
          | :decoration
          | :logo
          | :icon
          | :tile_fragment
          | :mask
          | :page_raster
          | :unknown

  @photograph :photograph
  @diagram :diagram
  @chart :chart
  @drawing :drawing
  @text_block :text_block
  @decoration :decoration
  @logo :logo
  @icon :icon
  @tile_fragment :tile_fragment
  @mask :mask
  @page_raster :page_raster
  @unknown :unknown

  @doc "Photographic image (natural scene, photograph)"
  @spec photograph() :: t()
  def photograph, do: @photograph
  @doc "Technical or schematic diagram"
  @spec diagram() :: t()
  def diagram, do: @diagram
  @doc "Chart, graph, or plot"
  @spec chart() :: t()
  def chart, do: @chart
  @doc "Freehand or technical drawing"
  @spec drawing() :: t()
  def drawing, do: @drawing
  @doc "Text-heavy image (scanned text, document)"
  @spec text_block() :: t()
  def text_block, do: @text_block
  @doc "Decorative element or border"
  @spec decoration() :: t()
  def decoration, do: @decoration
  @doc "Logo or brand mark"
  @spec logo() :: t()
  def logo, do: @logo
  @doc "Small icon"
  @spec icon() :: t()
  def icon, do: @icon
  @doc "Fragment of a larger tiled image (tile of a technical drawing)"
  @spec tile_fragment() :: t()
  def tile_fragment, do: @tile_fragment
  @doc "Mask or transparency map"
  @spec mask() :: t()
  def mask, do: @mask
  @doc "Full-page render produced during OCR preprocessing; used as a citation thumbnail."
  @spec page_raster() :: t()
  def page_raster, do: @page_raster
  @doc "Could not classify with reasonable confidence"
  @spec unknown() :: t()
  def unknown, do: @unknown

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:photograph), do: "photograph"
  def wire_value(:diagram), do: "diagram"
  def wire_value(:chart), do: "chart"
  def wire_value(:drawing), do: "drawing"
  def wire_value(:text_block), do: "text_block"
  def wire_value(:decoration), do: "decoration"
  def wire_value(:logo), do: "logo"
  def wire_value(:icon), do: "icon"
  def wire_value(:tile_fragment), do: "tile_fragment"
  def wire_value(:mask), do: "mask"
  def wire_value(:page_raster), do: "page_raster"
  def wire_value(:unknown), do: "unknown"
end
