# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d8674c3c9f43fdef554c474a608abf69c1e889f1d77db06558726496323865f0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageMetadata do
  @moduledoc """
  Image metadata extracted from image files.

  Includes dimensions, format, and EXIF data.
  """

  @typedoc "Image metadata extracted from image files."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif: %{}

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
