# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a405f1ababcc234d4117497e8b26bbaef0d1da9fdc0adb590c9f2ec6c806dabf
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageOutputFormat do
  @moduledoc """
  Target format for re-encoding extracted images.

  Controls whether and how extracted images are normalised to a uniform
  container format before being returned in `ExtractedDocument.images`.
  The default (`Native`) preserves the format produced by each extractor
  without any additional encode pass.

  Callers that need uniform output — e.g. cloud pipelines that always store
  WebP thumbnails — set this once on `ImageExtractionConfig.output_format`
  rather than re-encoding downstream.

  # Serde shape

  Uses a tagged enum: `{"type": "native"}`, `{"type": "png"}`,
  `{"type": "jpeg", "quality": 90}`, etc.
  """

  @typedoc "Target format for re-encoding extracted images."
  @type t :: term()

  @typedoc "Preserve whatever format the extractor produced (default)."
  @type native :: :native
  @typedoc "Re-encode all extracted images as PNG (lossless)."
  @type png :: :png
  @typedoc "Re-encode all extracted images as JPEG at the given quality level."
  @type jpeg :: %{type: :jpeg, quality: non_neg_integer()}
  @typedoc "Re-encode all extracted images as WebP at the given quality level."
  @type webp :: %{type: :webp, quality: non_neg_integer()}
  @typedoc "Re-encode all extracted images as HEIF/HEIC at the given quality level."
  @type heif :: %{type: :heif, quality: non_neg_integer()}
  @typedoc "Output pure-vector SVG. Lossless. Raster sources are not re-encoded (a warning is emitted and the image bytes are left untouched)."
  @type svg :: :svg

  def jpeg(quality), do: {:jpeg, %{quality: quality}}
  def webp(quality), do: {:webp, %{quality: quality}}
  def heif(quality), do: {:heif, %{quality: quality}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:native), do: "native"
  def wire_value(:png), do: "png"
  def wire_value(:jpeg), do: "jpeg"
  def wire_value(:webp), do: "webp"
  def wire_value(:heif), do: "heif"
  def wire_value(:svg), do: "svg"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
