# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:42736b95991d27a8df8c9c4e3b98b2f6c3e9b101155558a38e0a3e3cb6b3dadf
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ImageType do
  @moduledoc "Image type classification."

  @typedoc "Image type classification."
  @type t :: :"data-uri" | :"inline-svg" | :external | :relative

  @data_uri :"data-uri"
  @inline_svg :"inline-svg"
  @external :external
  @relative :relative

  @doc "Data URI image"
  @spec data_uri() :: t()
  def data_uri, do: @data_uri
  @doc "Inline SVG"
  @spec inline_svg() :: t()
  def inline_svg, do: @inline_svg
  @doc "External image URL"
  @spec external() :: t()
  def external, do: @external
  @doc "Relative path image"
  @spec relative() :: t()
  def relative, do: @relative

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:data_uri), do: "data-uri"
  def wire_value(:inline_svg), do: "inline-svg"
  def wire_value(:external), do: "external"
  def wire_value(:relative), do: "relative"
end
