# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc2b8affd32aadbf850f984d90411175d6de08b59dd2812ebd613d22e7ef6d27
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: Xberg.InlineType.t(),
          content: String.t() | nil,
          attributes: Xberg.Attributes.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            attributes: nil,
            metadata: nil
end
