# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:21d0a6fd3de63216478f8ff257be887f9b6511136a7d35bc46f30f5aaab6cca7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.InlineType do
  @moduledoc "Types of inline elements in Djot."

  @typedoc "Types of inline elements in Djot."
  @type t ::
          :text
          | :strong
          | :emphasis
          | :highlight
          | :subscript
          | :superscript
          | :insert
          | :delete
          | :code
          | :link
          | :image
          | :span
          | :math
          | :raw_inline
          | :footnote_ref
          | :symbol

  @text :text
  @strong :strong
  @emphasis :emphasis
  @highlight :highlight
  @subscript :subscript
  @superscript :superscript
  @insert :insert
  @delete :delete
  @code :code
  @link :link
  @image :image
  @span :span
  @math :math
  @raw_inline :raw_inline
  @footnote_ref :footnote_ref
  @symbol :symbol

  @doc "Plain text run."
  @spec text() :: t()
  def text, do: @text
  @doc "Bold / strong emphasis."
  @spec strong() :: t()
  def strong, do: @strong
  @doc "Italic / regular emphasis."
  @spec emphasis() :: t()
  def emphasis, do: @emphasis
  @doc "Highlighted text (marker pen)."
  @spec highlight() :: t()
  def highlight, do: @highlight
  @doc "Subscript text."
  @spec subscript() :: t()
  def subscript, do: @subscript
  @doc "Superscript text."
  @spec superscript() :: t()
  def superscript, do: @superscript
  @doc "Inserted text (tracked change)."
  @spec insert() :: t()
  def insert, do: @insert
  @doc "Deleted text (tracked change)."
  @spec delete() :: t()
  def delete, do: @delete
  @doc "Inline code span."
  @spec code() :: t()
  def code, do: @code
  @doc "Hyperlink with URL."
  @spec link() :: t()
  def link, do: @link
  @doc "Inline image reference."
  @spec image() :: t()
  def image, do: @image
  @doc "Generic inline span with optional attributes."
  @spec span() :: t()
  def span, do: @span
  @doc "Inline mathematical expression."
  @spec math() :: t()
  def math, do: @math
  @doc "Raw inline content in a specified format."
  @spec raw_inline() :: t()
  def raw_inline, do: @raw_inline
  @doc "Footnote reference marker."
  @spec footnote_ref() :: t()
  def footnote_ref, do: @footnote_ref
  @doc "Named symbol or emoji shortcode."
  @spec symbol() :: t()
  def symbol, do: @symbol

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:text), do: "text"
  def wire_value(:strong), do: "strong"
  def wire_value(:emphasis), do: "emphasis"
  def wire_value(:highlight), do: "highlight"
  def wire_value(:subscript), do: "subscript"
  def wire_value(:superscript), do: "superscript"
  def wire_value(:insert), do: "insert"
  def wire_value(:delete), do: "delete"
  def wire_value(:code), do: "code"
  def wire_value(:link), do: "link"
  def wire_value(:image), do: "image"
  def wire_value(:span), do: "span"
  def wire_value(:math), do: "math"
  def wire_value(:raw_inline), do: "raw_inline"
  def wire_value(:footnote_ref), do: "footnote_ref"
  def wire_value(:symbol), do: "symbol"
end
