# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2bc1b44e36941e751c73c1756b0dd08ff862425549dd243e0f4a0b365e367a8e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  @typedoc "JATS (Journal Article Tag Suite) metadata."
  @type t :: %__MODULE__{
          copyright: String.t() | nil,
          license: String.t() | nil,
          history_dates: map(),
          contributor_roles: [Xberg.ContributorRole.t()]
        }

  defstruct copyright: nil,
            license: nil,
            history_dates: %{},
            contributor_roles: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
