# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f788252d812a02033fb86fc4b9ccb3a332f7ff4e6fe4e75524b449c51a11e0eb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.JupyterCellRendering do
  @moduledoc """
  Controls how Jupyter notebook code cells are rendered during extraction.

  A code cell carries both its **source** and any **outputs** that were saved in
  the notebook. Callers ingesting notebooks for AI agents want different slices of
  this depending on the task. Xberg never executes cells — `Outputs` and `Both`
  only surface outputs already stored in the `.ipynb`.

  This toggle governs a code cell's **source body** and its **saved outputs**.
  Markdown (prose) cells and structural markers (kernel language, cell id, tags,
  execution count) are unaffected — prose always renders and markers orient the
  reader regardless of mode.
  """

  @typedoc "Controls how Jupyter notebook code cells are rendered during extraction."
  @type t :: :source | :outputs | :both

  @source :source
  @outputs :outputs
  @both :both

  @doc "Render the code source as a fenced code block; omit saved outputs."
  @spec source() :: t()
  def source, do: @source
  @doc "Omit the code source; render only the saved cell outputs."
  @spec outputs() :: t()
  def outputs, do: @outputs
  @doc "Render both the code source and the saved outputs (default; preserves the historical behavior)."
  @spec both() :: t()
  def both, do: @both

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:source), do: "source"
  def wire_value(:outputs), do: "outputs"
  def wire_value(:both), do: "both"
end
