# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7b8caa5e63a3d58768686a55f11cf8377e5cd28b184f2ffed1c6c6ca4cc323b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.KeyValueAttribute do
  @moduledoc "A string key-value attribute."

  @typedoc "A string key-value attribute."
  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  defstruct key: nil,
            value: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
