# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc1b76385f07fcf194abc20b87455625bb49c7f128a229c2c6230bc1220e85c1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @typedoc "Keyword algorithm selection."
  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @doc "YAKE (Yet Another Keyword Extractor) - statistical approach"
  @spec yake() :: t()
  def yake, do: @yake
  @doc "RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based"
  @spec rake() :: t()
  def rake, do: @rake

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:yake), do: "yake"
  def wire_value(:rake), do: "rake"
end
