# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d2af8778bcd0dd741491fdc15d56d6e27d8e325467bd8d6106193848ad17edd2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          score: float(),
          algorithm: Xberg.KeywordAlgorithm.t(),
          positions: [non_neg_integer()] | nil
        }

  defstruct text: nil,
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
