# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @typedoc "Keyword algorithm selection."
  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @doc "YAKE (Yet Another Keyword Extractor) - statistical approach"
  @spec yake() :: t()
  def yake, do: @yake
  @doc "RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based"
  @spec rake() :: t()
  def rake, do: @rake
end
