# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fcab87af54feeb9fb51a237f1344333413d694a26ae445a50a7c7ace187e6e6b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  @typedoc "Keyword extraction configuration."
  @type t :: %__MODULE__{
          algorithm: Xberg.KeywordAlgorithm.t(),
          max_keywords: non_neg_integer(),
          min_score: float(),
          ngram_range: Xberg.NgramRange.t(),
          language: String.t() | nil,
          yake_params: Xberg.YakeParams.t() | nil,
          rake_params: Xberg.RakeParams.t() | nil
        }

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: nil,
            language: nil,
            yake_params: nil,
            rake_params: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
