# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LateInteractionPreset do
  @moduledoc """
  Static metadata for a bundled ColBERT preset (WASM/Android-safe, no ORT).

  Since v5.0.0.
  """

  @typedoc "Static metadata for a bundled ColBERT preset (WASM/Android-safe, no ORT)."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          model_repo: String.t() | nil,
          model_file: String.t() | nil,
          additional_files: [String.t()],
          max_length: non_neg_integer(),
          query_max_length: non_neg_integer(),
          dim: non_neg_integer(),
          description: String.t() | nil
        }

  defstruct name: nil,
            model_repo: nil,
            model_file: nil,
            additional_files: [],
            max_length: 0,
            query_max_length: 0,
            dim: 0,
            description: nil
end
