# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a51976973d408daad6c1814703e2da369e1674f893376335708d8bda6d9c0627
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LayoutClass do
  @moduledoc """
  The 18 canonical document layout classes.

  All model backends (RT-DETR, YOLO, etc.) map their native class IDs
  to this shared set. Models with fewer classes (DocLayNet: 11, PubLayNet: 5)
  map to the closest equivalent.

  Wire format is snake_case in all serializers (JSON, TOML, YAML).
  """

  @typedoc "The 18 canonical document layout classes."
  @type t ::
          :caption
          | :chart
          | :footnote
          | :formula
          | :list_item
          | :page_footer
          | :page_header
          | :picture
          | :section_header
          | :table
          | :text
          | :title
          | :document_index
          | :code
          | :checkbox_selected
          | :checkbox_unselected
          | :form
          | :key_value_region

  @caption :caption
  @chart :chart
  @footnote :footnote
  @formula :formula
  @list_item :list_item
  @page_footer :page_footer
  @page_header :page_header
  @picture :picture
  @section_header :section_header
  @table :table
  @text :text
  @title :title
  @document_index :document_index
  @code :code
  @checkbox_selected :checkbox_selected
  @checkbox_unselected :checkbox_unselected
  @form :form
  @key_value_region :key_value_region

  @doc "Figure or table caption text."
  @spec caption() :: t()
  def caption, do: @caption
  @doc "Chart or graph visualization."
  @spec chart() :: t()
  def chart, do: @chart
  @doc "Footnote or endnote text."
  @spec footnote() :: t()
  def footnote, do: @footnote
  @doc "Mathematical formula or equation."
  @spec formula() :: t()
  def formula, do: @formula
  @doc "A single item in a bulleted or numbered list."
  @spec list_item() :: t()
  def list_item, do: @list_item
  @doc "Running footer at the bottom of a page."
  @spec page_footer() :: t()
  def page_footer, do: @page_footer
  @doc "Running header at the top of a page."
  @spec page_header() :: t()
  def page_header, do: @page_header
  @doc "Image, chart, or other graphical element."
  @spec picture() :: t()
  def picture, do: @picture
  @doc "Section heading."
  @spec section_header() :: t()
  def section_header, do: @section_header
  @doc "Data table."
  @spec table() :: t()
  def table, do: @table
  @doc "Body text paragraph."
  @spec text() :: t()
  def text, do: @text
  @doc "Document or chapter title."
  @spec title() :: t()
  def title, do: @title
  @doc "Table of contents or index."
  @spec document_index() :: t()
  def document_index, do: @document_index
  @doc "Source code block."
  @spec code() :: t()
  def code, do: @code
  @doc "Checkbox in selected state."
  @spec checkbox_selected() :: t()
  def checkbox_selected, do: @checkbox_selected
  @doc "Checkbox in unselected state."
  @spec checkbox_unselected() :: t()
  def checkbox_unselected, do: @checkbox_unselected
  @doc "Form field or form element."
  @spec form() :: t()
  def form, do: @form
  @doc "Key-value pair region (e.g. label + value in a form)."
  @spec key_value_region() :: t()
  def key_value_region, do: @key_value_region

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:caption), do: "caption"
  def wire_value(:chart), do: "chart"
  def wire_value(:footnote), do: "footnote"
  def wire_value(:formula), do: "formula"
  def wire_value(:list_item), do: "list_item"
  def wire_value(:page_footer), do: "page_footer"
  def wire_value(:page_header), do: "page_header"
  def wire_value(:picture), do: "picture"
  def wire_value(:section_header), do: "section_header"
  def wire_value(:table), do: "table"
  def wire_value(:text), do: "text"
  def wire_value(:title), do: "title"
  def wire_value(:document_index), do: "document_index"
  def wire_value(:code), do: "code"
  def wire_value(:checkbox_selected), do: "checkbox_selected"
  def wire_value(:checkbox_unselected), do: "checkbox_unselected"
  def wire_value(:form), do: "form"
  def wire_value(:key_value_region), do: "key_value_region"
end
