# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:75f372bae2b30719af3bf8837874a70e613ca630abcfcb34b1fb96a9c0609845
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LinkType do
  @moduledoc "Link type classification."

  @typedoc "Link type classification."
  @type t :: :anchor | :internal | :external | :email | :phone | :other

  @anchor :anchor
  @internal :internal
  @external :external
  @email :email
  @phone :phone
  @other :other

  @doc "Anchor link (#section)"
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "Internal link (same domain)"
  @spec internal() :: t()
  def internal, do: @internal
  @doc "External link (different domain)"
  @spec external() :: t()
  def external, do: @external
  @doc "Email link (mailto:)"
  @spec email() :: t()
  def email, do: @email
  @doc "Phone link (tel:)"
  @spec phone() :: t()
  def phone, do: @phone
  @doc "Other link type"
  @spec other() :: t()
  def other, do: @other

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:anchor), do: "anchor"
  def wire_value(:internal), do: "internal"
  def wire_value(:external), do: "external"
  def wire_value(:email), do: "email"
  def wire_value(:phone), do: "phone"
  def wire_value(:other), do: "other"
end
