# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:80a013b829b60a34e901242774c9ce31bc3782338d7e7b915876fe1ff94b0f82
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: Xberg.LinkType.t(),
          rel: [String.t()],
          attributes: [Xberg.KeyValueAttribute.t()]
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
