# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:87de50f35aab592b3fed6449bfd7b98378e0beb61883dfb3d636fe18c997264e
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ListIndentType do
  @moduledoc """
  List indentation character type.

  Controls whether list items are indented with spaces or tabs.
  """

  @typedoc "List indentation character type."
  @type t :: :spaces | :tabs

  @spaces :spaces
  @tabs :tabs

  @doc "Use spaces for indentation. Default. Width controlled by `list_indent_width`."
  @spec spaces() :: t()
  def spaces, do: @spaces
  @doc "Use tabs for indentation."
  @spec tabs() :: t()
  def tabs, do: @tabs

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:spaces), do: "Spaces"
  def wire_value(:tabs), do: "Tabs"
end
