# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:138a0c444494715d1ca5ded65573ca0cb23693cdc72a7ee087b069bc742a363d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ListType do
  @moduledoc "Type of list detection."

  @typedoc "Type of list detection."
  @type t :: :bullet | :numbered | :lettered | :indented

  @bullet :bullet
  @numbered :numbered
  @lettered :lettered
  @indented :indented

  @doc "Bullet points (-, *, •, etc.)"
  @spec bullet() :: t()
  def bullet, do: @bullet
  @doc "Numbered lists (1., 2., etc.)"
  @spec numbered() :: t()
  def numbered, do: @numbered
  @doc "Lettered lists (a., b., A., B., etc.)"
  @spec lettered() :: t()
  def lettered, do: @lettered
  @doc "Indented items"
  @spec indented() :: t()
  def indented, do: @indented

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:bullet), do: "Bullet"
  def wire_value(:numbered), do: "Numbered"
  def wire_value(:lettered), do: "Lettered"
  def wire_value(:indented), do: "Indented"
end
