# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LlmBudgetConfig do
  @moduledoc """
  Budget enforcement configuration.

  Mirrors liter-llm's `LlmBudgetConfig`. Only takes effect when liter-llm's `tower`
  feature is compiled in; otherwise the value round-trips through configuration
  but is not enforced at request time.
  """

  @typedoc "Budget enforcement configuration."
  @type t :: %__MODULE__{
          global_limit: float() | nil,
          model_limits: map() | nil,
          enforcement: String.t() | nil
        }

  defstruct global_limit: nil,
            model_limits: nil,
            enforcement: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
