# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:88ab9e361dc7c6a4a11d21df3a7bfa28c85f4ea8811ff6df2432d3f700bc2df4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MarkdownLink do
  @moduledoc "A link extracted from Markdown."

  @typedoc "A link extracted from Markdown."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          url: String.t() | nil
        }

  defstruct text: nil,
            url: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
