# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76ebd31fca1e72248a88f8d0004a96561c52964087a3b5b396bc6ad754d9c28d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MergeMode do
  @moduledoc """
  How partial results from multiple model calls (e.g. per page batch) are combined.

  Canonical home for the merge strategy referenced by presets and by the
  structured pipeline's post-processing. There is intentionally only one merge
  type across the crate — do not introduce a second.
  """

  @typedoc "How partial results from multiple model calls (e.g. per page batch) are combined."
  @type t :: :object_merge | :array_concat | :object_first

  @object_merge :object_merge
  @array_concat :array_concat
  @object_first :object_first

  @doc "Deep-merge JSON objects field by field (later calls fill missing fields)."
  @spec object_merge() :: t()
  def object_merge, do: @object_merge
  @doc "Concatenate top-level arrays across calls."
  @spec array_concat() :: t()
  def array_concat, do: @array_concat
  @doc "Keep the first non-empty result; ignore subsequent calls."
  @spec object_first() :: t()
  def object_first, do: @object_first

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:object_merge), do: "object_merge"
  def wire_value(:array_concat), do: "array_concat"
  def wire_value(:object_first), do: "object_first"
end
