# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f9b15404730295f23073972640dfda13b34d5603bc639f643f0bb5f1c61e5ff7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MetaSchema do
  @moduledoc "Compiled meta-schema validator over `preset.schema.json`."

  alias Xberg.Native
  defstruct [:ref]

  @typedoc "Compiled meta-schema validator over `preset.schema.json`."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Compile the given JSON text as a Draft 2020-12 meta-schema."
  def compile(meta_schema_json) do
    case Native.metaschema_compile(meta_schema_json) do
      {:ok, ref} -> {:ok, %__MODULE__{ref: ref}}
      {:error, error} -> {:error, error}
    end
  end

  @doc "Validate `raw` against the meta-schema and deserialize into a [`Preset`],"
  def parse_preset(obj, path, raw) do
    Native.metaschema_parse_preset(obj.ref, path, raw)
  end
end
