# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
          det_model: String.t() | nil,
          cls_model: String.t() | nil,
          rec_model: String.t() | nil,
          dict_file: String.t() | nil
        }

  defstruct det_model: nil,
            cls_model: nil,
            rec_model: nil,
            dict_file: nil
end
