# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1dc8abf7a1226ba76e72f70fd53bfd7f3200e874f8f74702fd8612c36dff7aae
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
          page_count: non_neg_integer(),
          pages: [Xberg.PageSignals.t()]
        }

  defstruct page_count: 0,
            pages: []
end
