# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:19d14b38580d54233ffe4bef1dded9533ddb13dc2b10bf326b347b915962453b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  @typedoc "A single backend stage in the OCR pipeline."
  @type t :: %__MODULE__{
          backend: String.t() | nil,
          priority: non_neg_integer(),
          language: [String.t()] | nil,
          tesseract_config: Xberg.TesseractConfig.t() | nil,
          paddle_ocr_config: String.t() | nil,
          vlm_config: Xberg.LlmConfig.t() | nil,
          backend_options: String.t() | nil
        }

  defstruct backend: nil,
            priority: nil,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil,
            backend_options: nil
end
