# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:019b857c88406e7da522dd259a8f843ac2dea194973cab9f96e9c4c102f32b3b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrTable do
  @moduledoc """
  Table detected via OCR.

  Represents a table structure recognized during OCR processing.
  """

  @typedoc "Table detected via OCR."
  @type t :: %__MODULE__{
          cells: [[String.t()]],
          markdown: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: Xberg.OcrTableBoundingBox.t() | nil
        }

  defstruct cells: [],
            markdown: nil,
            page_number: 0,
            bounding_box: nil
end
