# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9d0094a07fd8341ea105d8734f49e108d1ae4e4733a5bc5198aee201921a9d1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrElementLevel do
  @moduledoc """
  Hierarchical level of an OCR element.

  Maps to Tesseract's page segmentation hierarchy and provides
  equivalent semantics for PaddleOCR.
  """

  @typedoc "Hierarchical level of an OCR element."
  @type t :: :word | :line | :block | :page

  @word :word
  @line :line
  @block :block
  @page :page

  @doc "Individual word"
  @spec word() :: t()
  def word, do: @word
  @doc "Line of text (default for PaddleOCR)"
  @spec line() :: t()
  def line, do: @line
  @doc "Paragraph or text block"
  @spec block() :: t()
  def block, do: @block
  @doc "Page-level element"
  @spec page() :: t()
  def page, do: @page

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:word), do: "word"
  def wire_value(:line), do: "line"
  def wire_value(:block), do: "block"
  def wire_value(:page), do: "page"
end
