# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:621b34c6eecbedb498e3caebb0673a77fbbb30aa01e0e6a0ee0c7fd7422c3e79
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
          angle_degrees: float(),
          confidence: float() | nil
        }

  defstruct angle_degrees: 0.0,
            confidence: nil
end
