# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fec43c7c0a089d45e0a5d6bfd3def1bbf9f8eaf77238b49ea85dcc985bb8ba8d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrPoint do
  @moduledoc "A point in OCR raster pixel coordinates."

  @typedoc "A point in OCR raster pixel coordinates."
  @type t :: %__MODULE__{
          x: non_neg_integer(),
          y: non_neg_integer()
        }

  defstruct x: 0,
            y: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
