# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:411d2dd66d9e0fdc18269b00475348077626c128700ddf5d3c5d806b8792a3e2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrStrategy do
  @moduledoc """
  Which pages of a PDF get OCR'd when neither `force_ocr` nor `force_ocr_pages` applies.

  # Examples

  ```
  use xberg::{ExtractionConfig, OcrStrategy};

  // OCR pages that look like scans; keep native text everywhere else.
  let config = ExtractionConfig {
      ocr_strategy: OcrStrategy::ScannedPages { min_confidence: 0.7 },
      ..Default::default()
  };
  assert!(matches!(config.ocr_strategy, OcrStrategy::ScannedPages { .. }));
  ```
  """

  @typedoc "Which pages of a PDF get OCR'd when neither `force_ocr` nor `force_ocr_pages` applies."
  @type t :: term()

  @typedoc "OCR only when the native text layer fails a quality check (default)."
  @type auto :: :auto
  @typedoc "Additionally OCR every page that looks like a scan."
  @type scanned_pages :: %{mode: :scanned_pages, min_confidence: float()}

  def scanned_pages(min_confidence), do: {:scanned_pages, %{min_confidence: min_confidence}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:auto), do: "auto"
  def wire_value(:scanned_pages), do: "scanned_pages"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
