# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af4f1ffcf9ac16f4abec3524a813a1d1f8311157c1a59ca31c5648bc782ef8d7
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PaddleOcrConfig do
  @moduledoc """
  Configuration for PaddleOCR backend.

  Configures PaddleOCR text detection and recognition with multi-language support.
  Uses a builder pattern for convenient configuration.

  # Examples

  ```no_run
  use xberg::PaddleOcrConfig;

  // Create with default English configuration
  let config = PaddleOcrConfig::new("en");

  // Create with custom cache directory
  let config = PaddleOcrConfig::new("ch")
      .with_cache_dir("/path/to/cache".into());

  // Table detection is off by default (unlike `TesseractConfig`); PaddleOCR has no
  // per-word table-candidate signal, so unfiltered clustering over-fabricates tables
  // on ordinary prose. Enable it explicitly once you've validated it for your corpus.
  let config = PaddleOcrConfig::new("en")
      .with_table_detection(true);
  ```
  """

  @typedoc "Configuration for PaddleOCR backend."
  @type t :: %__MODULE__{
          language: String.t() | nil,
          cache_dir: String.t() | nil,
          use_angle_cls: boolean(),
          enable_table_detection: boolean(),
          det_db_thresh: float(),
          det_db_box_thresh: float(),
          det_db_unclip_ratio: float(),
          det_limit_side_len: non_neg_integer(),
          rec_batch_num: non_neg_integer(),
          padding: non_neg_integer(),
          drop_score: float(),
          model_tier: String.t() | nil,
          model_version: String.t() | nil,
          inference_backend: Xberg.PaddleInferenceBackend.t() | nil
        }

  defstruct language: "en",
            cache_dir: nil,
            use_angle_cls: false,
            enable_table_detection: false,
            det_db_thresh: 0.3,
            det_db_box_thresh: 0.5,
            det_db_unclip_ratio: 1.6,
            det_limit_side_len: 1_024,
            rec_batch_num: 6,
            padding: 10,
            drop_score: 0.5,
            model_tier: "mobile",
            model_version: "pp-ocrv6",
            inference_backend: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
