# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PaddleInferenceBackend do
  @moduledoc """
  Which concrete ONNX inference engine PaddleOCR model loading uses.

  Mirrors `sceptre::Backend` for the PaddleOCR backend: `Ort` is the native,
  full-featured path (acceleration/execution-provider hook, ONNX-embedded
  dictionary metadata); `Tract` is the pure-Rust, CPU-only path used on targets
  where `ort` cannot link (Android x86_64 emulator, WASM once wired).
  """

  @typedoc "Which concrete ONNX inference engine PaddleOCR model loading uses."
  @type t :: :ort | :tract

  @ort :ort
  @tract :tract

  @doc "Native ONNX Runtime (requires the `paddle-ocr-ort` feature)."
  @spec ort() :: t()
  def ort, do: @ort
  @doc "Pure-Rust ONNX via `tract` (requires the `paddle-ocr-tract` feature)."
  @spec tract() :: t()
  def tract, do: @tract
end
