# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:87d6af9cc98a1430b6246f73f5f8388595df46281463f8081e81888e28bd27ef
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PaddleOcrVlBackendOptions do
  @moduledoc "Runtime options accepted by the `candle-paddleocr-vl` backend."

  @typedoc "Runtime options accepted by the `candle-paddleocr-vl` backend."
  @type t :: %__MODULE__{
          task: Xberg.PaddleOcrVlTaskKind.t() | nil,
          model_path: String.t() | nil,
          model_id: String.t() | nil,
          hf_revision: String.t() | nil,
          cache_dir: String.t() | nil,
          device: Xberg.CandleDevicePreference.t() | nil
        }

  defstruct task: nil,
            model_path: nil,
            model_id: nil,
            hf_revision: nil,
            cache_dir: nil,
            device: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
