# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fdc8e9df619561ff01c099adbb7f977d360cbda28d6c88cd6926294ef26d4d5a
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PaddleInferenceBackend do
  @moduledoc """
  Which concrete ONNX inference engine PaddleOCR model loading uses.

  Mirrors `sceptre::Backend` for the PaddleOCR backend: `Ort` is the native,
  full-featured path (acceleration/execution-provider hook, ONNX-embedded
  dictionary metadata); `Tract` is the pure-Rust, CPU-only path used on targets
  where `ort` cannot link (Android x86_64 emulator, WASM once wired).
  """

  @typedoc "Which concrete ONNX inference engine PaddleOCR model loading uses."
  @type t :: :ort | :tract

  @ort :ort
  @tract :tract

  @doc "Native ONNX Runtime (requires the `paddle-ocr-ort` feature)."
  @spec ort() :: t()
  def ort, do: @ort
  @doc "Pure-Rust ONNX via `tract` (requires the `paddle-ocr-tract` feature)."
  @spec tract() :: t()
  def tract, do: @tract

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:ort), do: "ort"
  def wire_value(:tract), do: "tract"
end
