# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f5173aa61e577c67a0201c0b2553fcd4c0a4d70ef87e2cc720f6327d64993d1
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageSpan do
  @moduledoc """
  A single page covered by a chunk, with an optional bounding box on that page.

  See [`ChunkMetadata::page_spans`] (#1295) for population semantics.
  """

  @typedoc "A single page covered by a chunk, with an optional bounding box on that page."
  @type t :: %__MODULE__{
          page: non_neg_integer(),
          bbox: Xberg.BoundingBox.t() | nil
        }

  defstruct page: 0,
            bbox: nil
end
