# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4aaca6ec37337199947f9493ebe772008305ddfe50652be22b18ba9f067967b0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageHierarchy do
  @moduledoc """
  Page hierarchy structure containing heading levels and block information.

  Used when PDF text hierarchy extraction is enabled. Contains hierarchical
  blocks with heading levels (H1-H6) for semantic document structure.
  """

  @typedoc "Page hierarchy structure containing heading levels and block information."
  @type t :: %__MODULE__{
          block_count: non_neg_integer(),
          blocks: [Xberg.HierarchicalBlock.t()]
        }

  defstruct block_count: 0,
            blocks: []
end
