# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassification do
  @moduledoc "Classification result for a single page."

  @typedoc "Classification result for a single page."
  @type t :: %__MODULE__{
          page_number: non_neg_integer(),
          labels: [Xberg.ClassificationLabel.t()]
        }

  defstruct page_number: 0,
            labels: []
end
