# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83d99758403b657c469330db6f546efa402d2acdae92d1ad51d50d02d7c3f5a5
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageDimensions do
  @moduledoc """
  Metadata for individual page/slide/sheet.

  Captures per-page information including dimensions, content counts,
  and visibility state (for presentations).
  """

  @typedoc "Metadata for individual page/slide/sheet."
  @type t :: %__MODULE__{
          width: float(),
          height: float()
        }

  defstruct width: 0.0,
            height: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
