# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14a18266c7dcb2b6a35170a47384c75bef5eacb7efe26bee4b7fa0984e3adcd2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageOrientationHandling do
  @moduledoc """
  How a backend copes with a page raster whose text is not upright.

  Rotated-page handling is a backend capability, not a universal guarantee. An A/B run this
  session against `/Rotate 270` scanned pages showed the three handled cases genuinely differ:
  Tesseract reconstructs correct reading order on a sideways raster outright; PaddleOCR
  recognises the rotated text correctly (it warps each detected quad upright before running
  recognition) but leaves its block list in raw raster `(y, x)` order, so the caller must
  reorder; sceptre produces character garbage on the same sideways raster and only reads
  correctly once the page is rendered upright first. A caller that skips an upright-render step
  for a backend that actually needs one gets silent garbage, not an error.

  # Only one variant is discriminated (#657)

  Read this before "simplifying" the type. There is exactly one decision point in the
  codebase that inspects this value: `upright_raster_for_backend`
  (`crate::extractors::pdf::ocr`), which tests `orientation_handling != RequiresUpright` and
  otherwise does nothing. Every other mention forwards the value to that test. So, *to that
  codepath*, `SelfCorrecting` and `RecognisesRotatedText` are behaviourally identical — the
  enum is a boolean at the point of use, and the three variants describe measured backend
  behaviour rather than three dispatch paths.

  `RecognisesRotatedText`'s actual remedy is not this enum. The block-order fix is the
  `backend_options["page_rotation_degrees"]` hint injected by
  `ocr_config_with_page_rotation_hint` (`crate::extractors::pdf::ocr`) **unconditionally, for
  every backend**, which `PaddleOcrBackend::process_image` reads back
  (`page_rotation_degrees_from_backend_options` -> `residual_rotation_for_reorder` ->
  `reorder_blocks_for_page_rotation`, `crate::paddle_ocr::backend`) and applies internally.
  Declaring `RecognisesRotatedText` therefore changes nothing on its own; a backend in that
  class must also read the hint. Conversely, gating that hint on this enum would remove a
  field from Tesseract's `OcrConfig` and hence from the OCR cache key
  (`hash(image + language + config)`), invalidating every cached page — do not do it without
  its own A/B.

  # PDF-route-only

  Only the PDF OCR routes call `OcrBackend::page_orientation_handling` (the `--force-ocr`
  route via `extract_with_ocr` and the scanned-pages route via `extract_mixed_ocr_native`).
  The raw-image route (`crate::extractors::image`) never calls it: there is no `/Rotate` to
  consult, and orientation there is handled by the PP-LCNet document-orientation classifier
  (`crate::doc_orientation`) gated on `OcrConfig::auto_rotate`.

  # Cost of the default

  The trait default is `RequiresUpright` (deliberately the least capable option, see
  [`OcrBackend::page_orientation_handling`]). A backend that does not declare therefore pays,
  on every page with `/Rotate != 0`, a re-encode plus rotation of the raster in
  `upright_raster_for_backend` and a bounding-box round-trip back through
  `undo_upright_raster_correction`. That is the safe direction to be wrong in, but it is not
  free, and for a backend that never got measured it is not known to be necessary either.
  """

  @typedoc "How a backend copes with a page raster whose text is not upright."
  @type t :: :self_correcting | :recognises_rotated_text | :requires_upright

  @self_correcting :self_correcting
  @recognises_rotated_text :recognises_rotated_text
  @requires_upright :requires_upright

  @doc "Reconstructs reading order regardless of page rotation — safe to hand a raster in any orientation."
  @spec self_correcting() :: t()
  def self_correcting, do: @self_correcting
  @doc "Recognises rotated text correctly but emits blocks in raw raster order, so the caller must reorder."
  @spec recognises_rotated_text() :: t()
  def recognises_rotated_text, do: @recognises_rotated_text
  @doc "Requires an upright raster; rotated text produces garbage."
  @spec requires_upright() :: t()
  def requires_upright, do: @requires_upright

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:self_correcting), do: "SelfCorrecting"
  def wire_value(:recognises_rotated_text), do: "RecognisesRotatedText"
  def wire_value(:requires_upright), do: "RequiresUpright"
end
