# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ed20f16d48f4b5824145db190a26410c4ec3860ede6a075c36c6a8d8feddd10
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
          prompt_template: String.t() | nil,
          labels: [String.t()],
          multi_label: boolean(),
          llm: Xberg.LlmConfig.t()
        }

  defstruct prompt_template: nil,
            labels: [],
            multi_label: false,
            llm: nil
end
