# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4a8a0404a7290895e1d25b1ddbca38c17d8e9475fc70fc9f216574e69e27d2eb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PatternMatch do
  @moduledoc "One detected PII span in the input text."

  @typedoc "One detected PII span in the input text."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: Xberg.PiiCategory.t(),
          text: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            text: nil
end
