# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2f4a51643a8a0f7cda145238e45ea3361de53c99750bcf38010bc1ea0fdaf73b
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PdfFormField do
  @moduledoc """
  A form field extracted from a PDF's AcroForm or XFA structure.

  Populated by the PDF extractor when `PdfConfig::extract_form_fields` is
  enabled and the document is a fillable form. Supports both AcroForm (standard)
  and XFA (XML Forms Architecture) layers. When both are present, AcroForm fields
  take priority (canonical fallback per PDF spec), and XFA-only fields are appended.
  The collection is empty for non-form PDFs and for non-PDF formats.
  """

  @typedoc "A form field extracted from a PDF's AcroForm or XFA structure."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          full_name: String.t() | nil,
          field_type: Xberg.FormFieldType.t(),
          value: String.t() | nil,
          default_value: String.t() | nil,
          flags: non_neg_integer(),
          page: non_neg_integer() | nil,
          bbox: Xberg.BoundingBox.t() | nil,
          max_length: non_neg_integer() | nil,
          tooltip: String.t() | nil
        }

  defstruct name: nil,
            full_name: nil,
            field_type: :unknown,
            value: nil,
            default_value: nil,
            flags: 0,
            page: nil,
            bbox: nil,
            max_length: nil,
            tooltip: nil
end
