# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a3944e9d8354ae447bbfc07a19ec40504efbd04ec19a5ead2220ac68d2491d6f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PdfAnnotationType do
  @moduledoc "Type of PDF annotation."

  @typedoc "Type of PDF annotation."
  @type t ::
          :text
          | :highlight
          | :link
          | :stamp
          | :underline
          | :strike_out
          | :squiggly
          | :ink
          | :square
          | :circle
          | :polygon
          | :poly_line
          | :line
          | :caret
          | :file_attachment
          | :sound
          | :movie
          | :other

  @text :text
  @highlight :highlight
  @link :link
  @stamp :stamp
  @underline :underline
  @strike_out :strike_out
  @squiggly :squiggly
  @ink :ink
  @square :square
  @circle :circle
  @polygon :polygon
  @poly_line :poly_line
  @line :line
  @caret :caret
  @file_attachment :file_attachment
  @sound :sound
  @movie :movie
  @other :other

  @doc "Sticky note / text annotation"
  @spec text() :: t()
  def text, do: @text
  @doc "Highlighted text region"
  @spec highlight() :: t()
  def highlight, do: @highlight
  @doc "Hyperlink annotation"
  @spec link() :: t()
  def link, do: @link
  @doc "Rubber stamp annotation"
  @spec stamp() :: t()
  def stamp, do: @stamp
  @doc "Underline text markup"
  @spec underline() :: t()
  def underline, do: @underline
  @doc "Strikeout text markup"
  @spec strike_out() :: t()
  def strike_out, do: @strike_out
  @doc "Squiggly (wavy) underline text markup"
  @spec squiggly() :: t()
  def squiggly, do: @squiggly
  @doc "Freehand drawing (ink) annotation"
  @spec ink() :: t()
  def ink, do: @ink
  @doc "Rectangle/box shape annotation"
  @spec square() :: t()
  def square, do: @square
  @doc "Ellipse/oval shape annotation"
  @spec circle() :: t()
  def circle, do: @circle
  @doc "Closed polygon shape annotation"
  @spec polygon() :: t()
  def polygon, do: @polygon
  @doc "Open polyline shape annotation"
  @spec poly_line() :: t()
  def poly_line, do: @poly_line
  @doc "Line annotation"
  @spec line() :: t()
  def line, do: @line
  @doc "Caret (text-insertion marker) annotation"
  @spec caret() :: t()
  def caret, do: @caret
  @doc "Embedded file attachment annotation"
  @spec file_attachment() :: t()
  def file_attachment, do: @file_attachment
  @doc "Embedded sound annotation"
  @spec sound() :: t()
  def sound, do: @sound
  @doc "Embedded movie annotation"
  @spec movie() :: t()
  def movie, do: @movie
  @doc "Any other annotation type"
  @spec other() :: t()
  def other, do: @other

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:text), do: "text"
  def wire_value(:highlight), do: "highlight"
  def wire_value(:link), do: "link"
  def wire_value(:stamp), do: "stamp"
  def wire_value(:underline), do: "underline"
  def wire_value(:strike_out), do: "strike_out"
  def wire_value(:squiggly), do: "squiggly"
  def wire_value(:ink), do: "ink"
  def wire_value(:square), do: "square"
  def wire_value(:circle), do: "circle"
  def wire_value(:polygon), do: "polygon"
  def wire_value(:poly_line), do: "poly_line"
  def wire_value(:line), do: "line"
  def wire_value(:caret), do: "caret"
  def wire_value(:file_attachment), do: "file_attachment"
  def wire_value(:sound), do: "sound"
  def wire_value(:movie), do: "movie"
  def wire_value(:other), do: "other"
end
