# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PptxMetadata do
  @moduledoc """
  PowerPoint presentation metadata.

  Extracted from PPTX files containing slide counts and presentation details.
  """

  @typedoc "PowerPoint presentation metadata."
  @type t :: %__MODULE__{
          slide_count: non_neg_integer(),
          slide_names: [String.t()],
          image_count: non_neg_integer() | nil,
          table_count: non_neg_integer() | nil
        }

  defstruct slide_count: 0,
            slide_names: [],
            image_count: nil,
            table_count: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
