# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e814c2be3d401f757dcf582925dfa2817e7b36ef2c0b6f6388a5744d454a558d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PresetCategory do
  @moduledoc "High-level category used to group presets in the registry UI."

  @typedoc "High-level category used to group presets in the registry UI."
  @type t :: :finance | :identity | :legal | :logistics | :medical | :hr | :other

  @finance :finance
  @identity :identity
  @legal :legal
  @logistics :logistics
  @medical :medical
  @hr :hr
  @other :other

  @doc "Invoices, receipts, statements, purchase orders, W-9."
  @spec finance() :: t()
  def finance, do: @finance
  @doc "Passports, drivers licenses, insurance cards."
  @spec identity() :: t()
  def identity, do: @identity
  @doc "Contracts, NDAs, agreements."
  @spec legal() :: t()
  def legal, do: @legal
  @doc "Bills of lading, customs declarations, packing lists."
  @spec logistics() :: t()
  def logistics, do: @logistics
  @doc "Clinical records, lab reports."
  @spec medical() :: t()
  def medical, do: @medical
  @doc "Pay stubs, resumes, employment offers."
  @spec hr() :: t()
  def hr, do: @hr
  @doc "Catch-all for documents that don't fit the other categories."
  @spec other() :: t()
  def other, do: @other

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:finance), do: "finance"
  def wire_value(:identity), do: "identity"
  def wire_value(:legal), do: "legal"
  def wire_value(:logistics), do: "logistics"
  def wire_value(:medical), do: "medical"
  def wire_value(:hr), do: "hr"
  def wire_value(:other), do: "other"
end
