# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52ed88cd532107834dbcde5fd55882e170ecbbbdd32dadc897b1d7fa33ef8418
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded results.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct source: nil,
            message: nil
end
