# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f0a0d15ed5ffa1585447a1e3c7b2f4a09a7cd1b2421ea257b87fa53da5a62151
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ProxyConfig do
  @moduledoc "Proxy configuration for HTTP requests."

  @typedoc "Proxy configuration for HTTP requests."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          username: String.t() | nil,
          password: String.t() | nil
        }

  defstruct url: nil,
            username: nil,
            password: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
