# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d48d05848cd24802655045bf03eb44ecbda13f71baeaf781e54e9e2c8c0f5475
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
          message_count: non_neg_integer()
        }

  defstruct message_count: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
