# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:703c744e033a47cd56d2e25cb77378e966b88b25f7b4991646f6310b1f727199
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
          payload: String.t() | nil,
          confidence: float() | nil,
          bbox: Xberg.QrBoundingBox.t() | nil
        }

  defstruct payload: nil,
            confidence: nil,
            bbox: nil
end
