# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2cdb859769b07b47fcc8f687f09a08dfd788a5518c108c6b6df501afc92e4948
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RedactionPattern do
  @moduledoc """
  One user-supplied regex pattern to redact.

  The pattern is compiled with the Rust `regex` crate (no look-around). Case
  sensitivity is encoded in the pattern via the `(?i)` inline flag when
  [`Self::case_sensitive`] is `false`.
  """

  @typedoc "One user-supplied regex pattern to redact."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          pattern: String.t() | nil,
          case_sensitive: boolean()
        }

  defstruct label: nil,
            pattern: nil,
            case_sensitive: nil
end
