# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionPattern do
  @moduledoc """
  One user-supplied regex pattern to redact.

  The pattern is compiled with the Rust `regex` crate (no look-around). Case
  sensitivity is encoded in the pattern via the `(?i)` inline flag when
  [`Self::case_sensitive`] is `false`.
  """

  @typedoc "One user-supplied regex pattern to redact."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          pattern: String.t() | nil,
          case_sensitive: boolean()
        }

  defstruct label: nil,
            pattern: nil,
            case_sensitive: false
end
