# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7931027f309d13f7c2ad233514b1bb7deba108cf68b31c5b54da976187c0e75
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RedactionReport do
  @moduledoc """
  Audit report describing what the redaction processor found and how it replaced it.

  The redactor returns this alongside the rewritten content so compliance, replay, and
  audit-log consumers can see exactly what fired. Offsets are relative to the *original*
  pre-redaction `content` and are intended for audit reconstruction only — the original
  bytes are dropped at the end of the pipeline.
  """

  @typedoc "Audit report describing what the redaction processor found and how it replaced it."
  @type t :: %__MODULE__{
          findings: [Xberg.RedactionFinding.t()],
          total_redacted: non_neg_integer()
        }

  defstruct findings: [],
            total_redacted: 0
end
