# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:900b1fa90d6ceac71de334dbd196598c146d102b52152c7abb02af74ca7ddb8a
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RegionKind do
  @moduledoc "Classification of a detected layout region that warrants VLM extraction."

  @typedoc "Classification of a detected layout region that warrants VLM extraction."
  @type t :: :figure | :dense_table | :complex_layout | :caption

  @figure :figure
  @dense_table :dense_table
  @complex_layout :complex_layout
  @caption :caption

  @doc "A figure, diagram, chart, or image region."
  @spec figure() :: t()
  def figure, do: @figure
  @doc "A densely formatted or complex table."
  @spec dense_table() :: t()
  def dense_table, do: @dense_table
  @doc "A region with complex or mixed layout."
  @spec complex_layout() :: t()
  def complex_layout, do: @complex_layout
  @doc "A standalone image to caption."
  @spec caption() :: t()
  def caption, do: @caption

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:figure), do: "Figure"
  def wire_value(:dense_table), do: "DenseTable"
  def wire_value(:complex_layout), do: "ComplexLayout"
  def wire_value(:caption), do: "Caption"
end
