# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0cdfdfb4863929d24d5b29b71abe94225a3b791aeb2017326fd8fce5df6fea3
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RelationshipKind do
  @moduledoc "Semantic kind of a relationship between document elements."

  @typedoc "Semantic kind of a relationship between document elements."
  @type t ::
          :footnote_reference
          | :citation_reference
          | :internal_link
          | :caption
          | :label
          | :toc_entry
          | :cross_reference

  @footnote_reference :footnote_reference
  @citation_reference :citation_reference
  @internal_link :internal_link
  @caption :caption
  @label :label
  @toc_entry :toc_entry
  @cross_reference :cross_reference

  @doc "Footnote marker -> footnote definition."
  @spec footnote_reference() :: t()
  def footnote_reference, do: @footnote_reference
  @doc "Citation marker -> bibliography entry."
  @spec citation_reference() :: t()
  def citation_reference, do: @citation_reference
  @doc "Internal anchor link (`#id`) -> target heading/element."
  @spec internal_link() :: t()
  def internal_link, do: @internal_link
  @doc "Caption paragraph -> figure/table it describes."
  @spec caption() :: t()
  def caption, do: @caption
  @doc "Label -> labeled element (HTML `<label for>`, LaTeX `\\label{}`)."
  @spec label() :: t()
  def label, do: @label
  @doc "TOC entry -> target section."
  @spec toc_entry() :: t()
  def toc_entry, do: @toc_entry
  @doc "Cross-reference (LaTeX `\\ref{}`, DOCX cross-reference field)."
  @spec cross_reference() :: t()
  def cross_reference, do: @cross_reference

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:footnote_reference), do: "footnote_reference"
  def wire_value(:citation_reference), do: "citation_reference"
  def wire_value(:internal_link), do: "internal_link"
  def wire_value(:caption), do: "caption"
  def wire_value(:label), do: "label"
  def wire_value(:toc_entry), do: "toc_entry"
  def wire_value(:cross_reference), do: "cross_reference"
end
