# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9d471bebfca8a5b2513664ba09b14145ceca594f31a7581fa48a9313a44785e3
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RerankerHead do
  @moduledoc """
  Selects how a local ONNX reranker's raw output tensor is turned into a score.

  - [`RerankerHead::CrossEncoder`] — classic single-logit cross-encoder head:
    the model emits `[batch, 1]` (or `[batch]`) logits; the caller applies
    sigmoid to get a `[0, 1]` score. This is the original, unchanged path.
  - [`RerankerHead::Qwen3Generative`] — Qwen3 generative-reranker head: the
    model emits `[batch, seq, vocab]` logits; the score is `P("yes")` read
    from the last token's logits over the "yes"/"no" vocabulary entries,
    via a softmax over those two logits. Already a `[0, 1]` probability —
    no sigmoid is applied.
  """

  @typedoc "Selects how a local ONNX reranker's raw output tensor is turned into a score."
  @type t :: :cross_encoder | :qwen3_generative

  @cross_encoder :cross_encoder
  @qwen3_generative :qwen3_generative

  @doc "Single-logit cross-encoder head (sigmoid applied by the caller)."
  @spec cross_encoder() :: t()
  def cross_encoder, do: @cross_encoder
  @doc "Qwen3 generative-reranker head (softmax over yes/no token logits)."
  @spec qwen3_generative() :: t()
  def qwen3_generative, do: @qwen3_generative

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:cross_encoder), do: "cross_encoder"
  def wire_value(:qwen3_generative), do: "qwen3_generative"
end
