# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2492ed1ab0e20674e481a6e8d6e98e4c63e6110779e760a6add3b1bea8e9da5a
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ResolvedPreset do
  @moduledoc """
  A preset merged with caller-supplied overrides (custom schema, prompt suffix,
  context map). Output is what the pipeline orchestrator consumes.
  """

  @typedoc "A preset merged with caller-supplied overrides (custom schema, prompt suffix, context map). Output is what the pipeline orchestrator consumes."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          version: String.t() | nil,
          fingerprint: String.t() | nil,
          schema_name: String.t() | nil,
          schema: String.t() | nil,
          system_prompt: String.t() | nil,
          merge_mode: Xberg.MergeMode.t(),
          preferred_call_mode: Xberg.CallMode.t(),
          emit_citations: boolean()
        }

  defstruct id: nil,
            version: nil,
            fingerprint: nil,
            schema_name: nil,
            schema: nil,
            system_prompt: nil,
            merge_mode: :object_merge,
            preferred_call_mode: :text_only,
            emit_citations: false
end
