# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6c0c7e5c873fe55502d30ffe3765e16d115c437bcadf7940bed2450041dfb4c4
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RevisionAnchor do
  @moduledoc "Best-effort document location for a revision."

  @typedoc "Best-effort document location for a revision."
  @type t :: term()

  @typedoc "Body paragraph, identified by its zero-based index in the document flow."
  @type paragraph :: %{type: :paragraph, index: non_neg_integer()}
  @typedoc "Cell inside a table."
  @type table_cell :: %{type: :table_cell, row: non_neg_integer(), col: non_neg_integer(), table_index: non_neg_integer()}
  @typedoc "Page, identified by its zero-based index."
  @type page :: %{type: :page, index: non_neg_integer()}
  @typedoc "Presentation slide, identified by its zero-based index."
  @type slide :: %{type: :slide, index: non_neg_integer()}
  @typedoc "Spreadsheet cell or range, identified by sheet index and optional name."
  @type sheet :: %{type: :sheet, index: non_neg_integer(), name: String.t()}

  def paragraph(index), do: {:paragraph, %{index: index}}
  def table_cell(row, col, table_index), do: {:table_cell, %{row: row, col: col, table_index: table_index}}
  def page(index), do: {:page, %{index: index}}
  def slide(index), do: {:slide, %{index: index}}
  def sheet(index, name), do: {:sheet, %{index: index, name: name}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:paragraph), do: "paragraph"
  def wire_value(:table_cell), do: "table_cell"
  def wire_value(:page), do: "page"
  def wire_value(:slide), do: "slide"
  def wire_value(:sheet), do: "sheet"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
