# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:97fc7e6396a37dc114fe8d978141bbf869b049ea692770eaa46c70b403c9069c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SchemaCompliance do
  @moduledoc """
  Schema-validation outcome surfaced as one of three buckets.

  Fold into the combined confidence score without leaking internal validation
  error types.
  """

  @typedoc "Schema-validation outcome surfaced as one of three buckets."
  @type t :: :all_valid | :partial_valid | :all_invalid

  @all_valid :all_valid
  @partial_valid :partial_valid
  @all_invalid :all_invalid

  @doc "Every batch validated against the schema."
  @spec all_valid() :: t()
  def all_valid, do: @all_valid
  @doc "At least one batch validated; at least one did not."
  @spec partial_valid() :: t()
  def partial_valid, do: @partial_valid
  @doc "No batch validated."
  @spec all_invalid() :: t()
  def all_invalid, do: @all_invalid

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:all_valid), do: "all_valid"
  def wire_value(:partial_valid), do: "partial_valid"
  def wire_value(:all_invalid), do: "all_invalid"
end
