# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7409f6963a40323cfeed6089fc493cee32b4bb31cd83f498d517a6ebe957693c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SparseEmbedding do
  @moduledoc """
  A sparse learned embedding: vocabulary term indices and their weights.

  `indices` are ascending vocabulary token ids; `values[i]` is the weight for
  `indices[i]`. The two arrays always have equal length. Only strictly-positive
  terms are retained, so the representation is genuinely sparse.
  """

  @typedoc "A sparse learned embedding: vocabulary term indices and their weights."
  @type t :: %__MODULE__{
          indices: [non_neg_integer()],
          values: [float()]
        }

  defstruct indices: [],
            values: []
end
