# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7943753752aefc5bb4cdf56ad46a3d57ec9c42f39bd254fa6e51e6d4758943df
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SparseEmbeddingPreset do
  @moduledoc "Static metadata for a bundled SPLADE preset (WASM/Android-safe, no ORT)."

  @typedoc "Static metadata for a bundled SPLADE preset (WASM/Android-safe, no ORT)."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          model_repo: String.t() | nil,
          model_file: String.t() | nil,
          additional_files: [String.t()],
          max_length: non_neg_integer(),
          description: String.t() | nil
        }

  defstruct name: nil,
            model_repo: nil,
            model_file: nil,
            additional_files: [],
            max_length: 0,
            description: nil
end
