# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d5f2f63c228c32484b341baf873c013928478e37a080dd4b14890acaad415fa2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.SsrfPolicy do
  @moduledoc "SSRF policy configuration."

  @typedoc "SSRF policy configuration."
  @type t :: %__MODULE__{
          deny_private: boolean(),
          allowlist: [Xberg.HostMatcher.t()],
          max_redirects: non_neg_integer()
        }

  defstruct deny_private: true,
            allowlist: [],
            max_redirects: 5

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
