# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ca2a49e1d1d51395e98df719f8356c0a98d775722ace2541223b39a5bf716076
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @typedoc "Structured data type classification."
  @type t :: :"json-ld" | :microdata | :rdfa

  @json_ld :"json-ld"
  @microdata :microdata
  @rd_fa :rdfa

  @doc "JSON-LD structured data"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "Microdata"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDFa"
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:json_ld), do: "json-ld"
  def wire_value(:microdata), do: "microdata"
  def wire_value(:rd_fa), do: "rdfa"
end
