# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a1e595cbd8f5be901af5172f8b20a38c9ccabf20681de6ff9b07cd935d2e90f0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
          from_index: non_neg_integer(),
          to_index: non_neg_integer(),
          cell_changes: [Xberg.CellChange.t()]
        }

  defstruct from_index: 0,
            to_index: 0,
            cell_changes: []
end
