# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TranslationConfig do
  @moduledoc "Configuration for the translation post-processor."

  @typedoc "Configuration for the translation post-processor."
  @type t :: %__MODULE__{
          target_lang: String.t() | nil,
          source_lang: String.t() | nil,
          preserve_markup: boolean(),
          llm: Xberg.LlmConfig.t()
        }

  defstruct target_lang: nil,
            source_lang: nil,
            preserve_markup: false,
            llm: nil
end
