# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a480842af1dff9f13a20f21c03ad632e5a645493e5c5ecd39e02eef80fa31495
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TranslationConfig do
  @moduledoc "Configuration for the translation post-processor."

  @typedoc "Configuration for the translation post-processor."
  @type t :: %__MODULE__{
          target_lang: String.t() | nil,
          source_lang: String.t() | nil,
          preserve_markup: boolean(),
          llm: Xberg.LlmConfig.t()
        }

  defstruct target_lang: nil,
            source_lang: nil,
            preserve_markup: false,
            llm: nil
end
