# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:be08c0ade9bdbbd8dc0e497c4f74a71a0c2639acea8f136ac17c2c89cb8b10b2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TrocrBackendOptions do
  @moduledoc "Runtime options accepted by the `candle-trocr` backend."

  @typedoc "Runtime options accepted by the `candle-trocr` backend."
  @type t :: %__MODULE__{
          variant: Xberg.CandleTrocrVariant.t() | nil,
          device: Xberg.CandleDevicePreference.t() | nil,
          cache_dir: String.t() | nil,
          hf_revision: String.t() | nil
        }

  defstruct variant: nil,
            device: nil,
            cache_dir: nil,
            hf_revision: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
