# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.UriKind do
  @moduledoc "Semantic classification of an extracted URI."

  @typedoc "Semantic classification of an extracted URI."
  @type t :: :hyperlink | :image | :anchor | :citation | :reference | :email

  @hyperlink :hyperlink
  @image :image
  @anchor :anchor
  @citation :citation
  @reference :reference
  @email :email

  @doc "A clickable hyperlink (web URL, file link)."
  @spec hyperlink() :: t()
  def hyperlink, do: @hyperlink
  @doc "An image or media resource reference."
  @spec image() :: t()
  def image, do: @image
  @doc "An internal anchor or cross-reference target."
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "A citation or bibliographic reference (DOI, academic ref)."
  @spec citation() :: t()
  def citation, do: @citation
  @doc "A general reference (e.g. `\\ref{}` in LaTeX, `:ref:` in RST)."
  @spec reference() :: t()
  def reference, do: @reference
  @doc "An email address (`mailto:` link or bare email)."
  @spec email() :: t()
  def email, do: @email
end
