# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.UrlEscapeStyle do
  @moduledoc """
  URL encoding strategy for link and image destinations.

  Controls how special characters in URL destinations are handled when they
  require escaping to produce valid Markdown.

  The `Angle` variant (default) wraps the destination in angle brackets:
  `[text](<url with spaces>)`. This is the CommonMark-specified escape hatch
  but breaks when the URL itself contains `>`.

  The `Percent` variant percent-encodes every character that is not an RFC 3986
  unreserved character or `/`, producing a destination safe for all Markdown
  parsers: `[text](url%20with%20spaces)`.
  """

  @typedoc "URL encoding strategy for link and image destinations."
  @type t :: :angle | :percent

  @angle :angle
  @percent :percent

  @doc "Wrap destinations that contain spaces or newlines in angle brackets. Default."
  @spec angle() :: t()
  def angle, do: @angle
  @doc "Percent-encode all characters that are not RFC 3986 unreserved or `/`."
  @spec percent() :: t()
  def percent, do: @percent
end
