# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1f9ec07b48747ff4ab68a1cb6938fea4ed3eba934d57cda6f7f28b4c9bb3f37d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.UrlExtractionConfig do
  @moduledoc "URL ingestion and crawl configuration."

  @typedoc "URL ingestion and crawl configuration."
  @type t :: %__MODULE__{
          mode: Xberg.UrlExtractionMode.t(),
          crawl: Xberg.CrawlConfig.t(),
          document_url_pattern: String.t() | nil,
          max_document_urls_per_result: non_neg_integer() | nil,
          max_total_urls: non_neg_integer() | nil,
          allow_local_file_inputs: boolean(),
          allow_file_uris: boolean()
        }

  defstruct mode: :auto,
            crawl: nil,
            document_url_pattern: nil,
            max_document_urls_per_result: nil,
            max_total_urls: nil,
            allow_local_file_inputs: true,
            allow_file_uris: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
