# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:831b399f46d33803ddc628f18c0f4e6b88677bea2886e8408721651d0a53333d
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.WhisperModel do
  @moduledoc """
  Supported Whisper model sizes.

  These map to published ONNX exports on Hugging Face (onnx-community or
  similar orgs). The actual filenames and repos are resolved inside the
  transcription engine.
  """

  @typedoc "Supported Whisper model sizes."
  @type t :: :tiny | :base | :small | :medium | :large_v3

  @tiny :tiny
  @base :base
  @small :small
  @medium :medium
  @large_v3 :large_v3

  @doc "Smallest, fastest, lowest quality. Good default for development and CI."
  @spec tiny() :: t()
  def tiny, do: @tiny
  @doc "Reasonable quality/speed tradeoff."
  @spec base() :: t()
  def base, do: @base
  @doc "Better accuracy with higher memory and cache use."
  @spec small() :: t()
  def small, do: @small
  @doc "High quality; slower and more memory-intensive."
  @spec medium() :: t()
  def medium, do: @medium
  @doc "Best quality (large-v3). Use only when latency and memory use are acceptable."
  @spec large_v3() :: t()
  def large_v3, do: @large_v3

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:tiny), do: "tiny"
  def wire_value(:base), do: "base"
  def wire_value(:small), do: "small"
  def wire_value(:medium), do: "medium"
  def wire_value(:large_v3), do: "large_v3"
end
