# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.WhitespaceMode do
  @moduledoc """
  Whitespace handling strategy during conversion.

  Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
  """

  @typedoc "Whitespace handling strategy during conversion."
  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @doc "Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior."
  @spec normalized() :: t()
  def normalized, do: @normalized
  @doc "Preserve all whitespace exactly as it appears in the HTML."
  @spec strict() :: t()
  def strict, do: @strict
end
