# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11d96e25186281c68cee92cfac782bff02b6110084daac1e30cfd7541c084e41
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.YakeParams do
  @moduledoc "YAKE-specific parameters."

  @typedoc "YAKE-specific parameters."
  @type t :: %__MODULE__{
          window_size: non_neg_integer()
        }

  defstruct window_size: 2

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
