# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c717cbdb6e61faccb18251131f41336d45975e7523379abc8dd55ee962a5e538
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
          min: non_neg_integer() | nil,
          max: non_neg_integer() | nil,
          years: [non_neg_integer()]
        }

  defstruct min: nil,
            max: nil,
            years: []
end
