<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1faa4f33003fb18708348d4219d80a929dc94666d01c6f695fd3da3cafbc8765
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: post_processor_management. */
final class PostProcessorManagementTest extends TestCase
{


    /** Clear all post-processors and verify list is empty */
    public function test_post_processors_clear(): void
    {
        $result = Xberg::clearPostProcessors();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered post-processors */
    public function test_post_processors_list(): void
    {
        $result = Xberg::listPostProcessors();

        $this->assertNotNull($result);


    }

}
