<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1e14ad60a36e51f1779ed27b47355fb8a673ac0f50d6331ab6434e34a97dbb3a
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: registry. */
final class RegistryTest extends TestCase
{


    /** List embedding backends */
    public function test_list_embedding_backends(): void
    {
        $result = Xberg::listEmbeddingBackends();

        $this->assertNotNull($result);


    }


    /** List OCR backends */
    public function test_list_ocr_backends(): void
    {
        $result = Xberg::listOcrBackends();

        $this->assertNotNull($result);


    }


    /** List post-processors */
    public function test_list_post_processors(): void
    {
        $result = Xberg::listPostProcessors();

        $this->assertNotNull($result);


    }


    /** List renderers */
    public function test_list_renderers(): void
    {
        $result = Xberg::listRenderers();

        $this->assertNotNull($result);


    }


    /** List validators */
    public function test_list_validators(): void
    {
        $result = Xberg::listValidators();

        $this->assertNotNull($result);


    }

}
