<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:be4c25c5a113c419938741a8a4218808826328e56682dc9c57b3db536b350af3
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: renderer_management. */
final class RendererManagementTest extends TestCase
{


    /** Clear all renderers and verify list is empty */
    public function test_renderers_clear(): void
    {
        $result = Xberg::clearRenderers();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered renderers */
    public function test_renderers_list(): void
    {
        $result = Xberg::listRenderers();

        $this->assertNotNull($result);


    }

}
