<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:02b9ab3218831b9bca3583c98585691fa07a9b2102c4fa18708d943ccfa81ded
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: reranker_backend_management. */
final class RerankerBackendManagementTest extends TestCase
{


    /** Clear all reranker backends and verify list is empty */
    public function test_clear_reranker_backends(): void
    {
        $result = Xberg::clearRerankerBackends();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered reranker backends */
    public function test_list_reranker_backends(): void
    {
        $result = Xberg::listRerankerBackends();

        $this->assertNotNull($result);


    }

}
