<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:96ed214fe00bccb32aaa7a52fd79a01e6134155eb3da078cf9a355468aeb8d78
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: tokenizer_backend_management. */
final class TokenizerBackendManagementTest extends TestCase
{


    /** Clear all tokenizer backends and verify list is empty */
    public function test_tokenizer_backends_clear(): void
    {
        $result = Xberg::clearTokenizerBackends();

        $this->assertTrue(true, 'expected the call not to throw');


    }


    /** List all registered tokenizer backends */
    public function test_tokenizer_backends_list(): void
    {
        $result = Xberg::listTokenizerBackends();

        $this->assertNotNull($result);


    }

}
