// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dec183bec95198c210b6a0235f2bb1ec41d28c1299ec60ffe0f19494f1d19cb0
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: post_processor_management.
final class PostProcessorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testPostProcessorsClear() throws {
        // Clear all post-processors and verify list is empty
        XCTAssertNoThrow(try Xberg.clearPostProcessors())
    }

    func testPostProcessorsList() throws {
        // List all registered post-processors
        let result = try Xberg.listPostProcessors()
        XCTAssertNotNil(result)
    }

}
