// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9954897be8452a5a744c630013712d26a3519af67a37b1dea78092b7f4567f18
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: registry.
final class RegistryTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testListEmbeddingBackends() throws {
        // List embedding backends
        let result = try Xberg.listEmbeddingBackends()
        XCTAssertNotNil(result)
    }

    func testListOcrBackends() throws {
        // List OCR backends
        let result = try Xberg.listOcrBackends()
        XCTAssertNotNil(result)
    }

    func testListPostProcessors() throws {
        // List post-processors
        let result = try Xberg.listPostProcessors()
        XCTAssertNotNil(result)
    }

    func testListRenderers() throws {
        // List renderers
        let result = try Xberg.listRenderers()
        XCTAssertNotNil(result)
    }

    func testListValidators() throws {
        // List validators
        let result = try Xberg.listValidators()
        XCTAssertNotNil(result)
    }

}
