// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7c0bcf02fc64c03434e82c9d1e359641d413994e34b294723df0a6c57821a299
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: tokenizer_backend_management.
final class TokenizerBackendManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testTokenizerBackendsClear() throws {
        // Clear all tokenizer backends and verify list is empty
        XCTAssertNoThrow(try Xberg.clearTokenizerBackends())
    }

    func testTokenizerBackendsList() throws {
        // List all registered tokenizer backends
        let result = try Xberg.listTokenizerBackends()
        XCTAssertNotNil(result)
    }

}
