// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e8e23c3bc8a67b5f8122a94769d201dd9fc6ea0d229a8fcd71017d73302f865f
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: validator_management.
final class ValidatorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testValidatorsClear() throws {
        // Clear all validators and verify list is empty
        XCTAssertNoThrow(try Xberg.clearValidators())
    }

    func testValidatorsList() throws {
        // List all registered validators
        let result = try Xberg.listValidators()
        XCTAssertNotNil(result)
    }

}
