// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eca6107bb53cbe2051642ea112e0482c1f69e65406b9aef056c2754f8a8b2348
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
