// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ff8a90707b6574c394b93761334bde0af78807939a4f32842c7aea22dce60463
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import io.xberg.ExtractionConfig
import io.xberg.ExtractInput

/** E2e tests for category: error. */
class ErrorTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testErrorEmptyBytes() = runBlocking {
        // Graceful handling of empty bytes (should not error)
        val input = MAPPER.readValue("{\"bytes\":[],\"config\":{},\"filename\":\"empty.txt\",\"kind\":\"bytes\",\"mime_type\":\"text/plain\"}", ExtractInput::class.java)
        val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, config)
        assertNotNull(result, "expected non-null result")
    }

    @Test
    fun testErrorEmptyMime() = runBlocking {
        // Error when extracting with empty MIME type
        assertFailsWith<Exception> {
            val inputFile0 = java.util.Base64.getEncoder().encodeToString(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("text/plain.txt")))
            val input = MAPPER.readValue("{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"config\":{},\"filename\":\"plain.txt\",\"kind\":\"bytes\",\"mime_type\":\"\"}".replace("__ALEF_DOC_FILE_0__", inputFile0), ExtractInput::class.java)
            val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
            Xberg.extract(input, config)
        }
        Unit
    }

    @Test
    fun testErrorExtractInputConflictingOcr() = runBlocking {
        // extract force+disable OCR
        assertFailsWith<Exception> {
            val inputFile0 = java.util.Base64.getEncoder().encodeToString(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("text/fake_text.txt")))
            val input = MAPPER.readValue("{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"config\":{\"disable_ocr\":true,\"force_ocr\":true},\"filename\":\"fake_text.txt\",\"kind\":\"bytes\",\"mime_type\":\"text/plain\"}".replace("__ALEF_DOC_FILE_0__", inputFile0), ExtractInput::class.java)
            val config = MAPPER.readValue("{\"disable_ocr\":true,\"force_ocr\":true}", ExtractionConfig::class.java)
            Xberg.extract(input, config)
        }
        Unit
    }

    @Test
    fun testErrorInvalidMimeFormat() = runBlocking {
        // Error when extracting with invalid MIME type format
        assertFailsWith<Exception> {
            val inputFile0 = java.util.Base64.getEncoder().encodeToString(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("text/plain.txt")))
            val input = MAPPER.readValue("{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"config\":{},\"filename\":\"plain.txt\",\"kind\":\"bytes\",\"mime_type\":\"not-a-mime\"}".replace("__ALEF_DOC_FILE_0__", inputFile0), ExtractInput::class.java)
            val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
            Xberg.extract(input, config)
        }
        Unit
    }

    @Test
    fun testErrorUnsupportedMime() = runBlocking {
        // Error when extracting with unsupported MIME type
        assertFailsWith<Exception> {
            val inputFile0 = java.util.Base64.getEncoder().encodeToString(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("text/plain.txt")))
            val input = MAPPER.readValue("{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"config\":{},\"filename\":\"plain.txt\",\"kind\":\"bytes\",\"mime_type\":\"application/x-nonexistent\"}".replace("__ALEF_DOC_FILE_0__", inputFile0), ExtractInput::class.java)
            val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
            Xberg.extract(input, config)
        }
        Unit
    }

}
