// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dd9750cd65f9390e5b899310f6d779287c2724fa52799cf8e8ef92573533c143
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import io.xberg.ExtractionConfig
import io.xberg.ExtractInput

/** E2e tests for category: extract. */
class ExtractTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testExtractBytesInput() = runBlocking {
        // extract bytes input from PDF document
        val inputFile0 = java.util.Base64.getEncoder().encodeToString(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("pdf/fake_memo.pdf")))
        val input = MAPPER.readValue("{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"filename\":\"fake_memo.pdf\",\"kind\":\"bytes\",\"mime_type\":\"application/pdf\"}".replace("__ALEF_DOC_FILE_0__", inputFile0), ExtractInput::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
        // not_error: covered by the bare Optional's own assertion
        assertEquals("application/pdf", result.results.first().mimeType)
        assertTrue(result.results.first().content.length >= 50, "expected length >= 50")
    }

    @Test
    fun testExtractBytesInputEmptyMime() = runBlocking {
        // extract bytes input with empty MIME type
        assertFailsWith<Exception> {
            val inputFile0 = java.util.Base64.getEncoder().encodeToString(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("text/plain.txt")))
            val input = MAPPER.readValue("{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"config\":{},\"filename\":\"plain.txt\",\"kind\":\"bytes\",\"mime_type\":\"\"}".replace("__ALEF_DOC_FILE_0__", inputFile0), ExtractInput::class.java)
            val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
            Xberg.extract(input, config)
        }
        Unit
    }

    @Test
    fun testExtractBytesInputInvalidMime() = runBlocking {
        // extract bytes input with unsupported MIME type
        assertFailsWith<Exception> {
            val inputFile0 = java.util.Base64.getEncoder().encodeToString(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("text/plain.txt")))
            val input = MAPPER.readValue("{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"config\":{},\"filename\":\"plain.txt\",\"kind\":\"bytes\",\"mime_type\":\"application/x-nonexistent\"}".replace("__ALEF_DOC_FILE_0__", inputFile0), ExtractInput::class.java)
            val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
            Xberg.extract(input, config)
        }
        Unit
    }

}
