// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cb07cdbed63956e207b56c7eace4cd81fcb05cfa659aac0d2e52ebc001f0f5ad
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import io.xberg.OcrBackendBridge
import io.xberg.IOcrBackend
import io.xberg.*

/** E2e tests for category: ocr_backend_management. */
class OcrBackendManagementTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testOcrBackendsClear() = runBlocking {
        // Clear all OCR backends and verify list is empty
        val result = OcrBackendBridge.clearAll()
        assertNotNull(result, "expected non-null result")
    }

    @Test
    fun testOcrBackendsList() = runBlocking {
        // List all registered OCR backends
        val result = Xberg.listOcrBackends()
        assertNotNull(result, "expected non-null result")
    }

    @Test
    fun testOcrBackendsUnregister() = runBlocking {
        // Unregister nonexistent OCR backend gracefully
        val result = OcrBackendBridge.unregister("nonexistent-backend-xyz")
        assertNotNull(result, "expected non-null result")
    }

}
