// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76edc02b15c252cc33cbe74ffa3644b0d7ff6bb98c0cc92b8dda68e2901529a0
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import io.xberg.RerankerBackendBridge

/** E2e tests for category: reranker_backend_management. */
class RerankerBackendManagementTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testClearRerankerBackends() = runBlocking {
        // Clear all reranker backends and verify list is empty
        val result = RerankerBackendBridge.clearAll()
        assertNotNull(result, "expected non-null result")
    }

    @Test
    fun testListRerankerBackends() = runBlocking {
        // List all registered reranker backends
        val result = Xberg.listRerankerBackends()
        assertNotNull(result, "expected non-null result")
    }

}
