// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:426360a1b7b1cd75ea25326543430a82e30bbc9c8dd05f3ba13dead064a98978
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The meta-schema itself failed to compile.
/// </summary>
public class BadMetaSchemaException : LoadErrorException {
  public BadMetaSchemaException(string message) : base(message) {}

  public BadMetaSchemaException(string message, Exception innerException)
      : base(message, innerException) {}
}
