// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:058c2cd10ea40e0f47ca9dc71f34c065265b2d076d767e765284921c6adea5d9
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Code block fence style in Markdown output.
///
/// Determines how code blocks (`&lt;pre&gt;&lt;code&gt;`) are rendered in
/// Markdown.
/// </summary>
[JsonConverter(typeof(CodeBlockStyleJsonConverter))]
public enum CodeBlockStyle {
  /// <summary>
  /// Indented code blocks (4 spaces). `CommonMark` standard.
  /// </summary>
  [JsonPropertyName("Indented")] Indented,
  /// <summary>
  /// Fenced code blocks with triple backticks. Default (GFM). Supports language
  /// hints.
  /// </summary>
  [JsonPropertyName("Backticks")] Backticks,
  /// <summary>
  /// Fenced code blocks with tildes (~~~). Supports language hints.
  /// </summary>
  [JsonPropertyName("Tildes")] Tildes,
}

/// <summary>
/// Custom JSON converter for <see cref="CodeBlockStyle"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class CodeBlockStyleJsonConverter
    : JsonConverter<CodeBlockStyle> {
  public override CodeBlockStyle Read(ref Utf8JsonReader reader,
                                      Type typeToConvert,
                                      JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch { "Indented" => CodeBlockStyle.Indented,
                          "Backticks" => CodeBlockStyle.Backticks,
                          "Tildes" => CodeBlockStyle.Tildes,
                          _ => throw new JsonException(
                              $"Unknown CodeBlockStyle value: {value}") };
  }

  public override void Write(Utf8JsonWriter writer, CodeBlockStyle value,
                             JsonSerializerOptions options) {
    var str = value switch { CodeBlockStyle.Indented => "Indented",
                             CodeBlockStyle.Backticks => "Backticks",
                             CodeBlockStyle.Tildes => "Tildes",
                             _ => throw new JsonException(
                                 $"Unknown CodeBlockStyle value: {value}") };
    writer.WriteStringValue(str);
  }
}
