// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c7b139a5c42f1cd3dff8e0914c3f8b8499eb41d2617391686270363d2d405ca6
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration value.
/// </summary>
public class ConfigErrorException : HeuristicsErrorException {
  public ConfigErrorException(string message) : base(message) {}

  public ConfigErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
