// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:293ffb54206ce2b23332b02fa86a2074af91f218c2296f3516d22db494da3d1d
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException {
  public DeserializeException(string message) : base(message) {}

  public DeserializeException(string message, Exception innerException)
      : base(message, innerException) {}
}
