// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:dbab69388194c5b081ee01e7348d0e2d65ba4eb50c69c51d3b655b9f1af7e76a
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException {
  public EmbeddingException(string message) : base(message) {}

  public EmbeddingException(string message, Exception innerException)
      : base(message, innerException) {}
}
