// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c00f498f0157295787d5e2c79fe1ba9df2af5e745dc53a2d2b9d4e84c6fc1d30
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Error metadata (for batch operations).
/// </summary>
public sealed record ErrorMetadata {
  /// <summary>
  /// Machine-readable error type identifier (e.g. "UnsupportedFormat").
  /// </summary>
  [JsonPropertyName("error_type")]
  public required string ErrorType { get; init; }

  /// <summary>
  /// Human-readable error description.
  /// </summary>
  [JsonPropertyName("message")]
  public required string Message {
    get; init;
  }

  /// <summary>
  /// Parse a <see cref="ErrorMetadata"/> from a JSON string.
  /// </summary>
  /// <exception cref="XbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static ErrorMetadata FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<ErrorMetadata>(json, JsonOptions) ??
             throw new XbergException(
                 $"Failed to parse ErrorMetadata from JSON: deserializer returned null");
    } catch (XbergException) {
      throw;
    } catch (Exception e) {
      throw new XbergException(
          $"Failed to parse ErrorMetadata from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };
}
