// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6259db536cb86f1747cda9f83decbe30dd6c49c60b2057b6f157847280cdca1f
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Formula recognition model selection.
/// </summary>
[JsonConverter(typeof(FormulaModelJsonConverter))]
public enum FormulaModel {
  /// <summary>
  /// RapidLaTeXOCR (MIT, pix2tex-derived): resizer + encoder + decoder ONNX,
  /// ~180 MB total, downloaded on demand.
  /// </summary>
  [JsonPropertyName("latex_ocr")] LatexOcr,
}

/// <summary>
/// Custom JSON converter for <see cref="FormulaModel"/> that respects explicit
/// variant names.
/// </summary>
internal sealed class FormulaModelJsonConverter : JsonConverter<FormulaModel> {
  public override FormulaModel Read(ref Utf8JsonReader reader,
                                    Type typeToConvert,
                                    JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch { "latex_ocr" => FormulaModel.LatexOcr,
                          _ => throw new JsonException(
                              $"Unknown FormulaModel value: {value}") };
  }

  public override void Write(Utf8JsonWriter writer, FormulaModel value,
                             JsonSerializerOptions options) {
    var str = value switch { FormulaModel.LatexOcr => "latex_ocr",
                             _ => throw new JsonException(
                                 $"Unknown FormulaModel value: {value}") };
    writer.WriteStringValue(str);
  }
}
