// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:dca0c7bb0dd3b0223f9486e2175d77c6444d212efda91981bd184df2d2eba25c
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The preset's declared `id` does not match its file-system location.
/// </summary>
public class IdMismatchException : LoadErrorException {
  public IdMismatchException(string message) : base(message) {}

  public IdMismatchException(string message, Exception innerException)
      : base(message, innerException) {}
}
