// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6a3b6ce2d515e4e81469a40e5a4f03b830e43ae004a0f9ec222961a897baa282
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An image manipulation operation (resize, decode, DPI conversion) failed.
/// </summary>
public class ImageProcessingException : XbergErrorException {
  public ImageProcessingException(string message) : base(message) {}

  public ImageProcessingException(string message, Exception innerException)
      : base(message, innerException) {}
}
