// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:300f6681f7d69eec61db56614f15c2bcfd71c2e130694c68b6ad7581b8b2de7f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A filesystem I/O error occurred while reading a preset directory.
/// </summary>
public class IoException : LoadErrorException {
  public IoException(string message) : base(message) {}

  public IoException(string message, Exception innerException)
      : base(message, innerException) {}
}
