// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c97cdfd86ceba1d640e4ac37b5f31ee890605c48341b6f22b8d31c25a142f2e1
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// A string key-value attribute.
/// </summary>
public sealed record KeyValueAttribute {
  /// <summary>
  /// Attribute name.
  /// </summary>
  [JsonPropertyName("key")]
  public string Key { get; init; } = "";

  /// <summary>
  /// Attribute value.
  /// </summary>
  [JsonPropertyName("value")]
  public string Value {
    get; init;
  } = "";

  /// <summary>
  /// Parse a <see cref="KeyValueAttribute"/> from a JSON string.
  /// </summary>
  /// <exception cref="XbergException">When the JSON cannot be
  /// deserialised.</exception>
  public static KeyValueAttribute FromJson(string json) {
    try {
      return JsonSerializer.Deserialize<KeyValueAttribute>(json, JsonOptions) ??
             throw new XbergException(
                 $"Failed to parse KeyValueAttribute from JSON: deserializer returned null");
    } catch (XbergException) {
      throw;
    } catch (Exception e) {
      throw new XbergException(
          $"Failed to parse KeyValueAttribute from JSON: {e.Message}", e);
    }
  }

  private static readonly JsonSerializerOptions JsonOptions = new() {
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower),
                   new ByteArrayJsonConverter() },
  };

  /// <summary>Options for serializing config/input objects to FFI. Strips nulls
  /// (nullable C# fields default to null and would override required Rust
  /// fields with non-deserialisable nulls) but preserves explicit false/0 so
  /// caller intent is kept.</summary>
  private static readonly JsonSerializerOptions JsonSerializationOptions =
      new() {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(
                           JsonNamingPolicy.SnakeCaseLower),
                       new ByteArrayJsonConverter() },
      };
}
