// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7205e98250b0ae00eabee40baec97952fb3b3524aa07e9fbd30c8b93ac341e39
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while loading or validating a preset file.
/// </summary>
public class LoadErrorException : XbergException {
  public LoadErrorException(string message) : base(message) {}

  public LoadErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
