// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c54b98ac7eb2cb1a7419961da17292aca64682a3eed53b88e964313a6872d043
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : XbergErrorException {
  public LockPoisonedException(string message) : base(message) {}

  public LockPoisonedException(string message, Exception innerException)
      : base(message, innerException) {}
}
