// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b27cc29e6d4adbc51702395e64275568edfd98fa08c79069a35b671047d6be7f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A required optional system dependency (e.g. `tesseract`) was not found.
/// </summary>
public class MissingDependencyException : XbergErrorException {
  public MissingDependencyException(string message) : base(message) {}

  public MissingDependencyException(string message, Exception innerException)
      : base(message, innerException) {}
}
