// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7801c9b90670e798a2127197b823cf3cb8feb16c12c2a68a949419e8bd09c6b5
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : XbergErrorException {
  public OcrException(string message) : base(message) {}

  public OcrException(string message, Exception innerException)
      : base(message, innerException) {}
}
