// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f111e2af9c1d906390decdd5ace85049688acad9f084f6c333b31c37b2bc17a6
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A catch-all for uncommon errors that do not fit another variant.
/// </summary>
public class OtherException : XbergErrorException {
  public OtherException(string message) : base(message) {}

  public OtherException(string message, Exception innerException)
      : base(message, innerException) {}
}
