// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c6599c18c3a738c05f903beebbc524582090372dfb53e73b4f4b03cdb743320d
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file is not valid JSON.
/// </summary>
public class ParseException : LoadErrorException {
  public ParseException(string message) : base(message) {}

  public ParseException(string message, Exception innerException)
      : base(message, innerException) {}
}
