// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6242ff3126234702548e9617f13a6cf282dbfbc5bc6dfb2161a772c0f01ef075
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Document parsing failed (e.g. corrupt file, unsupported format feature).
/// </summary>
public class ParsingException : XbergErrorException {
  public ParsingException(string message) : base(message) {}

  public ParsingException(string message, Exception innerException)
      : base(message, innerException) {}
}
