// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6dc48127e24dc504fda82f1fdf5e41851af141f98056229505cfdf2d6d221497
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException {
  public PdfAnalysisErrorException(string message) : base(message) {}

  public PdfAnalysisErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
