// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a4ef0953c59b7699df80ef3b15c75fa323f6baa8fb82dde5e53f8ca228f6c81c
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException {
  public PluginException(string message) : base(message) {}

  public PluginException(string message, Exception innerException)
      : base(message, innerException) {}
}
