// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:548b5f6317db2bba9975625282592770b7b3f7964bf937ec874ce031ebda3ec3
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException {
  public ResolveErrorException(string message) : base(message) {}

  public ResolveErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
