// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:336328e5e2ae86874ca096b1aaac5969f1009cd6cad6bd2806dec07e1c7908c3
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException {
  public SchemaValidationException(string message) : base(message) {}

  public SchemaValidationException(string message, Exception innerException)
      : base(message, innerException) {}
}
