// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9ad0a6ec1ee49e27dbb9fc4584763909caf198c0ab3509d9eadba6832d8e83b8
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : XbergErrorException {
  public SecurityException(string message) : base(message) {}

  public SecurityException(string message, Exception innerException)
      : base(message, innerException) {}
}
