// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c1bf3adf11ebade48faad70bc6ca66ea3edc839c8d5f1ed91154ceb34794c61f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : XbergErrorException {
  public SerializationException(string message) : base(message) {}

  public SerializationException(string message, Exception innerException)
      : base(message, innerException) {}
}
