// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:49956b85b2761cb135ca108f63c5d57ec57a6fa365f85c8e524c83b8d5628a44
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction operation exceeded the configured time limit.
/// </summary>
public class TimeoutException : XbergErrorException {
  public TimeoutException(string message) : base(message) {}

  public TimeoutException(string message, Exception innerException)
      : base(message, innerException) {}
}
