// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f22a51a1d97f3fb884134db7d8d2fa7d2754a5de069b2102e42bb8fb551735fe
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The document's MIME type is not supported by any registered extractor.
/// </summary>
public class UnsupportedFormatException : XbergErrorException {
  public UnsupportedFormatException(string message) : base(message) {}

  public UnsupportedFormatException(string message, Exception innerException)
      : base(message, innerException) {}
}
