// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8f5e40c69ca4efc81819cd5fd4622b067bed3b7e04414967a474362d70e74da1
#nullable enable

using System;

namespace Xberg;

public class XbergException : Exception {
  public int Code { get; }

  public XbergException(int code, string message) : base(message) {
    Code = code;
  }

  public XbergException(string message) : base(message) { Code = 0; }

  public XbergException(string message, Exception innerException)
      : base(message, innerException) {
    Code = 0;
  }
}
