// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8272b8d8087da548e8be595f9ab55b0068b0315e6a866cbc5ee192f4bdf1996
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: embedding_backend_management

test "embedding_backends_clear" {
    // Clear all embedding backends and verify list is empty
    allow_private_network();
    _ = try xberg.clear_embedding_backends();
}

test "embedding_backends_list" {
    // List all registered embedding backends
    allow_private_network();
    _ = try xberg.list_embedding_backends();
}
