// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:77ba574b44775b14700c1386aaef9eea9e6a1870f4f2dbd1532c2a87fefa435f
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: registry

test "list_embedding_backends" {
    // List embedding backends
    allow_private_network();
    _ = try xberg.list_embedding_backends();
}

test "list_ocr_backends" {
    // List OCR backends
    allow_private_network();
    _ = try xberg.list_ocr_backends();
}

test "list_post_processors" {
    // List post-processors
    allow_private_network();
    _ = try xberg.list_post_processors();
}

test "list_renderers" {
    // List renderers
    allow_private_network();
    _ = try xberg.list_renderers();
}

test "list_validators" {
    // List validators
    allow_private_network();
    _ = try xberg.list_validators();
}
