// Generated by alef. Do not edit by hand.
// alef:hash:533b58b47e52749f73877ecf84489c29843fe20c8af98c34d74fed2aa125aecb
// swift-format-ignore-file
// This file contains generated FFI glue for trait bridge registration.

import Foundation
import RustBridge

/// Protocol for outbound `PostProcessor` implementations.
/// Conform your Swift class or struct to this protocol to implement
/// a Rust trait from the host side.
/// Implementations may be invoked concurrently and must synchronize mutable state.
public protocol SwiftPostProcessorBridge: SwiftPluginBridge {
    func process(result: String, config: String) throws -> Void
    func processingStage() -> String
    /// The Rust trait declares a default body for this method. alef does not carry that body in
    /// its IR and cannot reproduce it, so this conformance is required rather than defaulted:
    /// supply the same value the Rust default would have produced.
    func shouldProcess(result: String, config: String) -> Bool
    /// The Rust trait declares a default body for this method. alef does not carry that body in
    /// its IR and cannot reproduce it, so this conformance is required rather than defaulted:
    /// supply the same value the Rust default would have produced.
    func estimatedDurationMs(result: String) -> UInt64
    /// The Rust trait declares a default body for this method. alef does not carry that body in
    /// its IR and cannot reproduce it, so this conformance is required rather than defaulted:
    /// supply the same value the Rust default would have produced.
    func priority() -> Int32
}

/// Internal adapter wrapping a `SwiftPostProcessorBridge` conformer.
/// Wraps a user-supplied bridge and forwards calls through marshalling entry points.
final class SwiftPostProcessorAdapter {
    private let bridge: any SwiftPostProcessorBridge

    init(bridge: any SwiftPostProcessorBridge) {
        self.bridge = bridge
    }

    // MARK: - SwiftPluginBridge lifecycle

    var name: String {
        return bridge.name
    }

    func version() -> String {
        return bridge.version()
    }

    func initialize() throws {
        try bridge.initialize()
    }

    func shutdown() throws {
        try bridge.shutdown()
    }

    // MARK: - FFI marshalling entry points

    func processCall(result: String, config: String) throws -> String {
        do {
            let result = try self.bridge.process(result: result, config: config)
            return marshal_ok_result(Empty())
        } catch {
            return marshal_error_result(error)
        }
    }
    func processingStageCall() -> String {
        let result = self.bridge.processingStage()
        return result
    }
    func shouldProcessCall(result: String, config: String) -> Bool {
        let result = self.bridge.shouldProcess(result: result, config: config)
        return result
    }
    func estimatedDurationMsCall(result: String) -> UInt64 {
        let result = self.bridge.estimatedDurationMs(result: result)
        return result
    }
    func priorityCall() -> Int32 {
        let result = self.bridge.priority()
        return result
    }

}

// MARK: - Marshalling helpers

private struct Empty: Codable {}

private func marshal_ok_result<T: Encodable>(_ value: T) -> String {
    let encoder = JSONEncoder()
    if let data = try? encoder.encode(value),
       let jsonString = String(data: data, encoding: .utf8) {
        return "{\"ok\": \(jsonString)}"
    }
    return "{\"ok\": null}"
}

private func marshal_encode_excluded<T: Encodable>(_ value: T) throws -> Data {
    let encoder = JSONEncoder()
    return try encoder.encode(value)
}

private func marshal_error_result(_ error: any Error) -> String {
    let errorString = String(describing: error)
    let encoder = JSONEncoder()
    if let data = try? encoder.encode(errorString),
       let jsonString = String(data: data, encoding: .utf8) {
        return "{\"err\": \(jsonString)}"
    }
    return "{\"err\": \"unknown error\"}"
}
