// Generated by alef. Do not edit by hand.
// alef:hash:9c0af73652463808355ef1953173f920b35925a142d18b4d52b1b263ee445ed2
// swift-format-ignore-file
// This file contains generated FFI glue for trait bridge registration.

import Foundation
import RustBridge

/// Protocol for outbound `Validator` implementations.
/// Conform your Swift class or struct to this protocol to implement
/// a Rust trait from the host side.
/// Implementations may be invoked concurrently and must synchronize mutable state.
public protocol SwiftValidatorBridge: SwiftPluginBridge {
    func validate(result: String, config: String) throws -> Void
    /// The Rust trait declares a default body for this method. alef does not carry that body in
    /// its IR and cannot reproduce it, so this conformance is required rather than defaulted:
    /// supply the same value the Rust default would have produced.
    func shouldValidate(result: String, config: String) -> Bool
    /// The Rust trait declares a default body for this method. alef does not carry that body in
    /// its IR and cannot reproduce it, so this conformance is required rather than defaulted:
    /// supply the same value the Rust default would have produced.
    func priority() -> Int32
}

/// Internal adapter wrapping a `SwiftValidatorBridge` conformer.
/// Wraps a user-supplied bridge and forwards calls through marshalling entry points.
final class SwiftValidatorAdapter {
    private let bridge: any SwiftValidatorBridge

    init(bridge: any SwiftValidatorBridge) {
        self.bridge = bridge
    }

    // MARK: - SwiftPluginBridge lifecycle

    var name: String {
        return bridge.name
    }

    func version() -> String {
        return bridge.version()
    }

    func initialize() throws {
        try bridge.initialize()
    }

    func shutdown() throws {
        try bridge.shutdown()
    }

    // MARK: - FFI marshalling entry points

    func validateCall(result: String, config: String) throws -> String {
        do {
            let result = try self.bridge.validate(result: result, config: config)
            return marshal_ok_result(Empty())
        } catch {
            return marshal_error_result(error)
        }
    }
    func shouldValidateCall(result: String, config: String) -> Bool {
        let result = self.bridge.shouldValidate(result: result, config: config)
        return result
    }
    func priorityCall() -> Int32 {
        let result = self.bridge.priority()
        return result
    }

}

// MARK: - Marshalling helpers

private struct Empty: Codable {}

private func marshal_ok_result<T: Encodable>(_ value: T) -> String {
    let encoder = JSONEncoder()
    if let data = try? encoder.encode(value),
       let jsonString = String(data: data, encoding: .utf8) {
        return "{\"ok\": \(jsonString)}"
    }
    return "{\"ok\": null}"
}

private func marshal_encode_excluded<T: Encodable>(_ value: T) throws -> Data {
    let encoder = JSONEncoder()
    return try encoder.encode(value)
}

private func marshal_error_result(_ error: any Error) -> String {
    let errorString = String(describing: error)
    let encoder = JSONEncoder()
    if let data = try? encoder.encode(errorString),
       let jsonString = String(data: data, encoding: .utf8) {
        return "{\"err\": \(jsonString)}"
    }
    return "{\"err\": \"unknown error\"}"
}
