# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:74c83fd4d7690ac138a3ff65fc6605b4e706c15c7f30da6479cd869f146ef5c6
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: post_processor_management."""

import pytest  # noqa: F401
from xberg import clear_post_processors, list_post_processors


def test_post_processors_clear() -> None:
    """Clear all post-processors and verify list is empty."""
    clear_post_processors()


def test_post_processors_list() -> None:
    """List all registered post-processors."""
    result = list_post_processors()
    assert result is not None
