# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3f787cceba224540ff713a0f425b408e67bb4ab960ef0a8cc8195fcc9798f3d9
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: reranker_backend_management."""

import pytest  # noqa: F401
from xberg import clear_reranker_backends, list_reranker_backends


def test_clear_reranker_backends() -> None:
    """Clear all reranker backends and verify list is empty."""
    clear_reranker_backends()


def test_list_reranker_backends() -> None:
    """List all registered reranker backends."""
    result = list_reranker_backends()
    assert result is not None
