# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:07b9e74d704c85a7f6028e87f82465df6f65216c8d33c304c2356bb070d689c1
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: renderer_management."""

import pytest  # noqa: F401
from xberg import clear_renderers, list_renderers


def test_renderers_clear() -> None:
    """Clear all renderers and verify list is empty."""
    clear_renderers()


def test_renderers_list() -> None:
    """List all registered renderers."""
    result = list_renderers()
    assert result is not None
