# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eddd914655aff8758cfcfb44f2091f9c0f8da539a4f45f868675e53c7a5a220b
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: ocr_backend_management."""

import pytest  # noqa: F401
from xberg import clear_ocr_backends, list_ocr_backends, unregister_ocr_backend


def test_ocr_backends_clear() -> None:
    """Clear all OCR backends and verify list is empty."""
    clear_ocr_backends()


def test_ocr_backends_list() -> None:
    """List all registered OCR backends."""
    result = list_ocr_backends()
    assert result is not None


def test_ocr_backends_unregister() -> None:
    """Unregister nonexistent OCR backend gracefully."""
    name = "nonexistent-backend-xyz"

    unregister_ocr_backend(name)
