# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56ecfdd7c54f415ffc56c4329308cfcd465aff7691f0f8019e58962a6ebfd48c
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: tokenizer_backend_management."""

import pytest  # noqa: F401
from xberg import clear_tokenizer_backends, list_tokenizer_backends


def test_tokenizer_backends_clear() -> None:
    """Clear all tokenizer backends and verify list is empty."""
    clear_tokenizer_backends()


def test_tokenizer_backends_list() -> None:
    """List all registered tokenizer backends."""
    result = list_tokenizer_backends()
    assert result is not None
