# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11e1474b66206379569eaa01967cc426d5122bae2ed8fec6c65bf81e98a318c1
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: embedding_backend_management."""

import pytest  # noqa: F401
from xberg import clear_embedding_backends, list_embedding_backends


def test_embedding_backends_clear() -> None:
    """Clear all embedding backends and verify list is empty."""
    clear_embedding_backends()


def test_embedding_backends_list() -> None:
    """List all registered embedding backends."""
    result = list_embedding_backends()
    assert result is not None
