// Generated by alef. Do not edit by hand.
// alef:hash:f22f4d153f96caf62fd1c98a685771261ecfa5aadb9f2fd57ab818cf02bc0e95

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "xberg-android"
