// Generated by alef. Do not edit by hand.
// alef:hash:d9e22c6acaffec72afc6e68b9aa07f8ffbcc96b293b66769d6a7248dbb08b989
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Controls thread usage for constrained environments.
 *
 * Set `max_threads` to cap all internal thread pools (Rayon, ONNX Runtime
 * intra-op) and batch concurrency to a single limit.
 *
 * # Default budget when `max_threads` is unset
 *
 * Without an explicit `max_threads`, the effective budget is
 * `min(detected_cpu_cores, 8)` — a deliberate ceiling chosen for
 * serverless/shared-tenant defaults, not a full-host auto-scale. On a host
 * with more than 8 cores this means the extra cores go **unused** unless one
 * of the following applies:
 *
 * - `max_threads` is set explicitly above 8 (the only way to exceed the
 *   ceiling on a bare-metal or VM host with no CPU quota).
 *
 * - The process runs under a Linux cgroup CPU quota (containers, Kubernetes
 *   `resources.limits.cpu`); in that case the quota itself is used as the
 *   ceiling instead of the hardcoded 8, since the quota already reflects a
 *   deliberately-configured resource limit.
 *
 * When neither applies and the host has more than 8 cores, a single
 * `WARN`-level log is emitted the first time the budget is resolved,
 * naming the detected core count and the applied cap, so the ceiling is
 * discoverable without reading source.
 */
data class ConcurrencyConfig(
    /**
     * Maximum number of threads for all internal thread pools.
     *
     * Caps Rayon global pool size, ONNX Runtime intra-op threads, and the
     * combined document/inner-task budget for batch extraction. When `null`,
     * the effective budget is `min(detected_cpu_cores, 8)` unless a Linux
     * cgroup CPU quota is present, in which case the quota is used as the
     * ceiling instead. On hosts with more than 8 cores and no cgroup quota,
     * set `max_threads` explicitly to use the additional cores — the
     * default will not scale past 8 on its own.
     */
    val maxThreads: Long? = null,
)
