// Generated by alef. Do not edit by hand.
// alef:hash:febf8b6a2d83afd6cdfb61a7cbdca79e9110a9144be645b114514f4780d53091
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * How a backend's reported page-level confidence must be interpreted.
 *
 * Backend confidence scores are not interchangeable. Tesseract's mean word confidence is a
 * classifier score validated to track legibility on a 0-100 scale. Sceptre (EasyOCR-based)
 * reports a length-penalised `custom_mean` that is rescaled into the same 0-100 range but is
 * *not* comparable — its ordering can be inverted relative to legibility (a dense prose page
 * can score lower than a nearly-blank one). A page-rejection gate calibrated on Tesseract's
 * scale was once applied unconditionally to sceptre's output and rejected every page of a
 * 16-page document, emptying it. This descriptor exists so gating code can ask a backend what
 * its number means instead of assuming.
 */
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = ConfidenceSemanticsDeserializer::class)
@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = ConfidenceSemanticsSerializer::class)
sealed class ConfidenceSemantics {
    /** Validated to track legibility on a known scale — usable as an absolute quality gate. */
    @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.fasterxml.jackson.databind.JsonDeserializer.None::class)
    @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = com.fasterxml.jackson.databind.JsonSerializer.None::class)
    data class Legibility(
        val scaleMax: Double,
    ) : ConfidenceSemantics()
    /**
     * A number is reported, but it is not validated to correlate with legibility.
     * Never gate on it.
     */
    object Uncalibrated : ConfidenceSemantics()
    /** No page-level confidence is reported at all. */
    object None : ConfidenceSemantics()
}

private class ConfidenceSemanticsDeserializer : com.fasterxml.jackson.databind.deser.std.StdDeserializer<ConfidenceSemantics>(ConfidenceSemantics::class.java) {
    @Suppress("LongMethod", "CyclomaticComplexMethod", "ReturnCount")
    override fun deserialize(
        parser: com.fasterxml.jackson.core.JsonParser,
        ctx: com.fasterxml.jackson.databind.DeserializationContext,
    ): ConfidenceSemantics {
        val node = parser.codec.readTree<com.fasterxml.jackson.databind.JsonNode>(parser)
        if (node.isTextual) {
            return when (node.asText()) {
                "Uncalibrated" -> ConfidenceSemantics.Uncalibrated
                "None" -> ConfidenceSemantics.None
                else -> throw com.fasterxml.jackson.databind.exc.InvalidFormatException(
                    parser, "Unknown ConfidenceSemantics unit variant", node.asText(), ConfidenceSemantics::class.java,
                )
            }
        }
        if (node.isObject) {
            val obj = node as com.fasterxml.jackson.databind.node.ObjectNode
            val it = obj.fields()
            if (it.hasNext()) {
                val entry = it.next()
                if (!it.hasNext()) {
                    val payload = entry.value
                    return when (entry.key) {
                        "Legibility" -> ctx.readTreeAsValue<ConfidenceSemantics.Legibility>(payload, ConfidenceSemantics.Legibility::class.java)
                        else -> throw com.fasterxml.jackson.databind.exc.InvalidFormatException(
                            parser, "Unknown ConfidenceSemantics data variant", entry.key, ConfidenceSemantics::class.java,
                        )
                    }
                }
            }
        }
        throw com.fasterxml.jackson.databind.exc.InvalidFormatException(
            parser, "Cannot deserialize ConfidenceSemantics: expected string or single-field object", null, ConfidenceSemantics::class.java,
        )
    }
}

private class ConfidenceSemanticsSerializer : com.fasterxml.jackson.databind.ser.std.StdSerializer<ConfidenceSemantics>(ConfidenceSemantics::class.java) {
    @Suppress("LongMethod")
    override fun serialize(
        value: ConfidenceSemantics,
        gen: com.fasterxml.jackson.core.JsonGenerator,
        provider: com.fasterxml.jackson.databind.SerializerProvider,
    ) {
        @Suppress("UNCHECKED_CAST")
        val mapper = (gen.codec as? com.fasterxml.jackson.databind.ObjectMapper) ?: com.fasterxml.jackson.databind.ObjectMapper().findAndRegisterModules()
        when (value) {
            is ConfidenceSemantics.Legibility -> {
                gen.writeStartObject()
                gen.writeFieldName("Legibility")
                mapper.writeValue(gen, value as ConfidenceSemantics.Legibility)
                gen.writeEndObject()
            }
            is ConfidenceSemantics.Uncalibrated -> gen.writeString("Uncalibrated")
            is ConfidenceSemantics.None -> gen.writeString("None")
        }
    }
}
