// Generated by alef. Do not edit by hand.
// alef:hash:147d1a9656a5420cb5a93f54d11db1c7c226b28461952b39ee74852a25471c99
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Non-fatal per-input extraction error captured by `ExtractionResult`. */
data class ExtractionErrorItem(
    /** Input index in the original request. */
    val index: Long,
    /** Stable numeric error code. */
    val code: Int,
    /** Stable snake_case error kind. */
    val errorType: String,
    /** Best-effort source identifier. */
    val source: String,
    /** Error message. */
    val message: String,
)
