// Generated by alef. Do not edit by hand.
// alef:hash:9301b7554532f56a4078577e6c0bdc71fd8e4f6ded30a80f41eb02ec28c58f35
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

data class HierarchicalBlock(
    /** The text content of this block */
    val text: String,
    /** The font size of the text in this block */
    val fontSize: Float,
    /**
     * The hierarchy level of this block (H1-H6 or Body)
     *
     * Levels correspond to HTML heading tags:
     *
     * - "h1": Top-level heading
     * - "h2": Secondary heading
     * - "h3": Tertiary heading
     * - "h4": Quaternary heading
     * - "h5": Quinary heading
     * - "h6": Senary heading
     * - "body": Body text (no heading level)
     */
    val level: String,
    /**
     * Bounding box information for the block
     *
     * Contains left, top, right, and bottom coordinates in PDF units.
     */
    val bbox: HierarchicalBoundingBox? = null,
)
