// Generated by alef. Do not edit by hand.
// alef:hash:2bf26374b18d3964b52bd36249eb69bfa73fc7f55b5233cc5d20d603d24731d9
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Quality thresholds for OCR fallback decisions and pipeline quality gating.
 *
 * All fields default to the values that match the previous hardcoded behavior,
 * so `OcrQualityThresholds.default()` preserves existing semantics exactly.
 */
data class OcrQualityThresholds(
    /** Minimum total non-whitespace characters to consider text substantive. */
    val minTotalNonWhitespace: Long = 64L,
    /** Minimum non-whitespace characters per page on average. */
    val minNonWhitespacePerPage: Double = 32.0,
    /** Minimum character count for a word to be "meaningful". */
    val minMeaningfulWordLen: Long = 4L,
    /** Minimum count of meaningful words before text is accepted. */
    val minMeaningfulWords: Long = 3L,
    /** Minimum alphanumeric ratio (non-whitespace chars that are alphanumeric). */
    val minAlnumRatio: Double = 0.3,
    /** Minimum Unicode replacement characters (U+FFFD) to trigger OCR fallback. */
    val minGarbageChars: Long = 5L,
    /** Maximum fraction of short (1-2 char) words before text is considered fragmented. */
    val maxFragmentedWordRatio: Double = 0.6,
    /**
     * Critical fragmentation threshold — triggers OCR regardless of meaningful words.
     * Normal English text has ~20-30% short words. 80%+ is definitive garbage.
     */
    val criticalFragmentedWordRatio: Double = 0.8,
    /**
     * Maximum fraction of short (1-2 char) words an *OCR result* may carry before the page
     * is rejected as recognition noise rather than accepted as content.
     *
     * This is a different decision, and a different operating point, from
     * `Self.max_fragmented_word_ratio` / `Self.critical_fragmented_word_ratio`: those
     * ask "is the native text bad enough that we should OCR this page?", and are tuned to
     * only fire on text that is already definitively broken (0.6 / 0.8). Here we are judging
     * what OCR *produced*, where the failure mode is an engine run over line art — a scanned
     * plat, an engineering drawing, a signature flourish — returning confident-looking
     * strings that are not words.
     *
     * Measured over the 16 pages of a recorded municipal ordinance (13 prose pages, 3 scanned
     * survey drawings): prose ran 0.04-0.28, the drawings 0.42-0.47. The default sits in that
     * gap with margin on both sides. Raise it to keep more marginal text, lower it to be
     * stricter — but note the cost is asymmetric, since a false positive deletes real content
     * while a false negative only leaves noise in place.
     */
    val maxOcrOutputFragmentedWordRatio: Double,
    /**
     * Minimum mean OCR confidence (0-100) a page must reach for its text to be accepted.
     *
     * This is the engine's own uncertainty about what it read, and it is a far sharper
     * instrument than any statistic derived from the output text. Measured per page over a
     * recorded municipal ordinance (10 prose pages, 6 scanned survey/architectural drawings)
     * with Tesseract 5.5.3:
     *
     *     prose      86.3 - 95.3
     *     drawings   18.5 - 64.3
     *
     * The default sits in that gap with ~11 points of margin on each side. Compare the
     * short-word ratio, which separated the same two groups by 0.09 on a 0-1 scale.
     *
     * A backend that reports no confidence (no `mean_text_conf` in its result metadata)
     * skips this check entirely and falls back to
     * `Self.max_ocr_output_fragmented_word_ratio`. Set to 0.0 to disable.
     */
    val minOcrMeanConfidence: Double,
    /**
     * Minimum word count before `Self.max_ocr_output_fragmented_word_ratio` may reject a
     * page. Short pages (a signature block, an exhibit title) are legitimately dominated by
     * short words, so the ratio is not meaningful on them and the veto stays disabled.
     */
    val minWordsForOcrOutputCheck: Long,
    /**
     * Maximum fraction of a Tesseract page's dictionary-checkable words that
     * `TesseractAPI.is_valid_word` may reject before the page is treated as recognition
     * noise, supplementing (never replacing) `Self.max_ocr_output_fragmented_word_ratio`.
     *
     * Tesseract-only: other backends never report this ratio (see
     * `dictionary_invalid_word_ratio` in `ocr.processor.execution`), so this threshold is
     * simply never consulted for them.
     *
     * Calibration owed, same as `ocr.types.TesseractConfig.min_confidence`:
     * unlike `Self.max_ocr_output_fragmented_word_ratio` (measured across a recorded
     * ordinance's prose vs. drawing pages), this ratio has not yet had a page-level
     * measurement run over a labeled corpus. The default therefore disables the check
     * entirely (`1.01`, above the `[0.0, 1.0]` range a ratio can reach) rather than guess an
     * operating point. Do not lower this without running that measurement first — the cost
     * of a wrong threshold here is the same as for the fragmented-word-ratio veto: a false
     * positive deletes real content, a false negative only leaves noise in place.
     */
    val maxOcrOutputDictInvalidWordRatio: Double,
    /** Minimum average word length. Below this with enough words indicates garbled extraction. */
    val minAvgWordLength: Double = 2.0,
    /** Minimum word count before average word length check applies. */
    val minWordsForAvgLengthCheck: Long = 50L,
    /** Minimum consecutive word repetition ratio to detect column scrambling. */
    val minConsecutiveRepeatRatio: Double = 0.08,
    /** Minimum word count before consecutive repetition check is applied. */
    val minWordsForRepeatCheck: Long = 50L,
    /** Minimum character count for "substantive markdown" OCR skip gate. */
    val substantiveMinChars: Long = 100L,
    /** Minimum character count for "non-text content" OCR skip gate. */
    val nonTextMinChars: Long = 20L,
    /** Alphanumeric+whitespace ratio threshold for skip decisions. */
    val alnumWsRatioThreshold: Double = 0.4,
    /**
     * Minimum quality score (0.0-1.0) for a pipeline stage result to be accepted.
     * If the result from a backend scores below this, try the next backend.
     */
    val pipelineMinQuality: Double = 0.5,
    /**
     * Minimum fraction of non-whitespace characters that are undecodable
     * (Unicode Private Use Area, replacement characters, or non-whitespace
     * control characters) before a page's text layer is treated as
     * unreadable and routed to OCR (issue #1254). Gated by
     * `min_total_non_whitespace` so short snippets with a stray symbol or
     * two do not trip this check.
     */
    val minUndecodableRatio: Double,
    /**
     * Whether to route a page to OCR when xberg_native_pdf reports that a high
     * fraction of its text was fabricated rather than read from the file
     * (`MappingProvenance.Fallback`, xberg_native_pdf 0.3.75+, issue #1254). This is
     * a direct fact from the extractor's ISO 32000-1 §9.10.2 mapping cascade,
     * distinct from the character-heuristic proxy behind `min_undecodable_ratio`.
     * Defaults to `true`.
     */
    val enableProvenanceOcrRouting: Boolean,
    /**
     * Minimum fraction of a page's non-whitespace characters with
     * `MappingProvenance.Fallback` provenance before the page is treated as
     * having a fabricated text layer and routed to OCR (issue #1254). Gated by
     * `min_total_non_whitespace` so a short page with a stray fallback
     * character cannot trip it. Only used when `enable_provenance_ocr_routing`
     * is `true`.
     */
    val minProvenanceFallbackRatio: Double,
)
