// Generated by alef. Do not edit by hand.
// alef:hash:84e638f918e2742e24e7a978f329f52c3027718a194665a5811c4dee69c7a454
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** HTML preprocessing options for document cleanup before conversion. */
data class PreprocessingOptions(
    /** Enable HTML preprocessing globally */
    val enabled: Boolean = true,
    /** Preprocessing preset level (Minimal, Standard, Aggressive) */
    val preset: PreprocessingPreset = PreprocessingPreset.STANDARD,
    /** Remove navigation elements (nav, breadcrumbs, menus, sidebars) */
    val removeNavigation: Boolean = true,
    /** Remove form elements (forms, inputs, buttons, etc.) */
    val removeForms: Boolean = true,
)
