// Generated by alef. Do not edit by hand.
// alef:hash:9209e42d9db964cfda3c6807610b9c1c805c4515b0d03cb106c19a8033f442d9

package io.xberg

class XbergBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
