#!/usr/bin/env python3
"""Align xberg integration packages with the core version.

The integrations under ``integrations/`` are versioned and published in lockstep
with the xberg core. This script reads the single source of truth (the root
``Cargo.toml`` version, including any ``-rc.N`` pre-release suffix) and writes it
to every integration manifest:

* the package's own ``version`` field, and
* its ``xberg`` dependency pin (floor).

Python manifests use the PEP 440 form (``1.0.0-rc.32`` -> ``1.0.0rc32``); the
Maven pom and the npm ``package.json`` manifests use the native form
(``1.0.0-rc.32``, which is also valid semver). npm packages pin ``@xberg-io/xberg``
exactly (not a floor). Run via ``task version:sync`` after ``alef sync-versions``
has synced the alef-managed binding manifests.

It also syncs the Helm chart (``charts/xberg/Chart.yaml`` + its README), which is both a
published OCI artifact and installable directly from a checkout.

It also syncs the coding-agent plugin: the ``[plugin].version`` field in
``plugin/.ai-rulez/config.toml`` (the single source ai-rulez generates from). The
generated plugin manifests under ``plugin/`` are regenerated by ``ai-rulez generate
--plugin`` (wired into ``task version:sync``) and their freshness is enforced by
``ai-rulez verify --plugin`` in CI, so this script only touches the config source.

Usage:
    python3 scripts/sync_integration_versions.py           # apply
    python3 scripts/sync_integration_versions.py --check    # verify (CI), exit 1 on drift
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Coding-agent plugin source of truth: ai-rulez generates every per-runtime manifest
# under plugin/ from this file's `[plugin].version`. Uses the native/semver form (also
# what ai-rulez expects); ai-rulez renders the PEP 440 form for the Hermes wheel. ~keep
PLUGIN_CONFIG = "plugin/.ai-rulez/config.toml"

# Helm chart. The chart is a published artifact (oci://ghcr.io/xberg-io/charts/xberg) AND is
# installable straight from a checkout, so its version has to track core like every other
# manifest here. It was not in VERSION_TARGETS and nothing else checked it, so it sat at
# 1.0.0-rc.25 while core moved on -- `helm install ./charts/xberg` deployed an rc image while
# this script reported "in sync". Chart.yaml carries the version four times (version,
# appVersion, the artifacthub.io/images tag that must match appVersion, and the
# artifacthub.io/prerelease flag that is derived from it) and the README twice, in the
# native/semver form Helm requires. ~keep
HELM_CHART = "charts/xberg/Chart.yaml"
HELM_CHART_README = "charts/xberg/README.md"
HELM_IMAGE_REPOSITORY = "ghcr.io/xberg-io/xberg"
SEMVER_PRERELEASE_IDENTIFIER = r"(?:0|[1-9]\d*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)"
SEMVER_PATTERN = re.compile(
    r"^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)"
    rf"(?:-(?P<prerelease>{SEMVER_PRERELEASE_IDENTIFIER}"
    rf"(?:\.{SEMVER_PRERELEASE_IDENTIFIER})*))?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)

# npm integration packages (package.json): version + exact `@xberg-io/xberg` pin,
# both in the native/semver form. The committed `package-lock.json` is intentionally NOT
# synced here: the core pin resolves to an rc that is published to npm only during the same
# release run, so its integrity/resolved cannot be generated ahead of time. The npm publish +
# CI jobs use `npm install` (not `npm ci`) to reconcile the core entry against the just-published
# version while preserving third-party pins. ~keep
NPM_MANIFESTS = [
    "integrations/node/n8n-nodes-xberg/package.json",
    "integrations/node/langchain-xberg/package.json",
    "integrations/node/llamaindex-xberg/package.json",
]

# Published manifests whose own `version` is aligned with core. ~keep
VERSION_TARGETS = [
    "integrations/python/crewai/pyproject.toml",
    "integrations/python/txtai/pyproject.toml",
    "integrations/python/surrealdb/pyproject.toml",
    "integrations/python/langchain/pyproject.toml",
    "integrations/python/llama-index/readers/llama-index-readers-xberg/pyproject.toml",
    "integrations/python/llama-index/node_parsers/llama-index-node-parser-xberg/pyproject.toml",
    "integrations/java/spring-ai/pom.xml",
    HELM_CHART,
    HELM_CHART_README,
    *NPM_MANIFESTS,
]

# All manifests that carry an `xberg` dependency pin to sync (superset of the
# above minus node-parser, plus the llama-index dev aggregator). ~keep
XBERG_DEP_MANIFESTS = [
    "integrations/python/crewai/pyproject.toml",
    "integrations/python/txtai/pyproject.toml",
    "integrations/python/surrealdb/pyproject.toml",
    "integrations/python/langchain/pyproject.toml",
    "integrations/python/llama-index/pyproject.toml",
    "integrations/python/llama-index/readers/llama-index-readers-xberg/pyproject.toml",
    "integrations/java/spring-ai/pom.xml",
    *NPM_MANIFESTS,
]


def core_version() -> str:
    text = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
    match = re.search(r'(?m)^version = "([^"]+)"', text)
    if not match:
        sys.exit("could not read version from Cargo.toml")
    return match.group(1)


def to_pep440(version: str) -> str:
    """Convert a Cargo pre-release (1.0.0-rc.32) to PEP 440 (1.0.0rc32)."""
    labels = {"alpha": "a", "beta": "b", "a": "a", "b": "b", "rc": "rc"}
    return re.sub(
        r"-(rc|alpha|beta|a|b)\.?(\d+)",
        lambda m: f"{labels[m.group(1)]}{m.group(2)}",
        version,
    )


def _single_metadata_value(text: str, pattern: str) -> str | None:
    matches = re.findall(pattern, text, flags=re.MULTILINE)
    return matches[0] if len(matches) == 1 else None


def helm_metadata_errors(chart: str, expected_version: str) -> list[str]:
    """Validate release-sensitive Chart.yaml metadata before publishing."""
    semver = SEMVER_PATTERN.fullmatch(expected_version)
    if semver is None:
        return [f"release version is not valid SemVer: {expected_version}"]

    fields = {
        "chart version": _single_metadata_value(chart, r"^version:\s*[\"']?([^\"'\s]+)[\"']?\s*$"),
        "chart appVersion": _single_metadata_value(chart, r"^appVersion:\s*[\"']?([^\"'\s]+)[\"']?\s*$"),
        "Artifact Hub image tag": _single_metadata_value(
            chart,
            rf"^\s*image:\s*[\"']?{re.escape(HELM_IMAGE_REPOSITORY)}:([^\"'\s]+)[\"']?\s*$",
        ),
        "Artifact Hub prerelease": _single_metadata_value(
            chart,
            r'^\s*artifacthub\.io/prerelease:\s*["\']?(true|false)["\']?\s*$',
        ),
    }
    expected = {
        "chart version": expected_version,
        "chart appVersion": expected_version,
        "Artifact Hub image tag": expected_version,
        "Artifact Hub prerelease": "true" if semver.group("prerelease") else "false",
    }
    missing_names = {
        "chart version": "version",
        "chart appVersion": "appVersion",
        "Artifact Hub image tag": "artifacthub.io/images xberg image",
        "Artifact Hub prerelease": "artifacthub.io/prerelease",
    }

    errors = []
    for name, value in fields.items():
        if value is None:
            errors.append(f"chart is missing {missing_names[name]}")
        elif value != expected[name]:
            errors.append(f"{name} is {value}, expected {expected[name]}")
    return errors


def transform(rel: str, sync_version: bool, sync_dep: bool, maven: str, pep440: str) -> tuple[str, str]:
    path = ROOT / rel
    original = path.read_text(encoding="utf-8")
    updated = original
    if rel == HELM_CHART:
        if sync_version:
            updated = re.sub(r"(?m)^version: .*$", f"version: {maven}", updated, count=1)
            updated = re.sub(r"(?m)^appVersion: .*$", f'appVersion: "{maven}"', updated, count=1)
            # The artifacthub.io/images tag documents the image `helm install` actually
            # resolves (values.image.tag defaults to .Chart.AppVersion), so it must move
            # with appVersion or ArtifactHub advertises an image the chart never deploys.
            updated = re.sub(r"(?m)^(\s*image: ghcr\.io/xberg-io/xberg:).*$", rf"\g<1>{maven}", updated)
            # A version with no pre-release suffix is, by definition, not a prerelease.
            semver = SEMVER_PATTERN.fullmatch(maven)
            if semver is None:
                sys.exit(f"cannot sync invalid SemVer release: {maven}")
            prerelease = "true" if semver.group("prerelease") else "false"
            updated = re.sub(r'(?m)^(\s*artifacthub\.io/prerelease: ")[^"]*(")', rf"\g<1>{prerelease}\g<2>", updated)
        return original, updated
    if rel == HELM_CHART_README:
        if sync_version:
            updated = re.sub(r"--version \S+", f"--version {maven}", updated)
        return original, updated
    if rel.endswith(".xml"):
        if sync_version:
            updated = re.sub(r"<version>[^<]*</version>", f"<version>{maven}</version>", updated, count=1)
        if sync_dep:
            updated = re.sub(
                r"<xberg\.version>[^<]*</xberg\.version>",
                f"<xberg.version>{maven}</xberg.version>",
                updated,
            )
    elif rel.endswith(".json"):
        if sync_version:
            updated = re.sub(r'(?m)^(\s*"version":\s*)"[^"]*"', rf'\g<1>"{maven}"', updated, count=1)
        if sync_dep:
            updated = re.sub(r'("@xberg-io/xberg":\s*)"[^"]*"', rf'\g<1>"{maven}"', updated)
    else:
        if sync_version:
            updated = re.sub(r'(?m)^version = "[^"]*"', f'version = "{pep440}"', updated, count=1)
        if sync_dep:
            updated = re.sub(r'(?<![\w.-])xberg>=[^"\',\]]+', f"xberg>={pep440}", updated)
    return original, updated


def transform_plugin(version: str) -> tuple[str, str]:
    """Rewrite `version` inside the `[plugin]` table (not the top-level ai-rulez
    schema `version = "4.0"`) of the plugin config.
    """
    path = ROOT / PLUGIN_CONFIG
    original = path.read_text(encoding="utf-8")
    updated = re.sub(
        r'(\[plugin\][^\[]*?\nversion = ")[^"]*(")',
        rf"\g<1>{version}\g<2>",
        original,
        count=1,
        flags=re.DOTALL,
    )
    return original, updated


def main() -> int:
    check = "--check" in sys.argv[1:]
    maven = os.environ.get("RELEASE_VERSION", core_version()) if check else core_version()
    pep440 = to_pep440(maven)

    targets: dict[str, tuple[bool, bool]] = {}
    for rel in VERSION_TARGETS:
        targets[rel] = (True, rel in XBERG_DEP_MANIFESTS)
    for rel in XBERG_DEP_MANIFESTS:
        sync_version, _ = targets.get(rel, (False, False))
        targets[rel] = (sync_version, True)

    drift = []
    for rel, (sync_version, sync_dep) in sorted(targets.items()):
        original, updated = transform(rel, sync_version, sync_dep, maven, pep440)
        if original == updated:
            continue
        drift.append(rel)
        if not check:
            (ROOT / rel).write_text(updated, encoding="utf-8")

    plugin_original, plugin_updated = transform_plugin(maven)
    if plugin_original != plugin_updated:
        drift.append(PLUGIN_CONFIG)
        if not check:
            (ROOT / PLUGIN_CONFIG).write_text(plugin_updated, encoding="utf-8")

    if check:
        helm_errors = helm_metadata_errors((ROOT / HELM_CHART).read_text(encoding="utf-8"), maven)
        if drift or helm_errors:
            print(f"integration versions out of sync with core {maven}:")
            for rel in drift:
                print(f"  - {rel}")
            for error in helm_errors:
                print(f"  - {error}")
            print("run: task version:sync")
            return 1
        print(f"integration versions in sync with core {maven}")
        return 0

    if drift:
        print(f"aligned {len(drift)} integration manifest(s) to xberg {maven} (python: {pep440})")
        for rel in drift:
            print(f"  - {rel}")
    else:
        print(f"integration manifests already at xberg {maven}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
