// DO NOT EDIT - auto-generated by alef
// alef:hash:cee34a502faf9667f6b3ceecc8972f4559075bf49b58f1446293333a289f46a2
package io.xberg;

/**
 * The meta-schema itself failed to compile.
 */
public class BadMetaSchemaException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BadMetaSchemaException with the given message. */
  public BadMetaSchemaException(final String message) {
    super(message);
  }

  /** Creates a new BadMetaSchemaException with the given message and cause. */
  public BadMetaSchemaException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
