// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8b8b082d244dff16e3159a12816cf2ecf50201546651f0d2742c668c096ac8b6
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/**
 * Chunk-classification enrichment knob: how to multi-label individual chunks.
 *
 * Operates on {@code ExtractedDocument.chunks} in place — the caller must have
 * already produced chunks (e.g. via {@code ExtractionConfig.chunking}) for this
 * stage to have any effect; a document with no chunks is a no-op.
 */
public record ChunkClassificationEnrichmentConfig(ChunkClassificationConfig config) {
}
