// DO NOT EDIT - auto-generated by alef
// alef:hash:2a742efc38bc594a1d8e4a06adbab56b24551c20dcb7c4068490d4d15df3e486
package io.xberg;

/**
 * Invalid configuration value.
 */
public class ConfigErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConfigErrorException with the given message. */
  public ConfigErrorException(final String message) {
    super(message);
  }

  /** Creates a new ConfigErrorException with the given message and cause. */
  public ConfigErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
