// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b36e6d65146dcfc871198b2d5ed63703fd8da48b24a01e56ee1e0953f40e2e3b
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Content filter applied to each crawled page before it reaches the result.
 */
@SuppressWarnings("PMD")
public enum ContentFilterKind {
    /**
     * Keep only pages scoring at or above {@code bm25_threshold} for {@code bm25_query}.
     */
    Bm25("bm25");


    /** The string value. */
    private final String value;

    ContentFilterKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ContentFilterKind fromValue(final String value) {
        for (ContentFilterKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ContentFilterKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
