// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1a6a27fef6eef9206d7d93fc3771c9971fdf1b9f92f11466e64cd92f2d72b017
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown when an FFI value conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends XbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(1, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
