// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:88359e143554f99541a8a923dee9dd9804b8e8c37606adbb36336d2b2f37b1a6
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown when the Rust core reports an unknown error. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class CoreErrorException extends XbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CoreErrorException. */
  public CoreErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new CoreErrorException with a cause. */
  public CoreErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
