// DO NOT EDIT - auto-generated by alef
// alef:hash:46b03e9aff53178215502122f15d5dc6ed22cce8886e218e2fc0a7d1dca994ac
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeserializeException with the given message. */
  public DeserializeException(final String message) {
    super(message);
  }

  /** Creates a new DeserializeException with the given message and cause. */
  public DeserializeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
