// DO NOT EDIT - auto-generated by alef
// alef:hash:68711cca49c232c5f39efba75b5b4e9988cd9c615c54a8f607ce4c8806f36715
package io.xberg;

/**
 * The embedding model or embedding pipeline returned an error.
 */
public class EmbeddingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new EmbeddingException with the given message. */
  public EmbeddingException(final String message) {
    super(message);
  }

  /** Creates a new EmbeddingException with the given message and cause. */
  public EmbeddingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
