// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3435c5eaa93adb609d272830d02832d3e42d6ec3e77e0ffe804bb850adff32e
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Formula recognition model selection.
 */
@SuppressWarnings("PMD")
public enum FormulaModel {
    /**
     * RapidLaTeXOCR (MIT, pix2tex-derived): resizer + encoder + decoder ONNX,
     * ~180 MB total, downloaded on demand.
     */
    LatexOcr("latex_ocr");


    /** The string value. */
    private final String value;

    FormulaModel(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static FormulaModel fromValue(final String value) {
        for (FormulaModel e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown FormulaModel value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
