// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1779e51b2985e22d8e7f420d7357e3330ba5bbec9cf55d328211018474505172
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Heading style options for Markdown output.
 *
 * Controls how headings (h1-h6) are rendered in the output Markdown.
 */
@SuppressWarnings("PMD")
public enum HeadingStyle {
    /**
     * Underlined style (=== for h1, --- for h2).
     */
    Underlined("Underlined"),
    /**
     * ATX style (# for h1, ## for h2, etc.). Default.
     */
    Atx("Atx"),
    /**
     * ATX closed style (# title #, with closing hashes).
     */
    AtxClosed("AtxClosed");


    /** The string value. */
    private final String value;

    HeadingStyle(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static HeadingStyle fromValue(final String value) {
        for (HeadingStyle e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown HeadingStyle value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
