// DO NOT EDIT - auto-generated by alef
// alef:hash:b8f934e61e85d82f6d8337b976d0d645d4a4aa40d68a48be2f6db96c58dbb683
package io.xberg;

/**
 * The preset's declared `id` does not match its file-system location.
 */
public class IdMismatchException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IdMismatchException with the given message. */
  public IdMismatchException(final String message) {
    super(message);
  }

  /** Creates a new IdMismatchException with the given message and cause. */
  public IdMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
