// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a5b545f9fb30513e01c3b40537b9ff8ce765ec738de45174ce0f3b6f94c6df2e
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Horizontal and vertical image resolution in dots per inch.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImageDpi.Builder.class)
public record ImageDpi(
    @JsonProperty("horizontal") double horizontal,
    @JsonProperty("vertical") double vertical
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for ImageDpi deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private double horizontal;
        private double vertical;

        /** Sets the horizontal field. */
        @JsonProperty("horizontal")
        public Builder withHorizontal(final double value) {
            this.horizontal = value;
            return this;
        }

        /** Sets the vertical field. */
        @JsonProperty("vertical")
        public Builder withVertical(final double value) {
            this.vertical = value;
            return this;
        }

        /** Constructs a ImageDpi instance from the builder's current state. */
        public ImageDpi build() {
            return new ImageDpi(
                horizontal,
                vertical
            );
        }
    }
    // CPD-ON
}
