// DO NOT EDIT - auto-generated by alef
// alef:hash:21d089827fde2c9a1e0aed996cf635fbfda6f3b200c772c992dc8c348f1dac5f
package io.xberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ImageProcessingException with the given message. */
  public ImageProcessingException(final String message) {
    super(message);
  }

  /** Creates a new ImageProcessingException with the given message and cause. */
  public ImageProcessingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
