// DO NOT EDIT - auto-generated by alef
// alef:hash:cf57a23ee7d481cad41a75e066d5a5993b7d58d8518dffb074388bf317d3a62d
package io.xberg;

/**
 * A filesystem I/O error occurred while reading a preset directory.
 */
public class IoException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoException with the given message. */
  public IoException(final String message) {
    super(message);
  }

  /** Creates a new IoException with the given message and cause. */
  public IoException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
