// DO NOT EDIT - auto-generated by alef
// alef:hash:147c2d4c5df7e4d71bc38e912a58f5e90720d90d41dd3aa0b713c659642fece4
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new LoadErrorException with the given message. */
  public LoadErrorException(final String message) {
    super(message);
  }

  /** Creates a new LoadErrorException with the given message and cause. */
  public LoadErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
