// DO NOT EDIT - auto-generated by alef
// alef:hash:9fe8892221d97ca5b3afd9c793746eb66a4c41b0bc5a9e2fd85a8486c1900a96
package io.xberg;

/**
 * A required optional system dependency (e.g. `tesseract`) was not found.
 */
public class MissingDependencyException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new MissingDependencyException with the given message. */
  public MissingDependencyException(final String message) {
    super(message);
  }

  /** Creates a new MissingDependencyException with the given message and cause. */
  public MissingDependencyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
