// DO NOT EDIT - auto-generated by alef
// alef:hash:804410c71c1b717e724908248acb2c84b7f8df23be15d811b33d978dd2546ceb
package io.xberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OcrException with the given message. */
  public OcrException(final String message) {
    super(message);
  }

  /** Creates a new OcrException with the given message and cause. */
  public OcrException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
