// DO NOT EDIT - auto-generated by alef
// alef:hash:d6e700e14e63a9c288f82d68eddcb7bc384d1854f108b0c991f4ae18f04a75c2
package io.xberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
