// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f67bf88a6209e5611019c2133c80ff551e37fa9c74e216da670613529055d2e9
// To regenerate: alef generate
// To verify freshness: alef verify

/**
 * High-performance document intelligence library
 */
package io.xberg;
