// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

/**
 * High-performance document intelligence library
 */
package io.xberg;
