// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8b7a3b4a08160031fb3b2c143d9b98d530ce27b6cfb5661eb3821a0342896860
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown when a Rust panic is contained at the FFI boundary. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class PanicException extends XbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PanicException. */
  public PanicException(final String message) {
    super(3, message);
  }

  /** Creates a new PanicException with a cause. */
  public PanicException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
