// DO NOT EDIT - auto-generated by alef
// alef:hash:cf5789e15fb2dc7e90530915a3eea6748633560aa94cdd3c55e8472221920101
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
