// DO NOT EDIT - auto-generated by alef
// alef:hash:79324dccde2b1e8c0e546384398a72de7c5c18d9f1eae4d3b41ed72f5208c943
package io.xberg;

/**
 * A registered plugin returned an error during extraction.
 */
public class PluginException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PluginException with the given message. */
  public PluginException(final String message) {
    super(message);
  }

  /** Creates a new PluginException with the given message and cause. */
  public PluginException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
