// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1a4ad7a2606b4fe3ad557ebd3db80d59a57e0cc3f3d4d4b064857ccb423b28df
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Classification of a detected layout region that warrants VLM extraction.
 */
@SuppressWarnings("PMD")
public enum RegionKind {
    /**
     * A figure, diagram, chart, or image region.
     */
    Figure("Figure"),
    /**
     * A densely formatted or complex table.
     */
    DenseTable("DenseTable"),
    /**
     * A region with complex or mixed layout.
     */
    ComplexLayout("ComplexLayout"),
    /**
     * A standalone image to caption.
     */
    Caption("Caption");


    /** The string value. */
    private final String value;

    RegionKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static RegionKind fromValue(final String value) {
        for (RegionKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown RegionKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
