// DO NOT EDIT - auto-generated by alef
// alef:hash:b61e9bc1d2548e667d946252a8fa94f7580c83e532fc291d99c5ad7b240cd866
package io.xberg;

/**
 * The reranker model or reranking pipeline returned an error.
 */
public class RerankingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RerankingException with the given message. */
  public RerankingException(final String message) {
    super(message);
  }

  /** Creates a new RerankingException with the given message and cause. */
  public RerankingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
