// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:df9240b3c6b945187ec2bb8ab846bb55de266137ecc71c9232d0a5e7cc975191
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

import java.util.List;

/**
 * Path A Bridge implementation for IRerankerBackend.
 *
 * Wraps a user-supplied implementation and delegates all method calls.
 * This adapter conforms to the hand-authored sealed interface.
 */
public final class RerankerBackendAdapter implements IRerankerBackend {
    private final IRerankerBackend impl;

    public RerankerBackendAdapter(IRerankerBackend impl) {
        this.impl = impl;
    }

    @Override
    public String name() {
        return impl.name();
    }

    @Override
    public String version() {
        return impl.version();
    }

    @Override
    public void initialize() throws Exception {
        impl.initialize();
    }

    @Override
    public void shutdown() throws Exception {
        impl.shutdown();
    }

    @Override
    public List<Float> rerank(String query, List<String> documents) throws Exception {
        return impl.rerank(query, documents);
    }


}
