// DO NOT EDIT - auto-generated by alef
// alef:hash:45ce11a973b3c9e47750eed95969fd7edad17b4cac258ddefb3d92ad2c39846c
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaValidationException with the given message. */
  public SchemaValidationException(final String message) {
    super(message);
  }

  /** Creates a new SchemaValidationException with the given message and cause. */
  public SchemaValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
