// DO NOT EDIT - auto-generated by alef
// alef:hash:698da937f40dea1bb7c38e8e2fbb14fd894dc68541e9fb1ec361a76d2468f3e9
package io.xberg;

/**
 * A custom schema override was supplied but is not a JSON object.
 */
public class SchemaNotObjectException extends ResolveErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaNotObjectException with the given message. */
  public SchemaNotObjectException(final String message) {
    super(message);
  }

  /** Creates a new SchemaNotObjectException with the given message and cause. */
  public SchemaNotObjectException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
