// DO NOT EDIT - auto-generated by alef
// alef:hash:9eae3c8ad8dcd8c4dafbcb12bd506b8aa7b34b66734b64f23b3f9260eeaa5648
package io.xberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SecurityException with the given message. */
  public SecurityException(final String message) {
    super(message);
  }

  /** Creates a new SecurityException with the given message and cause. */
  public SecurityException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
