// DO NOT EDIT - auto-generated by alef
// alef:hash:712855d256b25e87a70f3b18b0232a2e920b8fb39b57db6704f704f5b5dc207c
package io.xberg;

/**
 * JSON or MessagePack serialization/deserialization failed.
 */
public class SerializationException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SerializationException with the given message. */
  public SerializationException(final String message) {
    super(message);
  }

  /** Creates a new SerializationException with the given message and cause. */
  public SerializationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
