// DO NOT EDIT - auto-generated by alef
// alef:hash:430fbfc38ed42163e622db2bf852ca686d0fa9164de13ca3cbafe7a6ab68d5f2
package io.xberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new UnsupportedFormatException with the given message. */
  public UnsupportedFormatException(final String message) {
    super(message);
  }

  /** Creates a new UnsupportedFormatException with the given message and cause. */
  public UnsupportedFormatException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
