// DO NOT EDIT - auto-generated by alef
// alef:hash:2ac45d02b05c086dbabad095312397a17f58db7fc789468939f74c1170a449cb
package io.xberg;

/**
 * Invalid configuration or input parameters were supplied.
 */
public class ValidationException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ValidationException with the given message. */
  public ValidationException(final String message) {
    super(message);
  }

  /** Creates a new ValidationException with the given message and cause. */
  public ValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
