# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0a917a04e1a54c84b1cb9934013317302c32835a3bb2a02a5dd18c4d5b7a75a9
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'embedding_backend_management' do

  it 'embedding_backends_clear: Clear all embedding backends and verify list is empty' do
    expect { Xberg.clear_embedding_backends() }.not_to raise_error

  end


  it 'embedding_backends_list: List all registered embedding backends' do
    result = Xberg.list_embedding_backends()

    expect(result).not_to be_nil
  end

end
