# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c438481b4d2765e7a7c825b7d74e480be6b87eaad33d15ccd03ca2193246a06a
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'post_processor_management' do

  it 'post_processors_clear: Clear all post-processors and verify list is empty' do
    expect { Xberg.clear_post_processors() }.not_to raise_error

  end


  it 'post_processors_list: List all registered post-processors' do
    result = Xberg.list_post_processors()

    expect(result).not_to be_nil
  end

end
