# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62b3c743ab8b3d793d5f5763b833d8a49b6d695f44636d4f97f55e616243532c
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'renderer_management' do

  it 'renderers_clear: Clear all renderers and verify list is empty' do
    expect { Xberg.clear_renderers() }.not_to raise_error

  end


  it 'renderers_list: List all registered renderers' do
    result = Xberg.list_renderers()

    expect(result).not_to be_nil
  end

end
