# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ae9a81efda55fa0a65d8dfb17e991d4fdcc432147dc9518d04deb3010bfb7830
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'summarization' do

  it 'summarization_extractive_smoke: TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required.' do
    input_mock_base_url = ENV.fetch('MOCK_SERVER_SUMMARIZATION_EXTRACTIVE_SMOKE', nil) || "#{ENV.fetch('MOCK_SERVER_URL')}/fixtures/summarization_extractive_smoke"
    result = Xberg.extract(Xberg::ExtractInput.new(kind: 'uri', uri: '$mock_url/text/book_war_and_peace_1p.txt'.gsub('$mock_url', input_mock_base_url)), Xberg::ExtractionConfig.new(summarization: { 'max_tokens' => 80, 'strategy' => 'extractive' }))
    expect(result.results[0].mime_type.to_s).to eq('text/plain')
    expect(result.results[0].summary.text.respond_to?(:empty?) ? !result.results[0].summary.text.empty? : !result.results[0].summary.text.nil?).to be(true)
    expect(result.results[0].summary.strategy.to_s).to eq('extractive')

  end

end
