# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:05082979b5300c995e4e308e162a90b3fe59c5202c17e9289e1174e0e7346344
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.1.0"
end
