<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:55b0addc1b7d5d9be17dac15eef7c2625b399ddff060e35b97e0708f8b156e3f
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Xberg;

/**
 * Compiled meta-schema validator over `preset.schema.json`.
 */
final class MetaSchema
{
    /**
     * Validate `raw` against the meta-schema and deserialize into a `Preset`,
     */
    public function parsePreset(string $path, string $raw): Preset
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }

    /**
     * Compile the given JSON text as a Draft 2020-12 meta-schema.
     */
    public static function compile(string $meta_schema_json): MetaSchema
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
