// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6fd45fceec1cfb2eab618a42d2ed3d7c976d92950cc8820875c5479313ebfd7d
// To regenerate: alef generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'package:xberg/xberg.dart';
import 'package:xberg/src/xberg_bridge_generated/frb_generated.dart' show RustLib;
import 'dart:ffi';
import 'package:ffi/ffi.dart';

// E2e tests for category: ocr_backend_management

void _setEnv(String key, String value) {
  final libc = DynamicLibrary.process();
  final setenv = libc.lookupFunction<
      Int32 Function(Pointer<Utf8>, Pointer<Utf8>, Int32),
      int Function(Pointer<Utf8>, Pointer<Utf8>, int)>('setenv');
  final keyPtr = key.toNativeUtf8();
  final valuePtr = value.toNativeUtf8();
  try {
    final result = setenv(keyPtr, valuePtr, 1);
    if (result != 0) {
      throw StateError('setenv failed for ${key}=${value} with return code $result');
    }
  } finally {
    calloc.free(keyPtr);
    calloc.free(valuePtr);
  }
}

void main() {
  var _rustLibInitialized = false;

  setUpAll(() async {
    _setEnv('CRAWLBERG_ALLOW_PRIVATE_NETWORK', 'true');
    await RustLib.init();
    _rustLibInitialized = true;
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
  });

  test('Clear all OCR backends and verify list is empty', () async {
    await expectLater(XbergBridge.clearOcrBackends(), completes);
  });

  test('List all registered OCR backends', () async {
    final result = await XbergBridge.listOcrBackends();
    expect(result, isNotNull);
  });

  test('Unregister nonexistent OCR backend gracefully', () async {
    await expectLater(XbergBridge.unregisterOcrBackend('nonexistent-backend-xyz'), completes);
  });

}
