// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8311b2065939ac43a60f77462bd505f1e14af9fefa0c5580cf7e97c4abe0b4e9
// To regenerate: alef generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'dart:io';
import 'package:xberg/xberg.dart';
import 'package:xberg/src/xberg_bridge_generated/frb_generated.dart' show RustLib;
import 'dart:async';
import 'dart:convert';
import 'dart:ffi';
import 'package:ffi/ffi.dart';

// E2e tests for category: url

Process? _sutProcess;
String? _spawnedSutUrl;
final Map<String, String> _fixtureUrls = <String, String>{};

String _sutUrl() => _spawnedSutUrl ?? Platform.environment['MOCK_SERVER_URL'] ?? Platform.environment['SUT_URL'] ?? 'http://localhost:8008';

String _fixtureUrl(String fixtureId) {
  final perFixture = _fixtureUrls[fixtureId];
  if (perFixture != null) return perFixture;
  final env = Platform.environment['MOCK_SERVERS'];
  if (env != null && env.isNotEmpty) {
    try {
      final decoded = jsonDecode(env);
      if (decoded is Map && decoded[fixtureId] is String) {
        return decoded[fixtureId] as String;
      }
    } catch (_) {}
  }
  return '${_sutUrl()}/fixtures/$fixtureId';
}

void _setEnv(String key, String value) {
  final libc = DynamicLibrary.process();
  final setenv = libc.lookupFunction<
      Int32 Function(Pointer<Utf8>, Pointer<Utf8>, Int32),
      int Function(Pointer<Utf8>, Pointer<Utf8>, int)>('setenv');
  final keyPtr = key.toNativeUtf8();
  final valuePtr = value.toNativeUtf8();
  try {
    final result = setenv(keyPtr, valuePtr, 1);
    if (result != 0) {
      throw StateError('setenv failed for ${key}=${value} with return code $result');
    }
  } finally {
    calloc.free(keyPtr);
    calloc.free(valuePtr);
  }
}

void main() {
  var _rustLibInitialized = false;

  setUpAll(() async {
    _setEnv('CRAWLBERG_ALLOW_PRIVATE_NETWORK', 'true');
    await RustLib.init();
    _rustLibInitialized = true;
    if (Platform.environment['MOCK_SERVER_URL'] == null && Platform.environment['SUT_URL'] == null) {
      final _harness = Directory.current.uri.resolve('app_harness.dart').toFilePath();
      if (File(_harness).existsSync()) {
        _sutProcess = await Process.start('dart', ['run', _harness], mode: ProcessStartMode.normal);
        final _ready = Completer<void>();
        _sutProcess!.stdout
            .transform(utf8.decoder)
            .transform(const LineSplitter())
            .listen((_line) {
          final _trimmed = _line.trim();
          if (_trimmed.startsWith('SUT_URL=')) {
            _spawnedSutUrl = _trimmed.substring('SUT_URL='.length);
            if (!_ready.isCompleted) _ready.complete();
          }
        }, onDone: () {
          if (!_ready.isCompleted) _ready.complete();
        });
        await _ready.future.timeout(const Duration(seconds: 15), onTimeout: () {});
      } else {
        // Standalone mock-server mode: build if missing, then spawn.
        final _mockBin = Directory.current.uri.resolve('../rust/target/release/mock-server').toFilePath();
        final _mockManifest = Directory.current.uri.resolve('../rust/Cargo.toml').toFilePath();
        if (!File(_mockBin).existsSync()) {
          final _build = await Process.run('cargo', ['build', '--release', '--manifest-path', _mockManifest, '--bin', 'mock-server']);
          if (_build.exitCode != 0) throw StateError('mock-server build failed: ${_build.stderr}');
        }
        final _fixturesDir = Directory.current.uri.resolve('../../fixtures').toFilePath();
        _sutProcess = await Process.start(_mockBin, [_fixturesDir], mode: ProcessStartMode.normal);
        final _ready2 = Completer<void>();
        _sutProcess!.stdout
            .transform(utf8.decoder)
            .transform(const LineSplitter())
            .listen((_line) {
          final _trimmed = _line.trim();
          if (_trimmed.startsWith('MOCK_SERVER_URL=')) {
            _spawnedSutUrl = _trimmed.substring('MOCK_SERVER_URL='.length);
          }
          if (_trimmed.startsWith('MOCK_SERVERS=')) {
            final _payload = _trimmed.substring('MOCK_SERVERS='.length);
            try {
              final _decoded = jsonDecode(_payload);
              if (_decoded is Map) {
                _decoded.forEach((k, v) {
                  if (k is String && v is String) {
                    _fixtureUrls[k] = v;
                  }
                });
              }
            } catch (_) {}
            if (!_ready2.isCompleted) _ready2.complete();
          } else if (_spawnedSutUrl != null) {
            if (!_ready2.isCompleted) _ready2.complete();
          }
        }, onDone: () {
          if (!_ready2.isCompleted) _ready2.complete();
        });
        await _ready2.future.timeout(const Duration(seconds: 60), onTimeout: () {});
      }
    }
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
    final proc = _sutProcess;
    if (proc != null) {
      proc.kill();
      await proc.exitCode;
    }
  });

  test('extract_batch: mixed bytes and URL inputs share one output envelope', () async {
    final inputsMockBaseUrl = _fixtureUrl("url_batch_mixed_inputs");
    final inputsJson = r'[{"kind":"uri","uri":"$mock_url"},{"bytes":[66,97,116,99,104,32,98,121,116,101,115,32,99,111,110,116,101,110,116],"filename":"inline.txt","kind":"bytes","mime_type":"text/plain"}]'.replaceAll(r'$mock_url', inputsMockBaseUrl);
    final inputs = await Future.wait((jsonDecode(inputsJson) as List<dynamic>).cast<Map<String, dynamic>>().map((m) => createExtractInputFromJson(json: jsonEncode(m))));
    final config = await createExtractionConfigFromJson(json: '{"url":{"mode":"document"}}');
    final result = await XbergBridge.extractBatch(inputs, config: config);
    expect(result.results.length, greaterThanOrEqualTo(2));
    expect(result.results[0].content, contains('Batch URL document content'));
    expect(result.results[1].content, contains('Batch bytes content'));
  });

  test('extract: crawl mode follows linked pages', () async {
    final inputMockBaseUrl = _fixtureUrl("url_crawl_linked_pages");
    final inputJson = '{"kind":"uri","uri":"\$mock_url"}'.replaceAll(r'$mock_url', inputMockBaseUrl);
    final input = await createExtractInputFromJson(json: inputJson);
    final config = await createExtractionConfigFromJson(json: '{"url":{"crawl":{"max_depth":1,"max_pages":4,"respect_robots_txt":false},"mode":"crawl"}}');
    final result = await XbergBridge.extract(input, config: config);
    expect(result.summary.pagesCrawled, greaterThanOrEqualTo(2));
    expect(result.results[1].content, contains('About crawl target'));
  });

  test('extract: website URL returns page content', () async {
    final inputMockBaseUrl = _fixtureUrl("url_html_page_extract");
    final inputJson = '{"kind":"uri","uri":"\$mock_url"}'.replaceAll(r'$mock_url', inputMockBaseUrl);
    final input = await createExtractInputFromJson(json: inputJson);
    final config = await createExtractionConfigFromJson(json: '{"url":{"mode":"document"}}');
    final result = await XbergBridge.extract(input, config: config);
    expect(result.results[0].content, contains('Xberg URL Page'));
    expect(result.results.length, greaterThanOrEqualTo(1));
  });

  test('extract: recursive URL extraction follows document links discovered in results', () async {
    final inputMockBaseUrl = _fixtureUrl("url_recursive_document_urls");
    final inputJson = '{"kind":"uri","uri":"\$mock_url"}'.replaceAll(r'$mock_url', inputMockBaseUrl);
    final input = await createExtractInputFromJson(json: inputJson);
    final config = await createExtractionConfigFromJson(json: '{"url":{"crawl":{"document_url_depth":1,"follow_document_urls":true,"respect_robots_txt":false},"mode":"document"}}');
    final result = await XbergBridge.extract(input, config: config);
    expect(result.results.length, greaterThanOrEqualTo(2));
    expect(result.results[1].content, contains('Recursive document target'));
  });

  test('extract: remote text document URL', () async {
    final inputMockBaseUrl = _fixtureUrl("url_remote_text_document");
    final inputJson = '{"kind":"uri","uri":"\$mock_url"}'.replaceAll(r'$mock_url', inputMockBaseUrl);
    final input = await createExtractInputFromJson(json: inputJson);
    final config = await createExtractionConfigFromJson(json: '{"url":{"mode":"document"}}');
    final result = await XbergBridge.extract(input, config: config);
    expect(result.results[0].content, contains('Remote document hello'));
    expect(result.summary.remoteUrls, equals(1));
  });

}
