// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:70c1bb432d22f833b48546066e56502dbec29164332de7241216b1d0d61574ba
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: embedding_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_EmbeddingBackendsClear(t *testing.T) {
	// Clear all embedding backends and verify list is empty
	result := xberg.ClearEmbeddingBackends()
	if result == nil {
		t.Fatalf("expected non-nil result")
	}
}

func Test_EmbeddingBackendsList(t *testing.T) {
	// List all registered embedding backends
	_, err := xberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
