// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0f7ddde227346746e4aa716c970301ba75e703e006b87114f1370a78c71524e
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: ocr_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_OcrBackendsClear(t *testing.T) {
	// Clear all OCR backends and verify list is empty
	result := xberg.ClearOcrBackends()
	if result == nil {
		t.Fatalf("expected non-nil result")
	}
}

func Test_OcrBackendsList(t *testing.T) {
	// List all registered OCR backends
	_, err := xberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OcrBackendsUnregister(t *testing.T) {
	// Unregister nonexistent OCR backend gracefully
	result := xberg.UnregisterOcrBackend(`nonexistent-backend-xyz`)
	if result == nil {
		t.Fatalf("expected non-nil result")
	}
}
