// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f0a0291d90e122fb7723ca3096e328f2770cd3bf3c5500c7ec8565ccca8c4e74
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: tokenizer_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_TokenizerBackendsClear(t *testing.T) {
	// Clear all tokenizer backends and verify list is empty
	result := xberg.ClearTokenizerBackends()
	if result == nil {
		t.Fatalf("expected non-nil result")
	}
}

func Test_TokenizerBackendsList(t *testing.T) {
	// List all registered tokenizer backends
	_, err := xberg.ListTokenizerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
