// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:772f3bac8008858ed0435f91676442316045d50835959fb4b49e806bf64db551
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: validator_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_ValidatorsClear(t *testing.T) {
	// Clear all validators and verify list is empty
	result := xberg.ClearValidators()
	if result == nil {
		t.Fatalf("expected non-nil result")
	}
}

func Test_ValidatorsList(t *testing.T) {
	// List all registered validators
	_, err := xberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
